force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Customer_Assignment__c/Employee_Customer_Assignment__c.object-meta.xml
<CustomObject>
    <label>Employee Customer Assignment</label>
    <nameField>
        <displayFormat>ECA-{0000}</displayFormat>
        <label>Customer Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Customer Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Customer_Assignment__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Employee Customer Assignments</relationshipLabel>
    <relationshipName>Employee_Customer_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee_Customer_Assignment__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Employee Customer Assignments</relationshipLabel>
    <relationshipName>Employee_Customer_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee_Customer_Assignment__c/fields/Executive__c.field-meta.xml
<CustomField>
    <fullName>Executive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Executive</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employee_Customer_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Junction_Beat__c/Junction_Beat__c.object-meta.xml
<CustomObject>
    <label>Beat Item</label>
    <nameField>
        <displayFormat>ITEM - {0000}</displayFormat>
        <label>Beat Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Beat Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Junction_Beat__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Junction_Beats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Junction_Beat__c/fields/Account_Customer_Code__c.field-meta.xml
<CustomField>
    <fullName>Account_Customer_Code__c</fullName>
    <formula>IF(Beat_Type__c == &apos;Primary&apos;, Account__r.SAP_Customer_Code__c , Account__r.Outlet_Id__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Customer Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Junction_Beat__c/fields/Beat_Owner_Employee_Code__c.field-meta.xml
<CustomField>
    <fullName>Beat_Owner_Employee_Code__c</fullName>
    <formula>Child_beat__r.Owner_Employee_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Beat Owner Employee Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Junction_Beat__c/fields/Beat_OwnerId__c.field-meta.xml
<CustomField>
    <fullName>Beat_OwnerId__c</fullName>
    <formula>CASESAFEID( Child_beat__r.OwnerId)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Beat OwnerId</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Junction_Beat__c/fields/Beat_Primary_Customer__c.field-meta.xml
<CustomField>
    <fullName>Beat_Primary_Customer__c</fullName>
    <formula>CASESAFEID(Child_beat__r.Primary_Customer__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Beat Primary Customer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Junction_Beat__c/fields/Beat_Primary_Customer_Code__c.field-meta.xml
<CustomField>
    <fullName>Beat_Primary_Customer_Code__c</fullName>
    <formula>Child_beat__r.Primary_Customer_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Beat Primary Customer Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Junction_Beat__c/fields/Beat_Sub_Stockist_Outlet_Code__c.field-meta.xml
<CustomField>
    <fullName>Beat_Sub_Stockist_Outlet_Code__c</fullName>
    <formula>Child_beat__r.Sub_Stockist_Outlet_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Beat Sub Stockist Outlet Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Junction_Beat__c/fields/Beat_Substockiest__c.field-meta.xml
<CustomField>
    <fullName>Beat_Substockiest__c</fullName>
    <formula>CASESAFEID(Child_beat__r.Sub_Stockist__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Beat Substockiest</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Junction_Beat__c/fields/Beat_Type__c.field-meta.xml
<CustomField>
    <fullName>Beat_Type__c</fullName>
    <formula>TEXT(Child_beat__r.Beat_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Beat Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Junction_Beat__c/fields/Manager_Id__c.field-meta.xml
<CustomField>
    <fullName>Manager_Id__c</fullName>
    <formula>CASESAFEID( Child_beat__r.Owner:User.ManagerId )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Manager Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Junction_Beat__c/fields/Payroll_Employee__c.field-meta.xml
<CustomField>
    <fullName>Payroll_Employee__c</fullName>
    <formula>Child_beat__r.Payroll_Employee__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payroll Employee?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/Product_Mapping__c.object-meta.xml
<CustomObject>
    <label>Product Mapping</label>
    <nameField>
        <displayFormat>PM-{0000}</displayFormat>
        <label>Product Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Mapping__c/fields/Cloned_From_Employee_Replacement__c.field-meta.xml
<CustomField>
    <fullName>Cloned_From_Employee_Replacement__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cloned From Employee Replacement</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Product Mappings</relationshipLabel>
    <relationshipName>Product_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <formula>TEXT(Customer__r.Customer_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Product Mappings</relationshipLabel>
    <relationshipName>Product_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Exectuive__c.field-meta.xml
<CustomField>
    <fullName>Exectuive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Executive</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Product_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Primary_Customer__c.field-meta.xml
<CustomField>
    <fullName>Primary_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Product Mappings (Primary Customer)</relationshipLabel>
    <relationshipName>Product_Mappings1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Secondary_Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Customer_Type__c</fullName>
    <formula>TEXT(Customer__r.Secondary_Customer_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Secondary Customer Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Sub_Stockiest__c.field-meta.xml
<CustomField>
    <fullName>Sub_Stockiest__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sub Stockiest</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Product Mappings (Sub Stockiest)</relationshipLabel>
    <relationshipName>Product_Mappings2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BeatItemTriggerHandler.cls
public without sharing class BeatItemTriggerHandler 
{
    
    public static void handleSecValidations(List<Junction_Beat__c> beatItems){ 
        
        Set<Id> exeIds = new Set<Id>();
        Set<Id> primaryCustomerIds = new Set<Id>();
        Set<Id> subStockiestCustomerIds = new Set<Id>();
        
        for(Junction_Beat__c beat: beatItems){
            if( beat.Cloned_From_Employee_Replacement__c == false) exeIds.add(beat.Beat_OwnerId__c );
            if (beat.Beat_Primary_Customer__c != null &&  beat.Cloned_From_Employee_Replacement__c == false) primaryCustomerIds.add(beat.Beat_Primary_Customer__c);
            if (beat.Beat_Substockiest__c != null  &&  beat.Cloned_From_Employee_Replacement__c == false) subStockiestCustomerIds.add(beat.Beat_Substockiest__c);
            
        }
        
        if(!exeIds.isEmpty())
        {
            Map<Id, Set<Id>> userWithSubordinates = RoleHeirarchyUtility.getManagerWithSubordinates(exeIds);
            Set<Id> allRelatedUserIds = new Set<Id>();
            for (Id managerId : userWithSubordinates.keySet()) {
                allRelatedUserIds.add(managerId); // include manager themselves
                allRelatedUserIds.addAll(userWithSubordinates.get(managerId)); // include their subordinates
                //System.debug('Subordinates: ' + JSON.serialize(userWithSubordinates.get(managerId))); 
                
            }
            // Step 4: Fetch Primary Customer Mappings (using both Exectuive__c and Employee__c)
            Map<Id, Set<Id>> userToPrimaryCustomers = new Map<Id, Set<Id>>();
            List<Product_Mapping__c> primaryMappings = [ SELECT Id, Customer__c, Exectuive__c, Employee__c
                                                        FROM Product_Mapping__c WHERE Customer_Type__c = 'Primary Customer' 
                                                        AND (Exectuive__c IN :allRelatedUserIds) AND Customer__c IN: primaryCustomerIds
                                                        limit 50000
                                                       ];
            for (Product_Mapping__c pm : primaryMappings) {
                if (!userToPrimaryCustomers.containsKey(pm.Exectuive__c)) { userToPrimaryCustomers.put(pm.Exectuive__c, new Set<Id>()); }
                userToPrimaryCustomers.get(pm.Exectuive__c).add(pm.Customer__c);
            }
            
            system.debug('allRelatedUserIds:'+ allRelatedUserIds);
            system.debug('primaryCustomerIds:'+ primaryCustomerIds);
            list<Employee_Customer_Assignment__c> primayCustomerDsmAssignments = [
                Select Id,Name,Executive__c,Employee__c,Customer__c from Employee_Customer_Assignment__c
                where (Executive__c IN :allRelatedUserIds) AND Customer__c IN:primaryCustomerIds limit 50000
            ];
            for (Employee_Customer_Assignment__c epm : primayCustomerDsmAssignments) {
                if (!userToPrimaryCustomers.containsKey(epm.Executive__c)) { userToPrimaryCustomers.put(epm.Executive__c, new Set<Id>()); }
                userToPrimaryCustomers.get(epm.Executive__c).add(epm.Customer__c);
            }
            system.debug('primayCustomerDsmAssignments:'+ primayCustomerDsmAssignments);
            
            // Step 4.1: Fetch Sub Stockiest mappings similarly
            Map<Id, Set<Id>> userToSubStockistCustomers = new Map<Id, Set<Id>>();
            List<Product_Mapping__c> subStockiestMappings = [
                SELECT Id, Customer__c, Exectuive__c, Employee__c FROM Product_Mapping__c
                WHERE Secondary_Customer_Type__c = 'Sub Stockiest' AND (Exectuive__c IN :allRelatedUserIds) AND Customer__c IN:subStockiestCustomerIds  limit 50000
            ];
            for (Product_Mapping__c pm : subStockiestMappings) {
                if (!userToSubStockistCustomers.containsKey(pm.Exectuive__c)) { userToSubStockistCustomers.put(pm.Exectuive__c, new Set<Id>()); }
                userToSubStockistCustomers.get(pm.Exectuive__c).add(pm.Customer__c);
            }
            
            List<Product_Mapping__c> mapsToCreate = new List<Product_Mapping__c>();
            
            for(Junction_Beat__c beat: beatItems){
                Boolean found = false;
                if (beat.Beat_Primary_Customer__c != null) {
                    Set<Id> primaryCustomers = userToPrimaryCustomers.get(beat.Beat_OwnerId__c);
                    
                    system.debug(primaryCustomers);
                    
                    if (primaryCustomers == null || !primaryCustomers.contains(beat.Beat_Primary_Customer__c)) {
                        
                        
                        if(userWithSubordinates.containsKey(beat.Beat_OwnerId__c))
                        {
                            Set<Id> subordinateUserIds = userWithSubordinates.get(beat.Beat_OwnerId__c);
                            //System.debug('Subordinates11: ' + JSON.serialize(subordinateUserIds));
                            for (Id subUserId : subordinateUserIds) {
                                if (userToPrimaryCustomers.containsKey(subUserId) && userToPrimaryCustomers.get(subUserId).contains(beat.Beat_Primary_Customer__c)) {
                                    found = true;
                                    break;
                                }
                            }
                        }
                        if (!found) {
                            beat.addError('Primary Customer is not yet mapped to this Executive or their subordinates (Executive Code: ' + beat.Beat_Owner_Employee_Code__c + ', Primary Customer Code: ' + beat.Beat_Primary_Customer_Code__c + ').');
                            continue;
                        }
                        
                    }
                } 
                if (beat.Beat_Substockiest__c != null && found) {
                    Product_Mapping__c newMap = new Product_Mapping__c();
                    newMap.Customer__c = beat.Beat_Substockiest__c;
                    newMap.Primary_Customer__c = beat.Beat_Primary_Customer__c;
                    newMap.Exectuive__c = beat.Beat_OwnerId__c;
                    
                    mapsToCreate.add(newMap);
                    /* Set<Id> subStockiestCustomers = userToSubStockistCustomers.get(beat.Beat_OwnerId__c);
if (subStockiestCustomers == null || !subStockiestCustomers.contains(beat.Beat_Substockiest__c)) {
Set<Id> subordinateUserIds = userWithSubordinates.get(beat.Beat_OwnerId__c);
Boolean found = false;
if(userWithSubordinates.containsKey(beat.Beat_OwnerId__c))
{
for (Id subUserId : subordinateUserIds) {
if (userToSubStockistCustomers.containsKey(subUserId) && userToSubStockistCustomers.get(subUserId).contains(beat.Beat_Substockiest__c)) {
found = true;
break;
}
}
}

if (!found) {
beat.addError('Sub Stockiest is not yet mapped to this Executive (Executive Code: ' + beat.Beat_Owner_Employee_Code__c + ', Sub Stockiest Code: ' + beat.Beat_Sub_Stockist_Outlet_Code__c + ').');
continue;
}
}*/
                }
                
                if(beat.Account__c != null && !found){
                    Product_Mapping__c newMap = new Product_Mapping__c();
                    newMap.Customer__c = beat.Account__c;
                    newMap.Primary_Customer__c = beat.Beat_Primary_Customer__c;
                    newMap.Sub_Stockiest__c = beat.Beat_Substockiest__c;
                    newMap.Exectuive__c = beat.Beat_OwnerId__c;
                    mapsToCreate.add(newMap);
                }
                
            }
            
            
            if(!mapsToCreate.isEmpty()){
                try{
                    insert mapsToCreate;                
                }
                catch(Exception ex){
                    ExceptionHandler.addLog(ex, String.valueof(mapsToCreate), 'BeatItemTriggerHandler.handleSecValidations');
                }
            }
        }        
        
    }
    
    public static void handlePrimValidations(List<Junction_Beat__c> beatItems){
        
        Set<Id> exeIds = new Set<Id>();
        Set<Id> primaryCustomerIds = new Set<Id>();
        Set<Id> allRelatedUserIds = new Set<Id>();
        
        for(Junction_Beat__c beat: beatItems){
            if( beat.Cloned_From_Employee_Replacement__c == false) exeIds.add(beat.Beat_OwnerId__c);
            if(!beat.Payroll_Employee__c && beat.Cloned_From_Employee_Replacement__c == false)allRelatedUserIds.add(beat.Manager_Id__c);
            if (beat.Account__c != null && beat.Cloned_From_Employee_Replacement__c == false) primaryCustomerIds.add(beat.Account__c);
            
        }
        
        Map<Id, Set<Id>> userWithSubordinates = RoleHeirarchyUtility.getManagerWithSubordinates(exeIds);
        
        for (Id managerId : userWithSubordinates.keySet()) {
            allRelatedUserIds.add(managerId); // include manager themselves
            allRelatedUserIds.addAll(userWithSubordinates.get(managerId)); // include their subordinates
            //System.debug('Subordinates: ' + JSON.serialize(userWithSubordinates.get(managerId))); 
            
        }
        // Step 4: Fetch Primary Customer Mappings (using both Exectuive__c and Employee__c)
        Map<Id, Set<Id>> userToPrimaryCustomers = new Map<Id, Set<Id>>();
        List<Product_Mapping__c> primaryMappings = [ SELECT Id, Customer__c, Exectuive__c, Employee__c
                                                    FROM Product_Mapping__c WHERE Customer_Type__c = 'Primary Customer' 
                                                    AND (Exectuive__c IN :allRelatedUserIds) AND Customer__c IN: primaryCustomerIds
                                                    limit 50000
                                                   ];
        for (Product_Mapping__c pm : primaryMappings) {
            if (!userToPrimaryCustomers.containsKey(pm.Exectuive__c)) { userToPrimaryCustomers.put(pm.Exectuive__c, new Set<Id>()); }
            userToPrimaryCustomers.get(pm.Exectuive__c).add(pm.Customer__c);
        }
        
        list<Employee_Customer_Assignment__c> primayCustomerDsmAssignments = [
            Select Id,Name,Executive__c,Employee__c,Customer__c from Employee_Customer_Assignment__c
            where (Executive__c IN :allRelatedUserIds) AND Customer__c IN:primaryCustomerIds limit 50000
        ];
        for (Employee_Customer_Assignment__c epm : primayCustomerDsmAssignments) {
            if (!userToPrimaryCustomers.containsKey(epm.Executive__c)) { userToPrimaryCustomers.put(epm.Executive__c, new Set<Id>()); }
            userToPrimaryCustomers.get(epm.Executive__c).add(epm.Customer__c);
        }
        
         List<Employee_Customer_Assignment__c> DSMmapsToCreate = new List<Employee_Customer_Assignment__c>();
       
        for(Junction_Beat__c beat: beatItems){
            if (beat.Account__c != null) {
                Set<Id> primaryCustomers = userToPrimaryCustomers.get(beat.Beat_OwnerId__c);
                
                if (primaryCustomers == null || !primaryCustomers.contains(beat.Account__c)) {
                    
                    Boolean found = false;
                    if(userWithSubordinates.containsKey(beat.Beat_OwnerId__c))
                    {
                        Set<Id> subordinateUserIds = userWithSubordinates.get(beat.Beat_OwnerId__c);
                        //System.debug('Subordinates11: ' + JSON.serialize(subordinateUserIds));
                        for (Id subUserId : subordinateUserIds) {
                            if (userToPrimaryCustomers.containsKey(subUserId) && userToPrimaryCustomers.get(subUserId).contains(beat.Account__c)) {
                                found = true;
                                break;
                            }
                        }
                    }
                    if (!found) {
                        if(!beat.Payroll_Employee__c && userToPrimaryCustomers.containsKey(beat.Manager_Id__c)){
                            Employee_Customer_Assignment__c dsmnewMap = new Employee_Customer_Assignment__c();
                            dsmnewMap.Customer__c = beat.Beat_Primary_Customer__c;
                            dsmnewMap.Executive__c = beat.Beat_OwnerId__c;
                            
                            DSMmapsToCreate.add(dsmnewMap);
                            found = true;
                        }
                        else{
                            beat.addError('Primary Customer is not yet mapped to this Executive or their subordinates (Executive Code: ' + beat.Beat_Owner_Employee_Code__c + ', Primary Customer Code: ' + beat.Account_Customer_Code__c + ').');
                            continue;
                        }
                        
                    }
                    
                }
            } 
            
            
            
        }
        
          
        if(!DSMmapsToCreate.isEmpty()){
            try{
				insert DSMmapsToCreate;                
            }
            catch(Exception ex){
                ExceptionHandler.addLog(ex, String.valueof(DSMmapsToCreate), 'BeatTriggerHandler.handleValidations');
            }
        }
        
    }
    
    /* //To Create New Secondary Mapping Based on Beat
    public static void AfterInsert(list<Junction_Beat__c> newBeatItems)
    {
        set<Id> primaryCustomerIds = new set<Id>();
        set<Id> subStockiestIds = new set<Id>();
        for(Junction_Beat__c bt : newBeatItems)
        {
            if(bt.Beat_Type__c == 'Secondary')
            {
                primaryCustomerIds.add(bt.Beat_Primary_Customer__c);
                subStockiestIds.add(bt.Beat_Substockiest__c);
            }
        }
        
        //Outlet to primary customer mappings
        list<Product_Mapping__c> secondaryPrimaryMappings = [select Id,Name,Customer__c,Primary_Customer__c,Exectuive__c from Product_Mapping__c where
                                                      Primary_Customer__c IN:primaryCustomerIds ];
        
        //outlet to substockiest mappings
        list<Product_Mapping__c> secondarySubstockiestMappings = [select Id,Name,Customer__c,Primary_Customer__c,Exectuive__c,Sub_Stockiest__c from
                                                                  Product_Mapping__c where Sub_Stockiest__c IN:subStockiestIds ];
        
        
    }
     */
    

}