force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Is_SSA_DSM__c.field-meta.xml
<CustomField>
    <fullName>Is_SSA_DSM__c</fullName>
    <formula>TEXT(Profile__c) == &apos;DSM&apos; || TEXT(Profile__c) == &apos;SSA&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is_SSA/DSM</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Payroll__c.field-meta.xml
<CustomField>
    <fullName>Payroll__c</fullName>
    <label>Payroll</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payroll</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee_Customer_Assignment__c/Employee_Customer_Assignment__c.object-meta.xml
<CustomObject>
    <label>Employee Customer Assignment</label>
    <nameField>
        <displayFormat>ECA-{0000}</displayFormat>
        <label>Customer Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Customer Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Customer_Assignment__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Employee Customer Assignments</relationshipLabel>
    <relationshipName>Employee_Customer_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee_Customer_Assignment__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Employee Customer Assignments</relationshipLabel>
    <relationshipName>Employee_Customer_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/Product_Mapping__c.object-meta.xml
<CustomObject>
    <label>Product Mapping</label>
    <nameField>
        <displayFormat>PM-{0000}</displayFormat>
        <label>Product Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Mapping__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Product Mappings</relationshipLabel>
    <relationshipName>Product_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <formula>TEXT(Customer__r.Customer_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Product Mappings</relationshipLabel>
    <relationshipName>Product_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EmployeeSubmitForApprovalController.cls
public class EmployeeSubmitForApprovalController {
    @AuraEnabled
    public static String getAssignments(Id recordId) {
        Employee__c emp = [
            SELECT Id, Name, User__c, Is_Active__c, Payroll__c, Is_SSA_DSM__c 
            FROM Employee__c 
            WHERE Id = :recordId 
            LIMIT 1
        ];
        
        Boolean isPrimaryCustomerAssigned = false;
        Boolean isSecondaryCustomerAssigned = false;
        
        // -------------------------
        // Primary Assignment Check
        // -------------------------
        if (emp.Is_SSA_DSM__c) {
            List<Employee_Customer_Assignment__c> primaryAssignments = [
                SELECT Id 
                FROM Employee_Customer_Assignment__c 
                WHERE Employee__c = :recordId 
            ];
            isPrimaryCustomerAssigned = !primaryAssignments.isEmpty();
        } else {
            List<Product_Mapping__c> primaryAssignments = [
                SELECT Id 
                FROM Product_Mapping__c 
                WHERE Employee__c =: recordId 
                AND Customer__r.Customer_Type__c = 'Primary Customer'
            ];
            isPrimaryCustomerAssigned = !primaryAssignments.isEmpty();
        }
        
        // ----------------------------
        // Secondary Assignment Check
        // ----------------------------
        List<Product_Mapping__c> secondaryAssignments = [
            SELECT Id FROM Product_Mapping__c 
            WHERE Employee__c = :recordId  AND Customer__r.Customer_Type__c = 'Secondary Customer'
        ];
        isSecondaryCustomerAssigned = !secondaryAssignments.isEmpty();
        
        // ----------------------------
        // Final Response
        // ----------------------------
        if (isPrimaryCustomerAssigned && isSecondaryCustomerAssigned) {
            return 'Success';
        } else if (!isPrimaryCustomerAssigned && !isSecondaryCustomerAssigned) {
            return 'primary and secondary customers';
        } else if (!isPrimaryCustomerAssigned) {
            return 'primary customers';
        } else {
            return 'secondary customers';
        }
    }
    
    
    @AuraEnabled
    public static void submitForApproval(Id recordId, string comments) 
    {
        try {
            if (String.isBlank(comments)) comments = 'Submitting for Approval';
        
            Approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();
            req.setComments(comments);
            req.setObjectId(recordId);
            Approval.ProcessResult result = Approval.process(req);
            
            if (result.isSuccess()) {
                System.debug('Record submitted successfully for approval.');
            } else {
                System.debug('Failed to submit record for approval. Error: ' + result.getErrors()[0].getMessage());
            }
        }
        catch (Exception e) {
            System.debug('Something Went wrong: ' + e.getMessage());
            // throw new AuraHandledException('Error: ' + e.getMessage());
        }
        
    }
    
}