force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/ASM_TSM__c.field-meta.xml
<CustomField>
    <fullName>ASM_TSM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee Approver L1</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>ASM</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>TSM</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Employees3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Employee_Approver_3_HR__c.field-meta.xml
<CustomField>
    <fullName>Employee_Approver_3_HR__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee Approver L3 (HR)</label>
    <referenceTo>User</referenceTo>
    <relationshipName>EmployeeswS13</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Expense_Approver_1__c.field-meta.xml
<CustomField>
    <fullName>Expense_Approver_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Expense Approver L1</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employees5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Expense_Approver_2_Finance_Department__c.field-meta.xml
<CustomField>
    <fullName>Expense_Approver_2_Finance_Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Expense Approver L2 (Finance)</label>
    <referenceTo>User</referenceTo>
    <relationshipName>EmployeeswSKR</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/PJP_Approver_1__c.field-meta.xml
<CustomField>
    <fullName>PJP_Approver_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PJP Approver L1</label>
    <referenceTo>User</referenceTo>
    <relationshipName>EmployeeswRzv</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/PJP_Approver_2__c.field-meta.xml
<CustomField>
    <fullName>PJP_Approver_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PJP Approver L2</label>
    <referenceTo>User</referenceTo>
    <relationshipName>EmployeeswS05</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Primary_Customer_Approver_1__c.field-meta.xml
<CustomField>
    <fullName>Primary_Customer_Approver_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Customer Approver L1</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employees8</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Primary_Customer_Approver_2__c.field-meta.xml
<CustomField>
    <fullName>Primary_Customer_Approver_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Customer Approver L2</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employees9</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Primary_Customer_Approver_3_CD__c.field-meta.xml
<CustomField>
    <fullName>Primary_Customer_Approver_3_CD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Customer Approver L3 (Credit)</label>
    <referenceTo>User</referenceTo>
    <relationshipName>EmployeeswS1N</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Reporting_Manager__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reporting Manager</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>User.Id</field>
            <operation>notEqual</operation>
            <valueField>$Source.User__c</valueField>
        </filterItems>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Employees1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/RSM__c.field-meta.xml
<CustomField>
    <fullName>RSM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee Approver L2</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>RSM</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Employees2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Secondary_Customer_Approver_1__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Customer_Approver_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Secondary Customer Approver L1</label>
    <referenceTo>User</referenceTo>
    <relationshipName>EmployeeswS1X</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Secondary_Customer_Approver_2__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Customer_Approver_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Secondary Customer Approver L2</label>
    <referenceTo>User</referenceTo>
    <relationshipName>EmployeeswS1h</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ApproverReplacementQueue.cls
public class ApproverReplacementQueue implements Queueable {

    private Map<String, String> oldEmployeeWithNewEmployeeMap;
    private Set<String> oldUserIds;

    // ✅ Constructor
    public ApproverReplacementQueue(Map<String, String> oldEmployeeWithNewEmployeeMap, Set<String> oldUserIds) {
        this.oldEmployeeWithNewEmployeeMap = oldEmployeeWithNewEmployeeMap;
        this.oldUserIds = oldUserIds;
    }

    public void execute(QueueableContext context) {
        List<Employee__c> employeesToUpdate = [
            SELECT Id,
                RSM__c, ASM_TSM__c, Employee_Approver_3_HR__c,
                Secondary_Customer_Approver_1__c, Secondary_Customer_Approver_2__c,
                Primary_Customer_Approver_1__c, Primary_Customer_Approver_2__c, Primary_Customer_Approver_3_CD__c,
                PJP_Approver_1__c, PJP_Approver_2__c,
                Expense_Approver_1__c, Expense_Approver_2_Finance_Department__c, Reporting_Manager__c
            FROM Employee__c
            WHERE RSM__c IN :oldUserIds
                OR ASM_TSM__c IN :oldUserIds
                OR Employee_Approver_3_HR__c IN :oldUserIds
                OR Secondary_Customer_Approver_1__c IN :oldUserIds
                OR Secondary_Customer_Approver_2__c IN :oldUserIds
                OR Primary_Customer_Approver_1__c IN :oldUserIds
                OR Primary_Customer_Approver_2__c IN :oldUserIds
                OR Primary_Customer_Approver_3_CD__c IN :oldUserIds
                OR PJP_Approver_1__c IN :oldUserIds
                OR PJP_Approver_2__c IN :oldUserIds
                OR Expense_Approver_1__c IN :oldUserIds
                OR Expense_Approver_2_Finance_Department__c IN :oldUserIds
                OR Reporting_Manager__c IN :oldUserIds
        ];

        List<Employee__c> updatedEmployees = new List<Employee__c>();

        for (Employee__c emp : employeesToUpdate) {
            Boolean isChanged = false;

            if (oldEmployeeWithNewEmployeeMap.containsKey(emp.RSM__c)) {
                emp.RSM__c = oldEmployeeWithNewEmployeeMap.get(emp.RSM__c);
                isChanged = true;
            }
            if (oldEmployeeWithNewEmployeeMap.containsKey(emp.ASM_TSM__c)) {
                emp.ASM_TSM__c = oldEmployeeWithNewEmployeeMap.get(emp.ASM_TSM__c);
                isChanged = true;
            }
            if (oldEmployeeWithNewEmployeeMap.containsKey(emp.Employee_Approver_3_HR__c)) {
                emp.Employee_Approver_3_HR__c = oldEmployeeWithNewEmployeeMap.get(emp.Employee_Approver_3_HR__c);
                isChanged = true;
            }
            if (oldEmployeeWithNewEmployeeMap.containsKey(emp.Secondary_Customer_Approver_1__c)) {
                emp.Secondary_Customer_Approver_1__c = oldEmployeeWithNewEmployeeMap.get(emp.Secondary_Customer_Approver_1__c);
                isChanged = true;
            }
            if (oldEmployeeWithNewEmployeeMap.containsKey(emp.Secondary_Customer_Approver_2__c)) {
                emp.Secondary_Customer_Approver_2__c = oldEmployeeWithNewEmployeeMap.get(emp.Secondary_Customer_Approver_2__c);
                isChanged = true;
            }
            if (oldEmployeeWithNewEmployeeMap.containsKey(emp.Primary_Customer_Approver_1__c)) {
                emp.Primary_Customer_Approver_1__c = oldEmployeeWithNewEmployeeMap.get(emp.Primary_Customer_Approver_1__c);
                isChanged = true;
            }
            if (oldEmployeeWithNewEmployeeMap.containsKey(emp.Primary_Customer_Approver_2__c)) {
                emp.Primary_Customer_Approver_2__c = oldEmployeeWithNewEmployeeMap.get(emp.Primary_Customer_Approver_2__c);
                isChanged = true;
            }
            if (oldEmployeeWithNewEmployeeMap.containsKey(emp.Primary_Customer_Approver_3_CD__c)) {
                emp.Primary_Customer_Approver_3_CD__c = oldEmployeeWithNewEmployeeMap.get(emp.Primary_Customer_Approver_3_CD__c);
                isChanged = true;
            }
            if (oldEmployeeWithNewEmployeeMap.containsKey(emp.PJP_Approver_1__c)) {
                emp.PJP_Approver_1__c = oldEmployeeWithNewEmployeeMap.get(emp.PJP_Approver_1__c);
                isChanged = true;
            }
            if (oldEmployeeWithNewEmployeeMap.containsKey(emp.PJP_Approver_2__c)) {
                emp.PJP_Approver_2__c = oldEmployeeWithNewEmployeeMap.get(emp.PJP_Approver_2__c);
                isChanged = true;
            }
            if (oldEmployeeWithNewEmployeeMap.containsKey(emp.Expense_Approver_1__c)) {
                emp.Expense_Approver_1__c = oldEmployeeWithNewEmployeeMap.get(emp.Expense_Approver_1__c);
                isChanged = true;
            }
            if (oldEmployeeWithNewEmployeeMap.containsKey(emp.Expense_Approver_2_Finance_Department__c)) {
                emp.Expense_Approver_2_Finance_Department__c = oldEmployeeWithNewEmployeeMap.get(emp.Expense_Approver_2_Finance_Department__c);
                isChanged = true;
            }
            if (oldEmployeeWithNewEmployeeMap.containsKey(emp.Reporting_Manager__c)) {
                emp.Reporting_Manager__c = oldEmployeeWithNewEmployeeMap.get(emp.Reporting_Manager__c);
                isChanged = true;
            }

            if (isChanged) {
                updatedEmployees.add(emp);
            }
        }

        if (!updatedEmployees.isEmpty()) {
            Database.update(updatedEmployees, false);
        }
    }
}