force-app/main/default/objects/Junction_Beat__c/Junction_Beat__c.object-meta.xml
<CustomObject>
    <label>Beat Item</label>
    <nameField>
        <displayFormat>ITEM - {0000}</displayFormat>
        <label>Beat Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Beat Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Junction_Beat__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Junction_Beats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Junction_Beat__c/fields/Beat_Id__c.field-meta.xml
<CustomField>
    <fullName>Beat_Id__c</fullName>
    <formula>CASESAFEID(Child_beat__r.Beat_Id_Text__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Beat Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Junction_Beat__c/fields/Primary_Customer_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Primary_Customer_Record_Id__c</fullName>
    <formula>CASESAFEID(Child_beat__r.Primary_Customer__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary Customer Record Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/Product_Mapping__c.object-meta.xml
<CustomObject>
    <label>Product Mapping</label>
    <nameField>
        <displayFormat>PM-{0000}</displayFormat>
        <label>Product Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Mapping__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Product Mappings</relationshipLabel>
    <relationshipName>Product_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <formula>TEXT(Customer__r.Customer_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Exectuive__c.field-meta.xml
<CustomField>
    <fullName>Exectuive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Executive</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Product_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Executive_Employee_Code__c.field-meta.xml
<CustomField>
    <fullName>Executive_Employee_Code__c</fullName>
    <formula>IF(
  NOT(ISBLANK(Exectuive__c)),
  Exectuive__r.Employee_Code__c,
  Employee__r.Employee_Code__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Executive Employee Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Primary_Customer__c.field-meta.xml
<CustomField>
    <fullName>Primary_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Product Mappings (Primary Customer)</relationshipLabel>
    <relationshipName>Product_Mappings1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Secondary_Customer_Customer_Code__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Customer_Customer_Code__c</fullName>
    <formula>Customer__r.Customer_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Secondary Customer Customer Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Secondary_Customer_Outlet_Id__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Customer_Outlet_Id__c</fullName>
    <formula>Customer__r.Outlet_Id__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Secondary Customer Outlet Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Secondary_Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Customer_Type__c</fullName>
    <formula>TEXT(Customer__r.Secondary_Customer_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Secondary Customer Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Sub_Stockiest__c.field-meta.xml
<CustomField>
    <fullName>Sub_Stockiest__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sub Stockiest</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Product Mappings (Sub Stockiest)</relationshipLabel>
    <relationshipName>Product_Mappings2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SecondaryCustomerController.cls
public with sharing class SecondaryCustomerController {

    @AuraEnabled(cacheable=true)
    public static ReturnData getProductMappings(Id recordId) {
        ReturnData rt = new ReturnData();
        String fileName = '';
        
        List<Account> lstAccount = [
            SELECT Id, Name, Customer_Type__c, SAP_Customer_Code__c, Customer_Code__c, Outlet_Id__c 
            FROM Account 
            WHERE Id = :recordId 
        ];
        
        List<Junction_Beat__c> beatItems = [  SELECT Id, Account__c, Beat_Id__c  FROM Junction_Beat__c WHERE Primary_Customer_Record_Id__c = :recordId];
        
        Map<Id, Set<String>> outletToBeatIds = new Map<Id, Set<String>>();
        
        for (Junction_Beat__c bt : beatItems) {
            if (!outletToBeatIds.containsKey(bt.Account__c)) {
                outletToBeatIds.put(bt.Account__c, new Set<String>());
            }
            outletToBeatIds.get(bt.Account__c).add(bt.Beat_Id__c);
        }
        

        List<Product_Mapping__c> mappings = new List<Product_Mapping__c>();

        if (!lstAccount.isEmpty()) {
            Account acc = lstAccount[0];

            if (acc.Customer_Type__c == 'Primary Customer') {
                fileName = acc.Name + (String.isNotBlank(acc.SAP_Customer_Code__c) ? ('_' + acc.SAP_Customer_Code__c) : '');

                mappings = [
                    SELECT Id, Customer__c, Secondary_Customer_Outlet_Id__c,Customer__r.State__c,Customer__r.District__c,Customer__r.Primary_Phone_Number__c,
                    Secondary_Customer_Customer_Code__c, Customer__r.Name,Executive_Employee_Code__c,Exectuive__r.Name,
                    Customer__r.Secondary_Customer_Type__c,
                    Primary_Customer__r.SAP_Customer_Code__c,Sub_Stockiest__r.Outlet_Id__c,
                    Primary_Customer__r.Name,Sub_Stockiest__r.Name
                    FROM Product_Mapping__c
                    WHERE Primary_Customer__c = :recordId
                    WITH SECURITY_ENFORCED
                ];
            } else {
                fileName = acc.Name
                    + (String.isNotBlank(acc.Customer_Code__c) ? ('_' + acc.Customer_Code__c) : '')
                    + (String.isNotBlank(acc.Outlet_Id__c) ? ('_' + acc.Outlet_Id__c) : '');

                mappings = [
                    SELECT Id, Customer__c, Secondary_Customer_Outlet_Id__c,Customer__r.State__c,Customer__r.District__c,Customer__r.Primary_Phone_Number__c,
                    Secondary_Customer_Customer_Code__c, Customer__r.Name,Executive_Employee_Code__c,Exectuive__r.Name,
                    Primary_Customer__r.SAP_Customer_Code__c,Sub_Stockiest__r.Outlet_Id__c,  Customer__r.Secondary_Customer_Type__c,
                    Primary_Customer__r.Name,Sub_Stockiest__r.Name
                    FROM Product_Mapping__c
                    WHERE Sub_Stockiest__c = :recordId
                    WITH SECURITY_ENFORCED
                ];
            }
        }

        rt.fileName = fileName;

        Set<String> seenCustomerIds = new Set<String>();
        List<Data> uniqueSecondaryCustomers = new List<Data>();
        Set<Id> uniqueCustomers = new Set<Id>();
        Set<Id> subStockiestCustomers = new Set<Id>();
        decimal secondaryCustomerCount = 0;
        decimal subStockiestCount = 0;
        decimal totalCustomersCount = 0;
        
        for (Product_Mapping__c pm : mappings) {
            if (String.isNotBlank(pm.Customer__c) && String.isNotBlank(pm.Exectuive__c)) {
                uniqueCustomers.add(pm.Customer__c);
                
                if (pm.Customer__r.Secondary_Customer_Type__c == 'Sub Stockiest') {
                    subStockiestCustomers.add(pm.Customer__c);
                }
                
                Data d = new Data();
                d.recordId = pm.Id;
                d.secondaryCustomerName = pm.Customer__r != null ? pm.Customer__r.Name : '';
                d.secondaryCustomerId = pm.Customer__c;
                d.secondaryCustomerOutletId = pm.Secondary_Customer_Outlet_Id__c;
                d.secondaryCustomerCode = pm.Secondary_Customer_Customer_Code__c;
                d.primaryPhoneNumber = pm.Customer__r != null  ? pm.Customer__r.Primary_Phone_Number__c : '';
                d.state = pm.Customer__r != null  ? pm.Customer__r.State__c : '';
                d.disrict =  pm.Customer__r != null  ?   pm.Customer__r.District__c :'';
                d.executiveName = pm.Exectuive__r != null ? pm.Exectuive__r.Name : '';
                d.executiveCode = pm.Executive_Employee_Code__c;
                d.primaryCustomer = pm.Primary_Customer__r != null  ? pm.Primary_Customer__r.SAP_Customer_Code__c : '';
                d.subStockiest = pm.Sub_Stockiest__r != null ? pm.Sub_Stockiest__r.Outlet_Id__c : ''; 
                d.primaryCustomerName = pm.Primary_Customer__r != null  ? pm.Primary_Customer__r.Name : '';
                d.subStockiestName = pm.Sub_Stockiest__r != null ? pm.Sub_Stockiest__r.Name : ''; 
                // Set BeatId using outletToBeatIds
                if (outletToBeatIds.containsKey(pm.Customer__c)) {
                    d.beatId = String.join(new List<String>(outletToBeatIds.get(pm.Customer__c)), ';');
                } else {
                    d.beatId = '';
                }
                uniqueSecondaryCustomers.add(d);
            }
        }
        // final counts
        subStockiestCount = subStockiestCustomers.size();
        secondaryCustomerCount = uniqueCustomers.size() - subStockiestCount;
        totalCustomersCount = uniqueCustomers.size();
        rt.customerData = uniqueSecondaryCustomers;
        rt.subStockiestCount = subStockiestCount;
        rt.secondaryCustomerCount = secondaryCustomerCount;
        rt.totalCustomersCount = totalCustomersCount;
        return rt;
    }

    public class ReturnData {
        @AuraEnabled public String fileName;
        @AuraEnabled public List<Data> customerData;
        @AuraEnabled public Decimal secondaryCustomerCount;
        @AuraEnabled public Decimal subStockiestCount;
        @AuraEnabled public Decimal totalCustomersCount;
    }

    public class Data {
        @AuraEnabled public String recordId;
        @AuraEnabled public String secondaryCustomerName;
        @AuraEnabled public String secondaryCustomerId;
        @AuraEnabled public String secondaryCustomerOutletId;
        @AuraEnabled public String secondaryCustomerCode;
        @AuraEnabled public String primaryPhoneNumber;
        @AuraEnabled public String primaryCustomer;
        @AuraEnabled public String subStockiest;
        @AuraEnabled public String primaryCustomerName;
        @AuraEnabled public String subStockiestName;
        @AuraEnabled public String state;
        @AuraEnabled public String disrict;
        @AuraEnabled public String executiveName;
        @AuraEnabled public String executiveCode;
        @AuraEnabled public String beatId;
        
        
        
    }
}