force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit - {00000000}</displayFormat>
        <label>Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/ClockIn_Latitude__c.field-meta.xml
<CustomField>
    <fullName>ClockIn_Latitude__c</fullName>
    <label>ClockIn Latitude</label>
    <precision>8</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Clockin_Longitude__c.field-meta.xml
<CustomField>
    <fullName>Clockin_Longitude__c</fullName>
    <label>Clockin Longitude</label>
    <precision>8</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Visit_Date__c.field-meta.xml
<CustomField>
    <fullName>Visit_Date__c</fullName>
    <formula>DATEVALUE( Planned_Start_Time__c + (0.5/24))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Visit Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/mapController.cls
public class mapController {
      @AuraEnabled(cacheable=true)
public static List<Visit__c> getVisits(Id ids, Date fromDate, Date toDate) {
    if (ids == null || fromDate == null || toDate == null) {
        return new List<Visit__c>();
    }
    System.debug('employeeId ===== ' + ids);
    System.debug('fromDate ===== ' + fromDate);
    System.debug('toDate ===== ' + toDate);

   
  Datetime fromDateTime = Datetime.newInstance(fromDate, Time.newInstance(0, 0, 0, 0));
Datetime toDateTime   = Datetime.newInstance(toDate, Time.newInstance(23, 59, 59, 999));

List<Visit__c> visits = [
    SELECT Id, Name, Visit_for__c, ClockIn_Latitude__c, ClockIn_Longitude__c,
           OwnerId, Visit_Date__c, CreatedDate
    FROM Visit__c
    WHERE OwnerId = :ids
    AND CreatedDate >= :fromDateTime
    AND CreatedDate <= :toDateTime
    AND ClockIn_Latitude__c != null
    AND ClockIn_Longitude__c != null
];
    System.debug('Fetched Visits ===== ' + visits);
    System.debug('Fetched Visits Count ===== ' + visits.size());

    return visits;
}


}