force-app/main/default/objects/Price_Book__c/Price_Book__c.object-meta.xml
<CustomObject>
    <label>Price Book</label>
    <nameField>
        <displayFormat>PB - {00000}</displayFormat>
        <label>Price Book Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Price_Book__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Price Books</relationshipLabel>
    <relationshipName>Price_Books1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Price_Book__c/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary Customer</fullName>
            </value>
            <value>
                <fullName>Secondary Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Price_Book__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Price Books</relationshipLabel>
    <relationshipName>Price_Books</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Price_Book__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Regions</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Price_Book__c/fields/Secondary_Customer_Category__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Customer_Category__c</fullName>
    <label>Secondary Customer Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TN_Elite Club</fullName>
            </value>
            <value>
                <fullName>TN_GT</fullName>
            </value>
            <value>
                <fullName>KN_BMA</fullName>
            </value>
            <value>
                <fullName>KN_GT</fullName>
            </value>
            <value>
                <fullName>KN_Wholesale</fullName>
            </value>
            <value>
                <fullName>West_SMT</fullName>
            </value>
            <value>
                <fullName>West_GT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Price_Book__c/fields/UOM__c.field-meta.xml
<CustomField>
    <fullName>UOM__c</fullName>
    <label>UOM</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nos</fullName>
            </value>
            <value>
                <fullName>KGS</fullName>
            </value>
            <value>
                <fullName>LTR</fullName>
            </value>
            <value>
                <fullName>KG</fullName>
            </value>
            <value>
                <fullName>MTR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/UOM__c.field-meta.xml
<CustomField>
    <fullName>UOM__c</fullName>
    <label>UOM</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SKUUOM</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Region__c/Region__c.object-meta.xml
<CustomObject>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Return__c/Return__c.object-meta.xml
<CustomObject>
    <label>Return</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Return Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Returns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Return__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Returns</relationshipLabel>
    <relationshipName>Returns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Return_Item__c/Return_Item__c.object-meta.xml
<CustomObject>
    <label>Return Item</label>
    <nameField>
        <displayFormat>RItem-{0000}</displayFormat>
        <label>Return Items Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Return Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Return_Item__c/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary Customer</fullName>
            </value>
            <value>
                <fullName>Secondary Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Return_Item__c/fields/Reason_For_Return__c.field-meta.xml
<CustomField>
    <fullName>Reason_For_Return__c</fullName>
    <label>Reason For Return</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Reason_For_Return</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Return_Item__c/fields/Return__c.field-meta.xml
<CustomField>
    <fullName>Return__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Return</label>
    <referenceTo>Return__c</referenceTo>
    <relationshipLabel>Return Items</relationshipLabel>
    <relationshipName>Return_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Return_Item__c/fields/UOM__c.field-meta.xml
<CustomField>
    <fullName>UOM__c</fullName>
    <label>UOM</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SKUUOM</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/ReturnControllerLwc.cls
public class ReturnControllerLwc {
        
    @AuraEnabled
    public static Data getData(String accountId) 
    {
        system.debug('accountId'+accountId);
        data dt = new data();
        Account acc = [
            SELECT Id, Name, Region__c, Customer_Type__c, Secondary_Customer_Category__c 
            FROM Account 
            WHERE Id = :accountId
        ];
        list<Product__c> products = beatPlannerlwc.getProducts(accountId,acc.Customer_Type__c); 
        dt.productList = products;
            
       
        
        Map<String, Decimal> allProductwithPrice = new Map<String, Decimal>();
        
        for (Product__c p : products) {
            Price_Book__c bestPB;
            for (Price_Book__c pb : p.Price_Books__r) {
                Boolean matched = false;
                
                if (acc.Customer_Type__c == 'Primary Customer') {
                    if (pb.Customer__c == acc.Id) {
                        matched = true;
                    } 
                } else if (acc.Customer_Type__c == 'Secondary Customer') {
                    if (pb.Customer__c == acc.Id ||
                        pb.Secondary_Customer_Category__c == acc.Secondary_Customer_Category__c ||
                        pb.Region__c == acc.Region__c) {
                            matched = true;
                        }
                }
                
                if (matched) {
                    bestPB = pb;
                    break;
                }
            }
            
            Decimal finalPrice = 0;
            if (bestPB != null) {
                finalPrice = bestPB.Unit_Price__c;
            } else {
                finalPrice = p.MRP__c;
            }
            
            allProductwithPrice.put(p.Id, finalPrice);
        }
        
        dt.productIdWithMrp = allProductwithPrice;
        dt.resonForReturn = extractPicklistValues('Return_Item__c','Reason_For_Return__c');
        dt.uom = extractPicklistValues('Return_Item__c','UOM__c');
        
        return dt;
        
    }
    
    @AuraEnabled
    public static void saveReturn(Return__c returnData, List<Return_Item__c> returnItems) {
        insert returnData;
        for (Return_Item__c rtnItem : returnItems) {
            rtnItem.Return__c = returnData.Id;
        }
        insert returnItems;
    }

    
    private static List<Map<String, String>> extractPicklistValues(String objectName, String fieldName) {
        // Get the global describe map
        Map<String, Schema.SObjectType> schemaMap = Schema.getGlobalDescribe();
        
        // Check if the object exists
        if (!schemaMap.containsKey(objectName)) {
            return new List<Map<String, String>>();
        }
        
        Schema.DescribeSObjectResult objDescribe = schemaMap.get(objectName).getDescribe();
        Map<String, Schema.SObjectField> fieldMap = objDescribe.fields.getMap();
        
        // Check if the field exists in the object
        if (!fieldMap.containsKey(fieldName)) {
            return new List<Map<String, String>>();
        }
        
        Schema.DescribeFieldResult fieldResult = fieldMap.get(fieldName).getDescribe();
        List<Map<String, String>> picklistValues = new List<Map<String, String>>();
        
        if (fieldResult != null && fieldResult.getType() == Schema.DisplayType.Picklist) {
            for (Schema.PicklistEntry entry : fieldResult.getPicklistValues()) {
                picklistValues.add(new Map<String, String>{
                    'label' => entry.getLabel(),
                        'value' => entry.getValue()
                        });
            }
        }
        return picklistValues;
    }
    public class Data {
        @AuraEnabled public list<Product__c> productList = new list<Product__c>();
        @AuraEnabled public List<Map<String, String>> resonForReturn = new List<Map<String, String>> ();
        @AuraEnabled public List<Map<String, String>> uom = new List<Map<String, String>> ();
        @AuraEnabled public Map<String, Decimal> productIdWithMrp = new Map<String, Decimal>();
    }
    
}