force-app/main/default/objects/Price_Book__c/Price_Book__c.object-meta.xml
<CustomObject>
    <label>Price Book</label>
    <nameField>
        <displayFormat>PB - {00000}</displayFormat>
        <label>Price Book Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Price_Book__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Price Books</relationshipLabel>
    <relationshipName>Price_Books1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Price_Book__c/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary Customer</fullName>
            </value>
            <value>
                <fullName>Secondary Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Price_Book__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Price Books</relationshipLabel>
    <relationshipName>Price_Books</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Price_Book__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Regions</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Price_Book__c/fields/Secondary_Customer_Category__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Customer_Category__c</fullName>
    <label>Secondary Customer Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TN_Elite Club</fullName>
            </value>
            <value>
                <fullName>TN_GT</fullName>
            </value>
            <value>
                <fullName>KN_BMA</fullName>
            </value>
            <value>
                <fullName>KN_GT</fullName>
            </value>
            <value>
                <fullName>KN_Wholesale</fullName>
            </value>
            <value>
                <fullName>West_SMT</fullName>
            </value>
            <value>
                <fullName>West_GT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Price_Book__c/fields/UOM__c.field-meta.xml
<CustomField>
    <fullName>UOM__c</fullName>
    <label>UOM</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nos</fullName>
            </value>
            <value>
                <fullName>KGS</fullName>
            </value>
            <value>
                <fullName>LTR</fullName>
            </value>
            <value>
                <fullName>KG</fullName>
            </value>
            <value>
                <fullName>MTR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Sales Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Chanel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/List_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Price__c</fullName>
    <label>Product Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/SKU_Code__c.field-meta.xml
<CustomField>
    <fullName>SKU_Code__c</fullName>
    <externalId>true</externalId>
    <label>SKU Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product__c/fields/UOM__c.field-meta.xml
<CustomField>
    <fullName>UOM__c</fullName>
    <label>UOM</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SKUUOM</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/Product_Mapping__c.object-meta.xml
<CustomObject>
    <label>Product Mapping</label>
    <nameField>
        <displayFormat>PM-{0000}</displayFormat>
        <label>Product Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Mapping__c/fields/Chanel__c.field-meta.xml
<CustomField>
    <fullName>Chanel__c</fullName>
    <label>Sales Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Chanel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Product Mappings</relationshipLabel>
    <relationshipName>Product_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <formula>TEXT(Customer__r.Customer_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Exectuive__c.field-meta.xml
<CustomField>
    <fullName>Exectuive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Executive</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Product_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Region__c/Region__c.object-meta.xml
<CustomObject>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Return__c/Return__c.object-meta.xml
<CustomObject>
    <label>Return</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Return Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Returns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Return__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Returns</relationshipLabel>
    <relationshipName>Returns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Return_Item__c/Return_Item__c.object-meta.xml
<CustomObject>
    <label>Return Item</label>
    <nameField>
        <displayFormat>RItem-{0000}</displayFormat>
        <label>Return Items Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Return Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Return_Item__c/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary Customer</fullName>
            </value>
            <value>
                <fullName>Secondary Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Return_Item__c/fields/Reason_For_Return__c.field-meta.xml
<CustomField>
    <fullName>Reason_For_Return__c</fullName>
    <label>Reason For Return</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Reason_For_Return</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Return_Item__c/fields/Return__c.field-meta.xml
<CustomField>
    <fullName>Return__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Return</label>
    <referenceTo>Return__c</referenceTo>
    <relationshipLabel>Return Items</relationshipLabel>
    <relationshipName>Return_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Return_Item__c/fields/UOM__c.field-meta.xml
<CustomField>
    <fullName>UOM__c</fullName>
    <label>UOM</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SKUUOM</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/ReturnControllerLwcTest.cls
@isTest
public class ReturnControllerLwcTest {
    @testSetup
    static void setupTestData() {
        // Create Account
        Account acc = new Account(
            Name = 'Test Account',
            Pincode__c = '123456',
            Primary_Phone_Number__c = '9876543210',
            State__c = 'Karnataka',
            District__c = 'Kolar'
        );
        insert acc;

        // Create User
        User u = [SELECT Id FROM User WHERE profile.Name ='System Administrator'  LIMIT 1];

        // Create Product
        Product__c product = new Product__c(
            Name = 'Test Product',
            Channel__c = 'Institutional',
            List_Price__c = 200,
            MRP__c = 250,
            SKU_Code__c = '112SSAA',
            Tax_Percent__c = 5,
            UOM__c = 'Unit',
            Is_Active__c = true
        );
        insert product;

        // Create Product Mapping
        Product_Mapping__c pm = new Product_Mapping__c(
            Exectuive__c = u.Id,
            Customer__c = acc.Id,
            Chanel__c = product.Channel__c
        );
        insert pm;

        // Create Price Book Entry
        Price_Book__c pb = new Price_Book__c(
            Product__c = product.Id,
            Unit_Price__c = 180,
            MRP__c = 250,
            UOM__c = 'KGS',
            Customer__c = acc.Id,
            Region__c = acc.Region__c,
            Customer_Type__c = acc.Customer_Type__c,
            Secondary_Customer_Category__c = acc.Secondary_Customer_Category__c
        );
        insert pb;
    }

    @isTest
    static void testGetData() {
        // Get test Account
        Account acc = [SELECT Id FROM Account LIMIT 1];

        Test.startTest();
        ReturnControllerLwc.getData(acc.Id);
        Test.stopTest();

       
    }

    @isTest
    static void testSaveReturn() {
        // Create Return__c record
        Return__c ret = new Return__c(
           
           
        );

        // Create Return_Item__c list
        List<Return_Item__c> items = new List<Return_Item__c>();
        items.add(new Return_Item__c(
            Quantity__c = 2,
             UOM__c = 'Unit'
           // Reason_For_Return__c = 'Damaged'
        ));

        Test.startTest();
        ReturnControllerLwc.saveReturn(ret, items);
        Test.stopTest();

       
    }
   
}