force-app/main/default/objects/Price_Book__c/Price_Book__c.object-meta.xml
<CustomObject>
    <label>Price Book</label>
    <nameField>
        <displayFormat>PB - {00000}</displayFormat>
        <label>Price Book Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Price_Book__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Price Books</relationshipLabel>
    <relationshipName>Price_Books1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PriceBookSharingBatch.cls
public class PriceBookSharingBatch implements Database.Batchable<SObject> {

    public Database.QueryLocator start(Database.BatchableContext bc) {
        // Process all Price Books that have a Customer set
        return Database.getQueryLocator([
            SELECT Id, Customer__c
            FROM Price_Book__c
            WHERE Customer__c != null
        ]);
    }

    public void execute(Database.BatchableContext bc, List<Price_Book__c> scope) {
        PriceBookTriggerHandler.sharePriceBooksWithPartners(scope);
    }

    public void finish(Database.BatchableContext bc) {
        System.debug('PriceBookSharingBatch completed.');
    }
}