force-app/main/default/objects/Calendar_beat__c/Calendar_beat__c.object-meta.xml
<CustomObject>
    <label>PJP</label>
    <nameField>
        <displayFormat>PJP - {0000}</displayFormat>
        <label>PJP Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PJPs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Calendar_beat__c/fields/Next_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Start_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Calendar_beat__c/fields/Start_Month__c.field-meta.xml
<CustomField>
    <fullName>Start_Month__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Calendar_beat__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PJPs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DeactivatePJPScheduler.cls
global class DeactivatePJPScheduler  implements Database.Batchable<sObject>,Database.Stateful,Schedulable{
    
      public Database.QueryLocator start(Database.BatchableContext BC){
         String query = 'SELECT Id, Name, OwnerId,User__c,Start_Month__c,Next_Start_Date__c FROM Calendar_beat__c WHERE Active__c = true AND Next_Start_Date__c <= TODAY';
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext BC, List<Calendar_beat__c> scope){
        
        for(Calendar_Beat__c pjp: scope){
            pjp.Active__c = false;
        }
        
        try{
            Database.update(scope,false);
        }
        catch(Exception ex){
            system.debug(ex.getMessage());
        }

    }
    
    public void finish(Database.BatchableContext BC){
    }
    
    global void execute(SchedulableContext SC){
       
        
    } 
}