force-app/main/default/objects/Calendar_beat__c/Calendar_beat__c.object-meta.xml
<CustomObject>
    <label>PJP</label>
    <nameField>
        <displayFormat>PJP - {0000}</displayFormat>
        <label>PJP Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PJPs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Calendar_beat__c/fields/Start_Month__c.field-meta.xml
<CustomField>
    <fullName>Start_Month__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Calendar_beat__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PJPs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Child_beat__c/Child_beat__c.object-meta.xml
<CustomObject>
    <label>Beat</label>
    <nameField>
        <label>Beat Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Beats</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Child_beat__c/fields/Calendar_beat__c.field-meta.xml
<CustomField>
    <fullName>Calendar_beat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PJP</label>
    <referenceTo>Calendar_beat__c</referenceTo>
    <relationshipLabel>Beats</relationshipLabel>
    <relationshipName>Child_beats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Child_beat__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Beats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PJP_Item__c/PJP_Item__c.object-meta.xml
<CustomObject>
    <label>PJP Item</label>
    <nameField>
        <displayFormat>ITEM - {0000}</displayFormat>
        <label>PJP Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PJP Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PJP_Item__c/fields/Assigned_Beat__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Beat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Beat</label>
    <referenceTo>Child_beat__c</referenceTo>
    <relationshipLabel>PJP Items (Worked Beat)</relationshipLabel>
    <relationshipName>PJP_Items1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PJP_Item__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PJP_Item__c/fields/PJP__c.field-meta.xml
<CustomField>
    <fullName>PJP__c</fullName>
    <label>PJP</label>
    <referenceTo>Calendar_beat__c</referenceTo>
    <relationshipLabel>PJP Items</relationshipLabel>
    <relationshipName>PJP_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PJP_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Submitted</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountCalendarControllerTest.cls
@isTest
public class AccountCalendarControllerTest {
    
    @isTest
    static void testGetBeats() {
        // Create test data for Child_beat__c
        Child_beat__c testBeat = new Child_beat__c(Name = 'Test Beat');
        insert testBeat;

        // Call the getBeats method
       

       
    }

    @isTest
    static void testGetPjpItems() {
        // Create test data for PJP_Item__c
        User testUser = [SELECT Id FROM User WHERE profile.Name ='System Administrator'  LIMIT 1];
        Calendar_beat__c testPjp = new Calendar_beat__c(OwnerId = testUser .Id, Start_Month__c = Date.today());
        insert testPjp;

        PJP_Item__c testItem = new PJP_Item__c(
            PJP__c = testPjp.Id,
            Date__c = Date.today(),
            Status__c = 'Submitted'
        );
        insert testItem;

        // Call the getPjpItems method
        Test.startTest();
        AccountCalendarController.getPjpItems(testUser .Id, Date.today().month(), Date.today().year());
        Test.stopTest();

       
    }

    @isTest
    static void testSavePjpItems() {
        // Create test data for Calendar_beat__c
        User testUser  = [SELECT Id FROM User WHERE profile.Name ='System Administrator'  LIMIT 1];
        Calendar_beat__c testPjp = new Calendar_beat__c(OwnerId = testUser .Id, Start_Month__c = Date.today());
        insert testPjp;
        
        Calendar_beat__c beat = new Calendar_beat__c(
            User__c = testUser.Id,
            Active__c = false
        );
        insert beat;
        
        Child_beat__c  beat1 = new Child_beat__c(
            Active__c = false
        );
        insert beat1;
        
        PJP_Item__c item = new PJP_Item__c(
            PJP__c = beat.Id,
            Assigned_Beat__c = beat1.Id,
            Status__c = 'Submitted'
        );
        insert item;
        
        Account acc = new Account(
            Name = 'Primary Customer',
            Customer_Type__c = 'Primary Customer',
            Pincode__c = '123456',
            Primary_Phone_Number__c = '9876543210',
            State__c = 'Karnataka',
            District__c = 'Kolar'
        );
        insert acc;

        // Prepare PjpItemWrapper data
        List<AccountCalendarController.PjpItemWrapper> pjpItems = new List<AccountCalendarController.PjpItemWrapper>();
        AccountCalendarController.PjpItemWrapper wrapper = new AccountCalendarController.PjpItemWrapper();
        wrapper.dates = String.valueOf(Date.today());
        wrapper.id = item.Id;
        wrapper.accountId = acc.Id; // Replace with a valid Account Id
        pjpItems.add(wrapper);

        // Call the savePjpItems method
        Test.startTest();
        try{
        AccountCalendarController.savePjpItems(testUser.Id, Date.today().month(), Date.today().year(), pjpItems);
        }catch (DmlException e) {
            System.debug('Error while inserting account: ' + e.getMessage());
        }
        Test.stopTest();

       
    }
}