force-app/main/default/objects/Calendar_beat__c/Calendar_beat__c.object-meta.xml
<CustomObject>
    <label>PJP</label>
    <nameField>
        <displayFormat>PJP - {0000}</displayFormat>
        <label>PJP Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PJPs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Calendar_beat__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Submitted</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Calendar_beat__c/fields/Approver__c.field-meta.xml
<CustomField>
    <fullName>Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PJPs1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Calendar_beat__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PJPs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Employee_Approval_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Approver_ASM__c.field-meta.xml
<CustomField>
    <fullName>Approver_ASM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee Owner Approver 1</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employees6</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Approver_RSM__c.field-meta.xml
<CustomField>
    <fullName>Approver_RSM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee Owner Approver 2</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employees7</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/ASM_TSM__c.field-meta.xml
<CustomField>
    <fullName>ASM_TSM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee Approver L1</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>ASM</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>TSM</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Employees3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/District_In_charge__c.field-meta.xml
<CustomField>
    <fullName>District_In_charge__c</fullName>
    <defaultValue>false</defaultValue>
    <label>District In-charge</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Employee_Approver_3_HR__c.field-meta.xml
<CustomField>
    <fullName>Employee_Approver_3_HR__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee Approver L3 (HR)</label>
    <referenceTo>User</referenceTo>
    <relationshipName>EmployeeswS13</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Employee_Owner_Approver_3_HR__c.field-meta.xml
<CustomField>
    <fullName>Employee_Owner_Approver_3_HR__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee Owner Approver 3 (HR)</label>
    <referenceTo>User</referenceTo>
    <relationshipName>EmployeeswSMc</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Expense_Approver_1__c.field-meta.xml
<CustomField>
    <fullName>Expense_Approver_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Expense Approver L1</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employees5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Expense_Approver_2_Finance_Department__c.field-meta.xml
<CustomField>
    <fullName>Expense_Approver_2_Finance_Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Expense Approver L2 (Finance)</label>
    <referenceTo>User</referenceTo>
    <relationshipName>EmployeeswSKR</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Payroll__c.field-meta.xml
<CustomField>
    <fullName>Payroll__c</fullName>
    <label>Payroll</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payroll</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/fields/PJP_Approver_1__c.field-meta.xml
<CustomField>
    <fullName>PJP_Approver_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PJP Approver L1</label>
    <referenceTo>User</referenceTo>
    <relationshipName>EmployeeswRzv</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/PJP_Approver_2__c.field-meta.xml
<CustomField>
    <fullName>PJP_Approver_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PJP Approver L2</label>
    <referenceTo>User</referenceTo>
    <relationshipName>EmployeeswS05</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Primary_Customer_Approver_1__c.field-meta.xml
<CustomField>
    <fullName>Primary_Customer_Approver_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Customer Approver L1</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employees8</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Primary_Customer_Approver_2__c.field-meta.xml
<CustomField>
    <fullName>Primary_Customer_Approver_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Customer Approver L2</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employees9</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Primary_Customer_Approver_3_CD__c.field-meta.xml
<CustomField>
    <fullName>Primary_Customer_Approver_3_CD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Customer Approver L3 (Credit)</label>
    <referenceTo>User</referenceTo>
    <relationshipName>EmployeeswS1N</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/RSM__c.field-meta.xml
<CustomField>
    <fullName>RSM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee Approver L2</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>RSM</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Employees2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Secondary_Customer_Approver_1__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Customer_Approver_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Secondary Customer Approver L1</label>
    <referenceTo>User</referenceTo>
    <relationshipName>EmployeeswS1X</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Secondary_Customer_Approver_2__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Customer_Approver_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Secondary Customer Approver L2</label>
    <referenceTo>User</referenceTo>
    <relationshipName>EmployeeswS1h</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense</label>
    <nameField>
        <label>Expense Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/District_In_charge__c.field-meta.xml
<CustomField>
    <fullName>District_In_charge__c</fullName>
    <formula>Owner:User.District_In_charge__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>District In-charge</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Expenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Expense_Finance_Department_Approver__c.field-meta.xml
<CustomField>
    <fullName>Expense_Finance_Department_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Expense Finance Department Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Expenses4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SyncApprovers.cls
public class SyncApprovers {
    @AuraEnabled
    public static String syncApprovers(String empId) {
        // Fetch Employee
        List<Employee__c> employeeList = [
            SELECT Id, Name, User__c,RSM__c,ASM_TSM__c,Employee_Approver_3_HR__c,
            Secondary_Customer_Approver_1__c,Secondary_Customer_Approver_2__c,
            Primary_Customer_Approver_1__c,Primary_Customer_Approver_2__c,Primary_Customer_Approver_3_CD__c,
            PJP_Approver_1__c,Expense_Approver_1__c,Expense_Approver_2_Finance_Department__c
            FROM Employee__c 
            WHERE Id = :empId
        ];
        if (employeeList.isEmpty()) { return 'Error: EMPLOYEE_NOT_FOUND';}

        Employee__c emp = employeeList[0];
        if (emp.User__c == null) {return 'Error: USER_NOT_FOUND';}

        // Fetch User
        List<User> userList = [
            SELECT Id,RSM__c,ASM_TSM__c,Employee_Approver_3_HR__c,
            Primary_Customer_Approver_1__c, Primary_Customer_Approver_2__c, Primary_Customer_Approver_3_Credit_Dept__c,
            Secondary_Customer_Approver_1__c, Secondary_Customer_Approver_2__c,
            Expense_Approver_1__c,Expense_Approver_2_Finance_Dept__c, PJP_Approver_1__c
            FROM User WHERE Id = :emp.User__c
        ];
        if (userList.isEmpty()) {
            return 'Error: USER_RECORD_NOT_FOUND';
        }

        User usr = userList[0];

        // === Update Employee__c records ===
        List<Employee__c> employeesToUpdate = [
            SELECT Id, OwnerId, Approver_ASM__c, Approver_RSM__c, Employee_Owner_Approver_3_HR__c
            FROM Employee__c WHERE OwnerId = :usr.Id AND Payroll__c = 'No' AND Is_Active__c = false AND Approval_Status__c != 'HR Approved'
        ];

        for (Employee__c e : employeesToUpdate) {
            if(emp.ASM_TSM__c !=null) e.Approver_ASM__c = emp.ASM_TSM__c;
            if(emp.RSM__c !=null) e.Approver_RSM__c = emp.RSM__c;
            if(emp.Employee_Approver_3_HR__c !=null) e.Employee_Owner_Approver_3_HR__c = emp.Employee_Approver_3_HR__c;
        }
        if (!employeesToUpdate.isEmpty()) {
            database.update(employeesToUpdate,false);
        }

        // === Update Primary Customer Accounts ===
        List<Account> primaryAccountsToUpdate = [
            SELECT Id, CreatedById, ASM_TSM__c, RSM__c, Primary_Customer_Approver_L3_Credit__c FROM Account
            WHERE CreatedById = :usr.Id AND Customer_Type__c = 'Primary Customer' AND Approval_Status__c != 'Credit Dept. Approved' AND Customer_Status__c != 'Active'
        ];

        for (Account acc : primaryAccountsToUpdate) {
            if(emp.Primary_Customer_Approver_1__c !=null) acc.ASM_TSM__c = emp.Primary_Customer_Approver_1__c;
            if(emp.Primary_Customer_Approver_2__c !=null) acc.RSM__c = emp.Primary_Customer_Approver_2__c;
            if(emp.Primary_Customer_Approver_3_CD__c !=null) acc.Primary_Customer_Approver_L3_Credit__c = emp.Primary_Customer_Approver_3_CD__c;
        }
        if (!primaryAccountsToUpdate.isEmpty()) {
            database.update(primaryAccountsToUpdate,false);
        }

        // === Update Secondary Customer Accounts ===
        List<Account> secondaryAccountsToUpdate = [ SELECT Id, CreatedById, ASM_TSM__c, RSM__c FROM Account WHERE CreatedById = :usr.Id
            AND Customer_Type__c = 'Secondary Customer' AND Approval_Status__c != 'Level 2 Approved' AND Customer_Status__c != 'Active'
        ];

        for (Account acc : secondaryAccountsToUpdate) {
            if(emp.Secondary_Customer_Approver_1__c !=null) acc.ASM_TSM__c = emp.Secondary_Customer_Approver_1__c;
            if(emp.Secondary_Customer_Approver_2__c !=null) acc.RSM__c = emp.Secondary_Customer_Approver_2__c;
        }
        if (!secondaryAccountsToUpdate.isEmpty()) {
            database.update(secondaryAccountsToUpdate,false);
        }

        // === Update Expense__c records ===
        List<Expense__c> expensesToUpdate = [
            SELECT Id, OwnerId, Expense_Approver_L1__c, Expense_Finance_Department_Approver__c FROM Expense__c WHERE OwnerId = :usr.Id
        ];

        for (Expense__c exp : expensesToUpdate) {
            if(emp.Expense_Approver_1__c !=null) exp.Expense_Approver_L1__c = emp.Expense_Approver_1__c;
            if(emp.Expense_Approver_2_Finance_Department__c !=null) exp.Expense_Finance_Department_Approver__c = emp.Expense_Approver_2_Finance_Department__c;
        }
        if (!expensesToUpdate.isEmpty()) {
            database.update(expensesToUpdate,false);
        }

        // === Update PJP (Calendar_beat__c) records ===
        List<Calendar_beat__c> pjpToUpdate = [
            SELECT Id, OwnerId, Approver__c, User__c FROM Calendar_beat__c WHERE User__c = :usr.Id
        ];

        for (Calendar_beat__c pjp : pjpToUpdate) {
            if(emp.PJP_Approver_1__c !=null) pjp.Approver__c = emp.PJP_Approver_1__c;
        }
        if (!pjpToUpdate.isEmpty()) {
            database.update(pjpToUpdate,false);
        }
        updateUser(emp.Id, emp.User__c);


        return 'Success: Approvers synced successfully.';
    }
    
    @future
    public static void updateUser(Id empId, Id userId)
    {
        // Query the Employee record
        Employee__c emp = [
            SELECT RSM__c, ASM_TSM__c, Employee_Approver_3_HR__c,
            Secondary_Customer_Approver_1__c, Secondary_Customer_Approver_2__c,
            Primary_Customer_Approver_1__c, Primary_Customer_Approver_2__c, Primary_Customer_Approver_3_CD__c,
            PJP_Approver_1__c, PJP_Approver_2__c,
            Expense_Approver_1__c, Expense_Approver_2_Finance_Department__c,
            District_In_charge__c
            FROM Employee__c
            WHERE Id = :empId
            LIMIT 1
        ];
        
        User usr = new User(
            Id = userId,
            RSM__c = emp.RSM__c,
            ASM_TSM__c = emp.ASM_TSM__c,
            Employee_Approver_3_HR__c = emp.Employee_Approver_3_HR__c,
            Secondary_Customer_Approver_1__c = emp.Secondary_Customer_Approver_1__c,
            Secondary_Customer_Approver_2__c = emp.Secondary_Customer_Approver_2__c,
            Primary_Customer_Approver_1__c = emp.Primary_Customer_Approver_1__c,
            Primary_Customer_Approver_2__c = emp.Primary_Customer_Approver_2__c,
            Primary_Customer_Approver_3_Credit_Dept__c = emp.Primary_Customer_Approver_3_CD__c,
            PJP_Approver_1__c = emp.PJP_Approver_1__c,
            PJP_Approver_2__c = emp.PJP_Approver_2__c,
            Expense_Approver_1__c = emp.Expense_Approver_1__c,
            Expense_Approver_2_Finance_Dept__c = emp.Expense_Approver_2_Finance_Department__c,
            District_In_charge__c = emp.District_In_charge__c
        );
        
        update usr;
    }
    
}