force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>RE - {00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/NET_WEIGHT__c.field-meta.xml
<CustomField>
    <fullName>NET_WEIGHT__c</fullName>
    <formula>Quantity__c *  Product__r.Net_Weight__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>NET WEIGHT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/SKU_Weight__c.field-meta.xml
<CustomField>
    <fullName>SKU_Weight__c</fullName>
    <label>SKU Weight</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/UpdateSKUWeightBatch.cls
global class UpdateSKUWeightBatch implements Database.Batchable<SObject> {
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            'SELECT Id, SKU_Weight__c, Product__r.Net_Weight__c ' +
            'FROM Order_Item__c ' +
            'WHERE SKU_Weight__c = null ' +
            'AND Product__r.Net_Weight__c != null Limit 500000'
        );
    }
    
    global void execute(Database.BatchableContext bc, List<Order_Item__c> scope) {
        List<Order_Item__c> toUpdate = new List<Order_Item__c>();
        
        for (Order_Item__c item : scope) {
            item.SKU_Weight__c = item.Product__r.Net_Weight__c;
            toUpdate.add(item);
        }
        
        if (!toUpdate.isEmpty()) {
            Database.update(toUpdate, false); // false = partial success, logs failures
        }
    }
    
    global void finish(Database.BatchableContext bc) {
        System.debug('UpdateSKUWeightBatch completed.');
    }
}