force-app/main/default/objects/Child_beat__c/Child_beat__c.object-meta.xml
<CustomObject>
    <label>Beat</label>
    <nameField>
        <label>Beat Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Beats</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Child_beat__c/fields/Beat_Type__c.field-meta.xml
<CustomField>
    <fullName>Beat_Type__c</fullName>
    <label>Beat Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Child_beat__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Beats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Daily_Log__c/Daily_Log__c.object-meta.xml
<CustomObject>
    <label>Daily Attendance</label>
    <nameField>
        <displayFormat>Log Id - {00000}</displayFormat>
        <label>Log Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Attendances</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Log__c/fields/Child_beat__c.field-meta.xml
<CustomField>
    <fullName>Child_beat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Child beat</label>
    <referenceTo>Child_beat__c</referenceTo>
    <relationshipName>Daily_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Daily_Log__c/fields/Day_started_time__c.field-meta.xml
<CustomField>
    <fullName>Day_started_time__c</fullName>
    <label>Day started time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Daily_Log__c/fields/Employee_Code__c.field-meta.xml
<CustomField>
    <fullName>Employee_Code__c</fullName>
    <formula>Owner:User.Employee_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Employee Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Log__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Companion name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Daily_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit - {00000000}</displayFormat>
        <label>Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Actual_End_Time__c.field-meta.xml
<CustomField>
    <fullName>Actual_End_Time__c</fullName>
    <label>Actual End Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Actual_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Actual_Start_Time__c</fullName>
    <label>Actual Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Child_beat__c.field-meta.xml
<CustomField>
    <fullName>Child_beat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Beat</label>
    <referenceTo>Child_beat__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/ClockIn_Latitude__c.field-meta.xml
<CustomField>
    <fullName>ClockIn_Latitude__c</fullName>
    <label>ClockIn Latitude</label>
    <precision>8</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Clockin_Longitude__c.field-meta.xml
<CustomField>
    <fullName>Clockin_Longitude__c</fullName>
    <label>Clockin Longitude</label>
    <precision>8</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/UpdateDailyLogBatchTest.cls
@isTest
public class UpdateDailyLogBatchTest {
     @isTest
    static void testAfterInsertVisits() {
        // Create a user
        Profile p = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];
        User u = new User(
            FirstName = 'Test',
            LastName = 'User',
            Email = 'visituser@test.com',
            Username = 'visituser' + System.currentTimeMillis() + '@test.com',
            Alias = 'vusr',
            Employee_Code__c  = 'sjkhjkj18118',
            ProfileId = p.Id,
            TimeZoneSidKey = 'Asia/Kolkata',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US'
        );
        insert u;
        
        // Create a Daily Log record
        Daily_Log__c log = new Daily_Log__c();
        log.Day_started_time__c = Date.today().addDays(-1);
        log.Clock_Out_Location__Longitude__s =37.7749;
        log.Clock_Out_Location__Latitude__s = 78.4194;
        insert log;
        
        // Create mock ContentDocument to simulate file upload
        ContentVersion cv = new ContentVersion(
            Title = 'VisitAttachment',
            PathOnClient = 'VisitAttachment.pdf',
            VersionData = Blob.valueOf('Test File Content'),
            Description = 'fileKey123'
        );
        insert cv;
        
        ContentVersion insertedVersion = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id = :cv.Id LIMIT 1];
        
        // Create a test Child_beat__c record
        Child_beat__c testBeat = new Child_beat__c(
            Name = 'Test Beat',
            Beat_Type__c = 'Primary',
            User__c = u.Id
        );
        insert testBeat;
        // Create Visit record with key fields
        Visit__c visit = new Visit__c(
            OwnerId = u.Id,
            UniqueFileId__c = 'fileKey123',
            Child_Beat__c = testBeat.Id,
            ClockIn_Latitude__c = 12.9716,
            Clockin_Longitude__c = 77.5946,
            Actual_Start_Time__c = System.now(),
            Distance__c = 10,
            Daily_log__c = log.Id
        );
        
        

        
        Test.startTest();
        insert visit;  // This should trigger the VisitTriggerHandler logic
        visit.ClockIn_Latitude__c = 37.7749;
        visit.Clockin_Longitude__c = 78.4194;
        visit.Actual_End_Time__c = DateTime.now();
        
        visit.Actual_Start_Time__c = DateTime.now();
        update visit; 
        
     
        
        UpdateDailyLogBatchForAccountCount bt = new UpdateDailyLogBatchForAccountCount();
        database.executeBatch(bt,200);
        Test.stopTest();
        
        // No assertions as requested
    }
    @isTest
    static void testAfterInsertVisits2() {
        // Create a user
        Profile p = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];
        User u = new User(
            FirstName = 'Test',
            LastName = 'User',
            Email = 'visituser@te112st.com',
            Username = 'visitu121ser' + System.currentTimeMillis() + '@test.com',
            Alias = 'vusr',
            Employee_Code__c  = 'sjkhjdd2kj18118',
            ProfileId = p.Id,
            TimeZoneSidKey = 'Asia/Kolkata',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US'
        );
        insert u;
        
        // Create a Daily Log record
        Daily_Log__c log = new Daily_Log__c();
        log.Clock_Out_Location__Longitude__s =37.7749;
        log.Clock_Out_Location__Latitude__s = 78.4194;
        insert log;
        
        // Create mock ContentDocument to simulate file upload
        ContentVersion cv = new ContentVersion(
            Title = 'VisitAttachment',
            PathOnClient = 'VisitAttachment.pdf',
            VersionData = Blob.valueOf('Test File Content'),
            Description = 'fileKey1123'
        );
        insert cv;
        
        ContentVersion insertedVersion = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id = :cv.Id LIMIT 1];
        
        // Create Visit record with key fields
        Visit__c visit = new Visit__c(
            OwnerId = u.Id,
            UniqueFileId__c = 'fileKey1123',
            Actual_Start_Time__c = System.now(),
            Distance__c = 10,
            Daily_log__c = log.Id
        );
        
          insert visit;
        
        Test.startTest();
        // This should trigger the VisitTriggerHandler logic
        try{
            delete visit;
        }
        catch(exception e)
        {
            
        }
        
        Test.stopTest();
        
        // No assertions as requested
    }

}