force-app/main/default/objects/Child_beat__c/Child_beat__c.object-meta.xml
<CustomObject>
    <label>Beat</label>
    <nameField>
        <label>Beat Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Beats</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Child_beat__c/fields/Sales_Channel__c.field-meta.xml
<CustomField>
    <fullName>Sales_Channel__c</fullName>
    <formula>IF(INCLUDES(Owner:User.Sales_Channel__c, &quot;TN&quot;), &quot;TN; &quot;, &quot;&quot;) &amp;
IF(INCLUDES(Owner:User.Sales_Channel__c, &quot;AP&quot;), &quot;AP; &quot;, &quot;&quot;) &amp;
IF(INCLUDES(Owner:User.Sales_Channel__c, &quot;TS&quot;), &quot;TS; &quot;, &quot;&quot;) &amp;
IF(INCLUDES(Owner:User.Sales_Channel__c, &quot;Cake&quot;), &quot;Cake; &quot;, &quot;&quot;) &amp;
IF(INCLUDES(Owner:User.Sales_Channel__c, &quot;Institutional&quot;), &quot;Institutional; &quot;, &quot;&quot;) &amp;
IF(INCLUDES(Owner:User.Sales_Channel__c, &quot;District Bulk&quot;), &quot;District Bulk; &quot;, &quot;&quot;) &amp;
IF(INCLUDES(Owner:User.Sales_Channel__c, &quot;Bread&quot;), &quot;Bread; &quot;, &quot;&quot;) &amp;
IF(INCLUDES(Owner:User.Sales_Channel__c, &quot;KA&quot;), &quot;KA; &quot;, &quot;&quot;) &amp;
IF(INCLUDES(Owner:User.Sales_Channel__c, &quot;Bulk Depot&quot;), &quot;Bulk Depot; &quot;, &quot;&quot;) &amp;
IF(INCLUDES(Owner:User.Sales_Channel__c, &quot;CPD&quot;), &quot;CPD; &quot;, &quot;&quot;) &amp;
IF(INCLUDES(Owner:User.Sales_Channel__c, &quot;Madurai&quot;), &quot;Madurai; &quot;, &quot;&quot;) &amp;
IF(INCLUDES(Owner:User.Sales_Channel__c, &quot;West&quot;), &quot;West; &quot;, &quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Channel</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Log__c/Daily_Log__c.object-meta.xml
<CustomObject>
    <label>Daily Attendance</label>
    <nameField>
        <displayFormat>Log Id - {00000}</displayFormat>
        <label>Log Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Attendances</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Log__c/fields/Assigned_Beat__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Beat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Beat</label>
    <referenceTo>Child_beat__c</referenceTo>
    <relationshipLabel>Daily Attendances (Assigned Beat)</relationshipLabel>
    <relationshipName>Daily_Attendances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Daily_Log__c/fields/Beat_Switch_History__c.field-meta.xml
<CustomField>
    <fullName>Beat_Switch_History__c</fullName>
    <label>Beat Switch History</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Daily_Log__c/fields/Calls_Made__c.field-meta.xml
<CustomField>
    <fullName>Calls_Made__c</fullName>
    <formula>IF( Total_No_of_Outlets__c == 0, 0,    Total_Calls__c /  Total_No_of_Outlets__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Calls Made %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Daily_Log__c/fields/Current_Beat__c.field-meta.xml
<CustomField>
    <fullName>Current_Beat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Worked Beat</label>
    <referenceTo>Child_beat__c</referenceTo>
    <relationshipLabel>Daily Attendances (Current Beat)</relationshipLabel>
    <relationshipName>Daily_Logs1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Daily_Log__c/fields/Distance_Travelled__c.field-meta.xml
<CustomField>
    <fullName>Distance_Travelled__c</fullName>
    <formula>KMs_Travelled__c  + Last_visit_distance__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Distance Travelled by System</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Daily_Log__c/fields/Distance_Travelled_by_Odometer__c.field-meta.xml
<CustomField>
    <fullName>Distance_Travelled_by_Odometer__c</fullName>
    <formula>IF(
  
   End_Day_Odometer_Reading_KM__c &gt; Start_Day_Odometer_Reading_KM__c
  ,
  End_Day_Odometer_Reading_KM__c - Start_Day_Odometer_Reading_KM__c,
  0
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Distance Travelled (by Odometer)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Daily_Log__c/fields/Distributor_Id__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Id__c</fullName>
    <formula>Current_Beat__r.Primary_Customer__r.SAP_Customer_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Distributor Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Log__c/fields/Distributor_Name__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Name__c</fullName>
    <formula>Current_Beat__r.Primary_Customer__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Distributor Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Log__c/fields/Effective_Man_Hours__c.field-meta.xml
<CustomField>
    <fullName>Effective_Man_Hours__c</fullName>
    <formula>IF(
AND(NOT(ISBLANK(Day_started_time__c)), NOT(ISBLANK( Last_Visit__r.Actual_Start_Time__c ))),
TEXT(
FLOOR((Last_Visit__r.Actual_Start_Time__c - Day_started_time__c) * 24)
) &amp; &quot; hrs &quot; &amp;
TEXT(
ROUND(MOD((Last_Visit__r.Actual_Start_Time__c - Day_started_time__c) * 1440, 60), 0)
) &amp; &quot; mins&quot;,
NULL
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Effective Man Hours</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Log__c/fields/Employee_Code__c.field-meta.xml
<CustomField>
    <fullName>Employee_Code__c</fullName>
    <formula>Owner:User.Employee_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Employee Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Log__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <formula>IF(
NOT(ISBLANK(Day_ended_time__c)),
TEXT(
IF(
MOD(
VALUE(MID(TEXT(Day_ended_time__c+ (5.5/24)), 12, 2)),
12
) = 0,
12,
MOD(
VALUE(MID(TEXT(Day_ended_time__c+ (5.5/24)), 12, 2)),
12
)
)
) &amp; &quot;:&quot; &amp;
MID(TEXT(Day_ended_time__c+ (5.5/24)), 15, 2) &amp; &quot; &quot; &amp;
IF(
VALUE(MID(TEXT(Day_ended_time__c+ (5.5/24)), 12, 2)) &gt;= 12,
&quot;PM&quot;,
&quot;AM&quot;
),
NULL
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>EOD Time</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Log__c/fields/First_Visit_Time__c.field-meta.xml
<CustomField>
    <fullName>First_Visit_Time__c</fullName>
    <formula>TIMEVALUE(First_Visit__r.Actual_Start_Time__c + (5.5/24))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>First Call Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Daily_Log__c/fields/Last_Visit_Time__c.field-meta.xml
<CustomField>
    <fullName>Last_Visit_Time__c</fullName>
    <formula>TIMEVALUE( Last_Visit__r.Actual_Start_Time__c + (5.5/24))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Last Call Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Daily_Log__c/fields/Lines_Per_OL__c.field-meta.xml
<CustomField>
    <fullName>Lines_Per_OL__c</fullName>
    <formula>IF(Total_Productive_Calls__c  == 0, 0, TLSD_Retailers_Outlets__c / Total_Productive_Calls__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lines_Per_OL</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Daily_Log__c/fields/Market_Hours__c.field-meta.xml
<CustomField>
    <fullName>Market_Hours__c</fullName>
    <formula>IF(
AND(NOT(ISBLANK( First_Visit__r.Actual_Start_Time__c )), NOT(ISBLANK( Last_Visit__r.Actual_Start_Time__c ))),
TEXT(
FLOOR(( Last_Visit__r.Actual_Start_Time__c- First_Visit__r.Actual_Start_Time__c ) * 24)
) &amp; &quot; hrs &quot; &amp;
TEXT(
ROUND(MOD(( Last_Visit__r.Actual_Start_Time__c- First_Visit__r.Actual_Start_Time__c ) * 1440, 60), 0)
) &amp; &quot; mins&quot;,
NULL
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Market Hours</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Log__c/fields/New_Calls__c.field-meta.xml
<CustomField>
    <fullName>New_Calls__c</fullName>
    <label>New Calls</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Daily_Log__c/fields/Normal_Call__c.field-meta.xml
<CustomField>
    <fullName>Normal_Call__c</fullName>
    <label>PJP Normal Call</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Daily_Log__c/fields/Primary_Order_Amount__c.field-meta.xml
<CustomField>
    <fullName>Primary_Order_Amount__c</fullName>
    <label>Primary Order Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Daily_Log__c/fields/Prouctive_Calls_Made__c.field-meta.xml
<CustomField>
    <fullName>Prouctive_Calls_Made__c</fullName>
    <formula>IF(Total_No_of_Outlets__c ==0 ,0,  Total_Productive_Calls_Made__c /  Total_No_of_Beat_Non_PJP_Order__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Productive Calls Made %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Daily_Log__c/fields/Secondary_Order_Amont__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Order_Amont__c</fullName>
    <label>Secondary Order Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Daily_Log__c/fields/Start_time__c.field-meta.xml
<CustomField>
    <fullName>Start_time__c</fullName>
    <formula>IF(
NOT(ISBLANK(Day_started_time__c)),
TEXT(
IF(
MOD(
VALUE(MID(TEXT(Day_started_time__c + (5.5/24)), 12, 2)),
12
) = 0,
12,
MOD(
VALUE(MID(TEXT(Day_started_time__c + (5.5/24)), 12, 2)),
12
)
)
) &amp; &quot;:&quot; &amp;
MID(TEXT(Day_started_time__c + (5.5/24)), 15, 2) &amp; &quot; &quot; &amp;
IF(
VALUE(MID(TEXT(Day_started_time__c + (5.5/24)), 12, 2)) &gt;= 12,
&quot;PM&quot;,
&quot;AM&quot;
),
NULL
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Log Start Time</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Log__c/fields/Telephonic_Call__c.field-meta.xml
<CustomField>
    <fullName>Telephonic_Call__c</fullName>
    <label>PJP Telephonic Call</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Daily_Log__c/fields/TLSD__c.field-meta.xml
<CustomField>
    <fullName>TLSD__c</fullName>
    <label>TLSD</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Daily_Log__c/fields/TLSD_Primary__c.field-meta.xml
<CustomField>
    <fullName>TLSD_Primary__c</fullName>
    <label>TLSD Primary</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Daily_Log__c/fields/TLSD_Retailers_Outlets__c.field-meta.xml
<CustomField>
    <fullName>TLSD_Retailers_Outlets__c</fullName>
    <label>TLSD Retailers Outlets</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Daily_Log__c/fields/TLSD_Sub_Stockist__c.field-meta.xml
<CustomField>
    <fullName>TLSD_Sub_Stockist__c</fullName>
    <label>TLSD_Sub_Stockist</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Daily_Log__c/fields/Total_Non_Productive_Calls__c.field-meta.xml
<CustomField>
    <fullName>Total_Non_Productive_Calls__c</fullName>
    <label>Non-Productive Calls Made</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Daily_Log__c/fields/Total_Order_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Order_Amount__c</fullName>
    <label>Total Order Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Daily_Log__c/fields/Total_Outlets__c.field-meta.xml
<CustomField>
    <fullName>Total_Outlets__c</fullName>
    <label>No Of Outlets from Beat</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Daily_Log__c/fields/Total_Productive_Calls__c.field-meta.xml
<CustomField>
    <fullName>Total_Productive_Calls__c</fullName>
    <label>PJP PC</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Daily_Log__c/fields/Total_Visits__c.field-meta.xml
<CustomField>
    <fullName>Total_Visits__c</fullName>
    <label>PJP TC</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Daily_Log__c/fields/TPut_Per_OL__c.field-meta.xml
<CustomField>
    <fullName>TPut_Per_OL__c</fullName>
    <formula>IF(Total_Productive_Calls__c == 0 ,0,  Total_Order_Amount__c / Total_Productive_Calls__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TPut_Per_OL</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/EODReport.cls
global class EODReport implements Database.Batchable<SObject>, Database.Stateful {
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        // Query only users who are managers (Role != null is a good filter)
        return Database.getQueryLocator([
            SELECT Id, Email, Name 
            FROM User 
            WHERE IsActive = true
            AND UserRoleId != null
        ]);
    }
    
    global void execute(Database.BatchableContext bc, List<User> scope) {
        User manager = scope[0];
        
        // Get subordinates under this manager
        Set<Id> subordinateIds = RoleHeirarchyUtility.getUsersUnderRoleHierarchy(manager.Id);
        
        if (subordinateIds.isEmpty()) {
            return; // no team → no report
        }
        
        List<User> subordinates = [
            SELECT Id, Name,Employee_Code__c, Email ,Username,Mail_Id__c,Phone,Sales_Channel__c,Title,Manager_Name__c,Manager_Employee_Code__c
            
            FROM User 
            WHERE Id IN :subordinateIds
        ];
        
        Map<Id, Daily_Log__c> logsByUser = new Map<Id, Daily_Log__c>(
            [SELECT Id, OwnerId,
             Start_time__c, First_Visit_Time__c, Last_Visit_Time__c, End_Time__c, Effective_Man_Hours__c, Market_Hours__c,
             Assigned_Beat__r.Name, Current_Beat__r.Name, Beat_Switch_History__c,
             Distributor_Name__c, Distributor_Id__c, Calls_Made__c, Total_Visits__c, Prouctive_Calls_Made__c, Total_Productive_Calls__c,
             Total_Non_Productive_Calls__c, New_Calls__c, Distance_Travelled_by_Odometer__c, Distance_Travelled__c, TLSD__c,
             Total_Outlets__c, Total_Order_Amount__c, Primary_Order_Amount__c, Secondary_Order_Amont__c, TLSD_Retailers_Outlets__c,
             TLSD_Sub_Stockist__c, TLSD_Primary__c, Lines_Per_OL__c, TPut_Per_OL__c, Normal_Call__c, Telephonic_Call__c
             FROM Daily_Log__c  
             WHERE OwnerId IN :subordinateIds 
             AND CreatedDate = TODAY]
        );
        
        
        // Build CSV header
        String csv = 'Date,User Name,Employee Code,Username,Mail Id,Phone,Sales Channel,Designation,Reporting Manager,Reporting Manager Code,' +
            'Day Start Time,First Visit Time,Last Visit Time,End Time,Effective Man Hours,Market Hours,Assigned Beat,Current Beat,Beat Switch History,' +
            'Distributor Name,Distributor Id,Calls Made %,Calls Made,Productive Calls Made %,Productive Calls Made,Non Productive Calls,New Calls,' +
            'Distance Travelled by Odometer,Distance Travelled,TLSD,Total Outlets,Total Order Amount,Primary Order Amount,Secondary Order Amount,' +
            'TLSD Retailers Outlets,TLSD Sub Stockist,TLSD Primary,Lines Per OL,TPut Per OL,Normal Call,Telephonic Call,Status\n';
        
        Date todayDate = Date.today();
        
        for (User sub : subordinates) {
            Daily_Log__c log = logsByUser.get(sub.Id);
            
            String status = (log != null) ? 'Present' : 'Absent';
            
            // Build row (user fields first)
            csv +=
                todayDate.format() + ',' +
                sub.Name + ',' +
                sub.Employee_Code__c + ',' +
                sub.Username + ',' +
                sub.Mail_Id__c + ',' +
                sub.Phone + ',' +
                sub.Sales_Channel__c + ',' +
                ( sub.Title  != null ?  sub.Title : '') + ',' +
                sub.Manager_Name__c + ',' +
                sub.Manager_Employee_Code__c + ',';
            
            if (log != null) {
                // You’ll need to calculate percentages if they’re not fields in Daily_Log__c
                Decimal callsMadePct = (log.Total_Visits__c != null && log.Total_Visits__c > 0) 
                    ? ((log.Calls_Made__c / log.Total_Visits__c) * 100) 
                    : null;
                Decimal productiveCallsPct = (log.Total_Productive_Calls__c != null && log.Calls_Made__c != null && log.Calls_Made__c > 0) 
                    ? ((log.Total_Productive_Calls__c / log.Calls_Made__c) * 100) 
                    : null;
                
                csv +=
                    log.Start_time__c + ',' +
                    log.First_Visit_Time__c + ',' +
                    log.Last_Visit_Time__c + ','+
                    (log.End_Time__c != null ? log.End_Time__c : '') + ','+
                    (log.Effective_Man_Hours__c != null ? log.Effective_Man_Hours__c : '') + ','+
                    (log.Market_Hours__c != null ? log.Market_Hours__c : '') + ','+
                    (log.Assigned_Beat__r != null ? log.Assigned_Beat__r.Name : '') + ',' +
                    (log.Current_Beat__r != null ? log.Current_Beat__r.Name : '') + ',' +
                    (log.Beat_Switch_History__c != null ? log.Beat_Switch_History__c : '') + ','+
                    (log.Distributor_Name__c != null ? log.Distributor_Name__c : '') + ','+
                    (log.Distributor_Id__c != null ? log.Distributor_Id__c : '') + ','+
                    (log.Calls_Made__c != null ?    log.Calls_Made__c + '%' : '') + ',' +   // Calls Made %
                    (log.Total_Visits__c != null ? log.Total_Visits__c : 0) + ','+
                    (log.Prouctive_Calls_Made__c != null ? log.Prouctive_Calls_Made__c + '%' : '') + ',' +  // Productive Calls Made %
                    (log.Total_Productive_Calls__c != null ? log.Total_Productive_Calls__c : 0) + ','+
                    (log.Total_Non_Productive_Calls__c != null ? log.Total_Non_Productive_Calls__c : 0) + ','+
                    (log.New_Calls__c != null ? log.New_Calls__c : 0) + ','+
                    (log.Distance_Travelled_by_Odometer__c != null ? log.Distance_Travelled_by_Odometer__c : 0) + ','+
                    (log.Distance_Travelled__c != null ? log.Distance_Travelled__c : 0) + ','+
                    (log.TLSD__c != null ? log.TLSD__c : 0) + ','+
                    (log.Total_Outlets__c != null ? log.Total_Outlets__c : 0) + ','+
                    (log.Total_Order_Amount__c != null ? log.Total_Order_Amount__c : 0) + ','+
                    (log.Primary_Order_Amount__c != null ? log.Primary_Order_Amount__c : 0) + ','+
                    (log.Secondary_Order_Amont__c != null ? log.Secondary_Order_Amont__c : 0) + ','+
                    (log.TLSD_Retailers_Outlets__c != null ? log.TLSD_Retailers_Outlets__c : 0) + ','+
                    (log.TLSD_Sub_Stockist__c != null ? log.TLSD_Sub_Stockist__c : 0) + ','+
                    (log.TLSD_Primary__c != null ? log.TLSD_Primary__c : 0) + ','+
                    (log.Lines_Per_OL__c != null ? log.Lines_Per_OL__c : 0) + ','+
                    (log.TPut_Per_OL__c != null ? log.TPut_Per_OL__c : 0) + ','+
                    (log.Normal_Call__c != null ? log.Normal_Call__c : 0) + ','+
                    (log.Telephonic_Call__c != null ? log.Telephonic_Call__c : 0) + ',';
            } else {
                // If no log → fill blanks for all log fields (34 fields here, keep commas consistent!)
                csv += ',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,';
            }
            
            csv += status + '\n'; // Final column
        }
        
        
        // Send only once per manager
        if (!String.isBlank(manager.Email)) {
            Messaging.EmailFileAttachment att = new Messaging.EmailFileAttachment();
            att.setFileName('Elite EOD Report ' + Date.today().format() + '.csv');
            att.setBody(Blob.valueOf(csv));
            
            Messaging.SingleEmailMessage msg = new Messaging.SingleEmailMessage();
            msg.setToAddresses(new String[] { manager.Email });
            msg.setSubject('Elite EOD Report - ' + Date.today().format());
            
            // Personalized body
            msg.setPlainTextBody('Dear ' + manager.Name + ',\n\n' + 
                                 'Please find your team\'s EOD report attached.\n\n' +
                                 'Regards,\nElite Team');
            
            msg.setFileAttachments(new Messaging.EmailFileAttachment[] { att });
            msg.setSaveAsActivity(false);
            
            Messaging.sendEmail(new List<Messaging.SingleEmailMessage>{ msg }, false);
        }

    }
    
    global void finish(Database.BatchableContext bc) {
        // nothing needed here
    }

}