force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV - {0000000}</displayFormat>
        <label>Invoice ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Customer_SAP_Code__c.field-meta.xml
<CustomField>
    <fullName>Customer_SAP_Code__c</fullName>
    <label>Customer SAP Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Delivery_Plant__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Plant__c</fullName>
    <label>Delivery Plant</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_No__c.field-meta.xml
<CustomField>
    <fullName>Invoice_No__c</fullName>
    <externalId>true</externalId>
    <label>Invoice No</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Is_Order_Owner_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Order_Owner_Active__c</fullName>
    <formula>SF_Order__r.Owner:User.IsActive</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Order Owner Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Order_OwnerId__c.field-meta.xml
<CustomField>
    <fullName>Order_OwnerId__c</fullName>
    <formula>CASESAFEID(SF_Order__r.OwnerId )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order OwnerId</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/SF_Order__c.field-meta.xml
<CustomField>
    <fullName>SF_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SF Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/Product_Mapping__c.object-meta.xml
<CustomObject>
    <label>Product Mapping</label>
    <nameField>
        <displayFormat>PM-{0000}</displayFormat>
        <label>Product Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Mapping__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Product Mappings</relationshipLabel>
    <relationshipName>Product_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Customer_Delivery_Plant_Pair__c.field-meta.xml
<CustomField>
    <fullName>Customer_Delivery_Plant_Pair__c</fullName>
    <formula>Customer__r.SAP_Customer_Code__c +&apos;_&apos;+Text(Child_Depot__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Delivery Plant Pair</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Customer_SAP_Code__c.field-meta.xml
<CustomField>
    <fullName>Customer_SAP_Code__c</fullName>
    <formula>Customer__r.SAP_Customer_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer SAP Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Exectuive__c.field-meta.xml
<CustomField>
    <fullName>Exectuive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Executive</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Product_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Hierarchy_Number__c.field-meta.xml
<CustomField>
    <fullName>Hierarchy_Number__c</fullName>
    <formula>Exectuive__r.Heirarchial_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Hierarchy Number</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/is_Executive_Active__c.field-meta.xml
<CustomField>
    <fullName>is_Executive_Active__c</fullName>
    <formula>Exectuive__r.IsActive</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>is Executive Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/InvoiceHeaderTriggerHandler.cls
public class InvoiceHeaderTriggerHandler {
    public static void beforeInsert(List<Invoice__c> newInvoicesList) {
        
        Set<String> invoiceNumberSet = new Set<String>();
        Set<String> customerCodeSet = new Set<String>();
        Set<String> customerExecuivePair = new Set<String>();
        
        for(Invoice__c item : newInvoicesList) {
            invoiceNumberSet.add(item.Invoice_No__c); 
            customerCodeSet.add(item.Customer_SAP_Code__c); 
            if(item.SF_Order__c == null)
            {
                string key = item.Customer_SAP_Code__c+'_' +item.Delivery_Plant__c;
                customerExecuivePair.add(key); 
            }
        }
        
        Map<String, Product_Mapping__c> pairWithLowestHierarchy = new Map<String, Product_Mapping__c>();
        
        List<Product_Mapping__c> executiveMappings = [
            SELECT Id, Name, Customer_Delivery_Plant_Pair__c, Hierarchy_Number__c,Exectuive__c FROM Product_Mapping__c
            WHERE Customer_Delivery_Plant_Pair__c IN :customerExecuivePair and Exectuive__c != null AND Customer__c != null and is_Executive_Active__c = true limit 50000
        ];
        
        for (Product_Mapping__c pm : executiveMappings) {
            String key = pm.Customer_Delivery_Plant_Pair__c;
            // If key not in map, add it
            if (!pairWithLowestHierarchy.containsKey(key)) { pairWithLowestHierarchy.put(key, pm);} 
            else {
                // Compare hierarchy numbers, keep the lowest
                Product_Mapping__c existing = pairWithLowestHierarchy.get(key);
                if (pm.Hierarchy_Number__c < existing.Hierarchy_Number__c) {pairWithLowestHierarchy.put(key, pm); }
            }
        }
        
        // Example usage: assign owner or other logic
        for (Invoice__c inv : newInvoicesList) {
            String invoiceNumber = inv.Invoice_No__c;
            if(inv.Is_Order_Owner_Active__c == True && inv.SF_Order__c != null && inv.Order_OwnerId__c != null){inv.OwnerId = inv.Order_OwnerId__c; }
            else if((inv.SF_Order__c == null || inv.SF_Order__c == '') && (inv.Customer_SAP_Code__c != null && inv.Delivery_Plant__c != null))
            {
                String key = inv.Customer_SAP_Code__c + '_' + inv.Delivery_Plant__c;
                if (pairWithLowestHierarchy.containsKey(key)) {
                    Product_Mapping__c lowestMapping = pairWithLowestHierarchy.get(key);
                    inv.OwnerId = lowestMapping.Exectuive__c; 
                }
            } 
        }
    }
}