force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Lead</label>
    <nameField>
        <label>Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Submitted</fullName>
                <default>true</default>
                <label>Not Submitted</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Admin Approved</fullName>
            </value>
            <value>
                <fullName>Admin Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>RSM Approved</fullName>
                <isActive>false</isActive>
                <label>Manager Approved</label>
            </value>
            <value>
                <fullName>RSM Rejected</fullName>
                <isActive>false</isActive>
                <label>Manager Rejected</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <isActive>false</isActive>
                <label>Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Followup_Date__c.field-meta.xml
<CustomField>
    <fullName>Followup_Date__c</fullName>
    <label>Followup Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Lead_Status__c.field-meta.xml
<CustomField>
    <fullName>Lead_Status__c</fullName>
    <label>Lead Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Working</fullName>
            </value>
            <value>
                <fullName>Follow Up</fullName>
            </value>
            <value>
                <fullName>Unqualified</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
            <value>
                <fullName>Converted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Lost_Reasons__c.field-meta.xml
<CustomField>
    <fullName>Lost_Reasons__c</fullName>
    <label>Lost Reasons</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lost to competitor</fullName>
            </value>
            <value>
                <fullName>Budget issue</fullName>
            </value>
            <value>
                <fullName>Not interested</fullName>
            </value>
            <value>
                <fullName>Random enquiry</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Lost_to_competitor_Name__c.field-meta.xml
<CustomField>
    <fullName>Lost_to_competitor_Name__c</fullName>
    <label>Lost to Competitor Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Other_reason__c.field-meta.xml
<CustomField>
    <fullName>Other_reason__c</fullName>
    <label>Other reason</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cold</fullName>
                <default>true</default>
                <label>Cold</label>
            </value>
            <value>
                <fullName>Warm</fullName>
            </value>
            <value>
                <fullName>Hot</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/StatusPathController.cls
public class StatusPathController 
{
    public class dataBox{ 
        @AuraEnabled
        public string RatingVal {get; set;}
        @AuraEnabled
        public list<string> picklistValues  {get; set;}
        @AuraEnabled
        public list<string> LostpicklistValues  {get; set;}
        @AuraEnabled
        public list<string> LeadStatuspicklistValues  {get; set;}
        @AuraEnabled
        public list<user> userlist  {get; set;}
       /* @AuraEnabled
        public list<Add_users__c> AddUserList  {get; set;}*/
        @AuraEnabled
        public Lead__c LeadRec  {get; set;}
        
    }
   
    
   
    @AuraEnabled
    public static dataBox getAllData(string recordId) {
        dataBox dbs= new dataBox();
        dbs.RatingVal=  [select Id,Rating__C from Lead__C where id=:recordId limit 1 ].Rating__c;
        
        String objectName = 'Lead__c';
        String fieldName = 'Rating__c';
        List<String> picklistValues = new List<String>();
        Schema.DescribeSObjectResult objectDescribe = Schema.getGlobalDescribe().get(objectName).getDescribe();
        Schema.DescribeFieldResult fieldDescribe = objectDescribe.fields.getMap().get(fieldName).getDescribe();
        system.debug('fieldDescribe'+fieldDescribe);
        List<Schema.PicklistEntry> picklistEntries = fieldDescribe.getPicklistValues();
        for (Schema.PicklistEntry entry : picklistEntries) {
            picklistValues.add(entry.getLabel());
        }
        dbs.picklistValues=picklistValues;
        
        String objectName1 = 'Lead__c';
        String fieldName1 = 'Lost_Reasons__c';
        List<String> picklistValues1 = new List<String>();
        Schema.DescribeSObjectResult objectDescribe1 = Schema.getGlobalDescribe().get(objectName1).getDescribe();
        Schema.DescribeFieldResult fieldDescribe1 = objectDescribe.fields.getMap().get(fieldName1).getDescribe();
        system.debug('fieldDescribe'+fieldDescribe1);
        
        List<Schema.PicklistEntry> picklistEntries1 = fieldDescribe1.getPicklistValues();
        for (Schema.PicklistEntry entry : picklistEntries1)
        {
            picklistValues1.add(entry.getLabel());
        }
        dbs.LostpicklistValues=picklistValues1;
        
        String objectName2 = 'Lead__c';
        String fieldName2 = 'Lead_Status__c';
        List<String> picklistValues2 = new List<String>();
        Schema.DescribeSObjectResult objectDescribe2 = Schema.getGlobalDescribe().get(objectName2).getDescribe();
        Schema.DescribeFieldResult fieldDescribe2 = objectDescribe.fields.getMap().get(fieldName2).getDescribe();
        system.debug('fieldDescribe'+fieldDescribe2);
        
        List<Schema.PicklistEntry> picklistEntries2 = fieldDescribe2.getPicklistValues();
        for (Schema.PicklistEntry entry : picklistEntries2)
        {
            picklistValues2.add(entry.getLabel());
        }
 
        dbs.LeadStatuspicklistValues=picklistValues2;
            
        dbs.userlist =  [select Id,Name from User order by Name];
        //dbs.AddUserList = [SELECT Id, Name, Lead__c, UserId__c FROM Add_users__c WHERE Lead__c =:recordId LIMIT 5];
        dbs.LeadRec = [SELECT Id, Name,Lead_Status__c,Approval_Status__c,Followup_Date__c,Lost_to_competitor_Name__c, Other_reason__c,Lost_Reasons__c from Lead__c where id=:recordId LIMIT 1];
        return dbs;
    }
    @AuraEnabled
    public static void MarkStatusAPex(string recordId, string currentStep) {
        lead__c ld = new lead__c();
        ld.id=recordId;
        ld.Lead_Status__c=currentStep;
        update ld;
       
    }
 	@AuraEnabled
    public static string SaveRatingpop(string Rating,string LeadId, Date FollowUpDate) {
        
        try {
            
            lead__c ld = new lead__c();
            ld.id=LeadId;
            if(Rating == null || Rating == '')
                Rating='Cold';
            ld.Rating__c=Rating;
            if(FollowUpDate != null)
                ld.Followup_Date__c=FollowUpDate;
            ld.Lead_Status__c='Follow Up';
            update ld;
            
            
            return 'Successfull';
        } catch (DmlException e) {
            System.debug('Upsert failed.');
            System.debug('Error: ' + e.getMessage());
            return e.getMessage() + 'unsuccessful';
        }
    }
    @AuraEnabled
    public static string Savelostpop(string OtherReason, String lostReason, string LostToCompetitorName, string LeadId){
        try {
            lead__c ld = new lead__c();
            ld.id=LeadId;
            ld.Lost_Reasons__c=lostReason;
            if(OtherReason != null && OtherReason != '')
            {
                ld.Other_reason__c=OtherReason;
            }
            if(LostToCompetitorName != null && LostToCompetitorName != '')
            {
                ld.Lost_to_competitor_Name__c = LostToCompetitorName;
            }
            ld.Lead_Status__c='Closed Lost';
            update ld;
            return 'Successfull';
        } catch (DmlException e) {
            System.debug('Upsert failed.');
            System.debug('Error: ' + e.getMessage());
            return e.getMessage() + 'unsuccessful';
        }
    }
    @AuraEnabled
    public static Lead__c RatingValue(string recordId) 
    {
        Lead__c ld = [select Id,Rating__C,Followup_Date__c from Lead__C where id=:recordId limit 1 ];
        return ld;
    }
    @AuraEnabled
    public static Lead__c LeadRecord(string recordId) 
    {
        Lead__c ld =[SELECT Id, Name,Lead_Status__c,Lost_to_competitor_Name__c, Other_reason__c,Lost_Reasons__c from Lead__c where id=:recordId LIMIT 1];
        return ld;
    }
    
}