force-app/main/default/objects/Collection__c/Collection__c.object-meta.xml
<CustomObject>
    <label>Collection</label>
    <nameField>
        <displayFormat>Collection -{00000}</displayFormat>
        <label>Collections Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Log__c/Daily_Log__c.object-meta.xml
<CustomObject>
    <label>Daily Attendance</label>
    <nameField>
        <displayFormat>Log Id - {00000}</displayFormat>
        <label>Log Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Attendances</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Return__c/Return__c.object-meta.xml
<CustomObject>
    <label>Return</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Return Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Returns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Return__c/fields/UniqueFileId__c.field-meta.xml
<CustomField>
    <fullName>UniqueFileId__c</fullName>
    <label>UniqueFileId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ReturnTriggerHandlerTest.cls
@isTest
public class ReturnTriggerHandlerTest {
 
    @isTest
    static void testAfterInsert() {
              // Insert the test records
        Test.startTest();
        // Create test data
        List<Return__c> testCollections = new List<Return__c>();
        
        // Add a few Return__c records with unique file IDs
        for (Integer i = 0; i < 5; i++) {
            testCollections.add(new Return__c(
                UniqueFileId__c = 'FileId_' + i,
                OwnerId = UserInfo.getUserId()
            ));
        }
        
        List<Return__c> testCollections1 = new List<Return__c>();
        
        // Add a few Return__c records with unique file IDs
        for (Integer i = 0; i < 5; i++) {
            testCollections1.add(new Return__c(
                UniqueFileId__c = 'FileId_' + i,
                OwnerId = UserInfo.getUserId()
            ));
        }
        insert testCollections1;
        
  
        insert testCollections;
        daily_log__c daily = new Daily_log__c();
        daily.OwnerId = UserInfo.getUserId();
        insert daily;
        
        delete testCollections1;
        Test.stopTest();
        
       
        //List<Collection__c> insertedCollections = [SELECT Id, UniqueFileId__c FROM Collection__c];
        //System.assertEquals(5, insertedCollections.size(), 'Five collections should be inserted.');
    }
}