force-app/main/default/objects/Beat__c/Beat__c.object-meta.xml
<CustomObject>
    <label>Beat Plan</label>
    <nameField>
        <displayFormat>BEAT-{00}</displayFormat>
        <label>BEATID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Beat Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Beat_Assignment__c/Beat_Assignment__c.object-meta.xml
<CustomObject>
    <label>Beat Assignment</label>
    <nameField>
        <displayFormat>ASGN-{0000}</displayFormat>
        <label>Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Beat Assignment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Beat_Assignment__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <label>Active</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Beat_Assignment__c/fields/Beat__c.field-meta.xml
<CustomField>
    <fullName>Beat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Beat</label>
    <referenceTo>Child_beat__c</referenceTo>
    <relationshipLabel>Beat Assignment</relationshipLabel>
    <relationshipName>Beat_Assignment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Beat_Assignment__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Beat_Assignment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Calendar_beat__c/Calendar_beat__c.object-meta.xml
<CustomObject>
    <label>PJP</label>
    <nameField>
        <displayFormat>PJP - {0000}</displayFormat>
        <label>PJP Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PJPs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Calendar_beat__c/fields/Auto_PJP_Creation__c.field-meta.xml
<CustomField>
    <fullName>Auto_PJP_Creation__c</fullName>
    <formula>IF(User__r.Profile.Name == &apos;DSM&apos; || User__r.Profile.Name == &apos;SSA&apos;, true, false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Auto PJP Creation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Calendar_beat__c/fields/Next_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Start_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Calendar_beat__c/fields/Start_Month__c.field-meta.xml
<CustomField>
    <fullName>Start_Month__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Calendar_beat__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PJPs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Child_beat__c/Child_beat__c.object-meta.xml
<CustomObject>
    <label>Beat</label>
    <nameField>
        <label>Beat Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Beats</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Child_beat__c/fields/Calendar_beat__c.field-meta.xml
<CustomField>
    <fullName>Calendar_beat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PJP</label>
    <referenceTo>Calendar_beat__c</referenceTo>
    <relationshipLabel>Beats</relationshipLabel>
    <relationshipName>Child_beats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Child_beat__c/fields/isRepeat__c.field-meta.xml
<CustomField>
    <fullName>isRepeat__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isRepeat</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Child_beat__c/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <label>Order Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Child_beat__c/fields/Primary_Customer__c.field-meta.xml
<CustomField>
    <fullName>Primary_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Beats</relationshipLabel>
    <relationshipName>Beats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Child_beat__c/fields/Sub_Stockist__c.field-meta.xml
<CustomField>
    <fullName>Sub_Stockist__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sub Stockist</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Beats (Sub Stockist)</relationshipLabel>
    <relationshipName>Beats1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Child_beat__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Beats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Holiday__c/Holiday__c.object-meta.xml
<CustomObject>
    <label>Holiday</label>
    <nameField>
        <label>Holiday Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Holidays</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Holiday__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Regions</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PJP_Item__c/PJP_Item__c.object-meta.xml
<CustomObject>
    <label>PJP Item</label>
    <nameField>
        <displayFormat>ITEM - {0000}</displayFormat>
        <label>PJP Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PJP Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PJP_Item__c/fields/Assigned_Beat__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Beat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Beat</label>
    <referenceTo>Child_beat__c</referenceTo>
    <relationshipLabel>PJP Items (Worked Beat)</relationshipLabel>
    <relationshipName>PJP_Items1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PJP_Item__c/fields/Beat__c.field-meta.xml
<CustomField>
    <fullName>Beat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approved Beat</label>
    <referenceTo>Child_beat__c</referenceTo>
    <relationshipLabel>PJP Items</relationshipLabel>
    <relationshipName>PJP_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PJP_Item__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PJP_Item__c/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <label>Sequence Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PJP_Item__c/fields/PJP__c.field-meta.xml
<CustomField>
    <fullName>PJP__c</fullName>
    <label>PJP</label>
    <referenceTo>Calendar_beat__c</referenceTo>
    <relationshipLabel>PJP Items</relationshipLabel>
    <relationshipName>PJP_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PJP_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Submitted</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Region__c/Region__c.object-meta.xml
<CustomObject>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/PJPItemScheduler.cls
global class PJPItemScheduler implements Database.Batchable<sObject>,Database.Stateful,Schedulable{
    
    public Database.QueryLocator start(Database.BatchableContext BC){
        String query = 'SELECT Id, Name, OwnerId,User__c,Start_Month__c,Next_Start_Date__c,(select Id,Name,Date__c,PJP__c from PJP_Items__r order by Date__c desc limit 1) FROM Calendar_beat__c WHERE Active__c = true AND Auto_PJP_Creation__c = true';
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext BC, List<Calendar_beat__c> pjpRecords){
        
        
        Calendar_beat__c pjp = pjpRecords[0];
        String ids = pjp.User__c;
        
        
        PJP_Item__c lastPJPItem = new PJP_Item__c();
        
        if(pjp.PJP_Items__r.size()>0){
            lastPJPItem = pjp.PJP_Items__r[0];
            
            if(lastPJPItem.Date__c == Date.today()){
                List<Child_Beat__c> childBeats = [SELECT Id, Name,isRepeat__c,Order_Number__c,
                                                  Primary_Customer__c, Sub_Stockist__c
                                                  FROM Child_Beat__c
                                                  WHERE OwnerId =:ids AND  Active__c = true order by Order_Number__c];
                
                
                List<User> selUser = [SELECT Id, Name, Region__c
                                      FROM User
                                      WHERE Id = :ids];
                
                String userRegion = selUser[0].Region__c;
                
                List<Holiday__c> holi = [SELECT id, name,Date__c from Holiday__c  WHERE Region__c INCLUDES (:userRegion)
                                         ORDER BY CreatedDate ASC];
                
                Set<Date> dates = new Set<Date>();
                
                for(Holiday__c hd: holi){
                    dates.add(hd.Date__c);
                }
                
                
                List<PJP_Item__c> itemsToCreate = new List<PJP_Item__c>();
                
                Date dt = Date.today().addDays(1);
                
                for(Child_Beat__c cb: childBeats){
                    
                    Integer dayOfWeek = dt.toStartOfWeek().daysBetween(dt);
                    
                    if(dayOfWeek == 0){
                        dt = dt.addDays(1);
                    }
                    else{
                        while(dates.contains(dt)){
                            dt = dt.addDays(1);
                        }
                    }
                    
                    
                    PJP_Item__c item = new PJP_Item__c();
                    item.PJP__c = pjp.Id;
                    item.Date__c = dt;
                    item.Beat__c = cb.Id;
                    item.Assigned_Beat__c = cb.Id;
                    item.Beat__c = cb.Id;
                    /*  item.Order_Number__c = cb.Beat_Assignment__r[0].Order_Number__c; */
                    item.Order_Number__c = cb.Order_Number__c;
                    item.Status__c = 'Approved';
                    itemsToCreate.add(item);
                    dt = dt.addDays(1);
                }
                
                if(!itemsToCreate.isEmpty()){
                    insert itemsToCreate;
                }
            }
            
        }
        
        
        
    }
    
    public void finish(Database.BatchableContext BC){
    }
    
    global void execute(SchedulableContext SC){
        
        Database.executeBatch(new PJPItemScheduler(), 1);
       /* String cronExpression = '0 55 23 * * ?'; // Cron expression for 11:55 PM every day
        String jobName = 'PJPItemScheduler';
        
        System.schedule(jobName, cronExpression, new PJPItemScheduler());*/
    } 
    
}