force-app/main/default/objects/Beat__c/Beat__c.object-meta.xml
<CustomObject>
    <label>Beat Plan</label>
    <nameField>
        <displayFormat>BEAT-{00}</displayFormat>
        <label>BEATID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Beat Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Calendar_beat__c/Calendar_beat__c.object-meta.xml
<CustomObject>
    <label>PJP</label>
    <nameField>
        <displayFormat>PJP - {0000}</displayFormat>
        <label>PJP Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PJPs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Calendar_beat__c/fields/Employee_code__c.field-meta.xml
<CustomField>
    <fullName>Employee_code__c</fullName>
    <formula>User__r.Employee_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Employee code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Calendar_beat__c/fields/Next_PJP_Run__c.field-meta.xml
<CustomField>
    <fullName>Next_PJP_Run__c</fullName>
    <label>Next PJP Run</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Calendar_beat__c/fields/Recurring_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Recurring_Frequency__c</fullName>
    <label>Recurring Frequency</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Calendar_beat__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PJPs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Child_beat__c/Child_beat__c.object-meta.xml
<CustomObject>
    <label>Beat</label>
    <nameField>
        <label>Beat Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Beats</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Child_beat__c/fields/Calendar_beat__c.field-meta.xml
<CustomField>
    <fullName>Calendar_beat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PJP</label>
    <referenceTo>Calendar_beat__c</referenceTo>
    <relationshipLabel>Beats</relationshipLabel>
    <relationshipName>Child_beats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Child_beat__c/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <label>Order Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Child_beat__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Beats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PJP_Item__c/PJP_Item__c.object-meta.xml
<CustomObject>
    <label>PJP Item</label>
    <nameField>
        <displayFormat>ITEM - {0000}</displayFormat>
        <label>PJP Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PJP Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PJP_Item__c/fields/Assigned_Beat__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Beat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Beat</label>
    <referenceTo>Child_beat__c</referenceTo>
    <relationshipLabel>PJP Items (Worked Beat)</relationshipLabel>
    <relationshipName>PJP_Items1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PJP_Item__c/fields/Beat__c.field-meta.xml
<CustomField>
    <fullName>Beat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approved Beat</label>
    <referenceTo>Child_beat__c</referenceTo>
    <relationshipLabel>PJP Items</relationshipLabel>
    <relationshipName>PJP_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PJP_Item__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PJP_Item__c/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <label>Sequence Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PJP_Item__c/fields/PJP__c.field-meta.xml
<CustomField>
    <fullName>PJP__c</fullName>
    <label>PJP</label>
    <referenceTo>Calendar_beat__c</referenceTo>
    <relationshipLabel>PJP Items</relationshipLabel>
    <relationshipName>PJP_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PJP_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Submitted</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Region__c/Region__c.object-meta.xml
<CustomObject>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AutoPJPCreationSchedulerTest.cls
@isTest
public class AutoPJPCreationSchedulerTest {
    
    // Helper method to insert test data
    private static void createTestData() {
       // Create test user
        Profile p = [SELECT Id FROM Profile WHERE Name='DSM'];
        User testUser = new User(
            Alias = 'testusr',
            Email = 'testuser@testorg.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'Testing',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = p.Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            UserName = 'testuser109rtyed56@testorg.com',
            Region__c = 'Tamil Nadu',
            Employee_Code__c = '4411'
        );
        insert testUser;
        
        // Create test calendar beat
        Calendar_beat__c testPJP = new Calendar_beat__c(
            Active__c = true,
            Recurring_Frequency__c = 5,
            Next_PJP_Run__c = Date.today(),
            User__c = testUser.Id,
            OwnerId = testUser.Id
        );
        insert testPJP;
        
        // Create test child beats
        List<Child_Beat__c> childBeats = new List<Child_Beat__c>();
        childBeats.add(new Child_Beat__c(
            Name = 'Child Beat 1',
            Active__c = true,
            Order_Number__c = 1,
            OwnerId = testUser.Id
        ));
        childBeats.add(new Child_Beat__c(
            Name = 'Child Beat 2',
            Active__c = true,
            Order_Number__c = 2,
            OwnerId = testUser.Id
        ));
        insert childBeats;
        
        // Create test PJP_Item__c records related to the Calendar_beat
        List<PJP_Item__c> pjpItems = new List<PJP_Item__c>();
        for (Integer i = 0; i < 2; i++) {
            pjpItems.add(new PJP_Item__c(
                PJP__c = testPJP.Id,
                Date__c = Date.today().addDays(-i-1), // Assigning dates from the past
                Beat__c = childBeats[i].id,
                Assigned_Beat__c = childBeats[i].id,
                Order_Number__c = i + 1,
                Status__c = 'Approved'
            ));
        }
        insert pjpItems;
    }

    @isTest
    public static void testBatchableClass() {
        // Step 1: Prepare the test data
        createTestData();

        // Step 2: Create an instance of the batchable class
        AutoPJPCreationScheduler scheduler = new AutoPJPCreationScheduler();

        // Step 3: Execute the batchable class using a test context
        Test.startTest();
        
        // Execute the batch job manually
        Database.executeBatch(scheduler, 1);
        
        Test.stopTest();
        
        
    }

    @isTest
    public static void testSchedulableClass() {
        // Step 1: Prepare the test data
        createTestData();
        
        // Step 2: Create an instance of the schedulable class
        AutoPJPCreationScheduler scheduler = new AutoPJPCreationScheduler();
        
        // Step 3: Schedule the job using the cron expression
        String cronExpression = '0 55 23 * * ?'; // Cron expression for 11:55 PM every day
        System.schedule('Test PJPItemScheduler', cronExpression, scheduler);
        
        // Step 4: Verify that the job has been scheduled
        CronTrigger[] scheduledJobs = [SELECT Id, CronExpression FROM CronTrigger WHERE CronJobDetail.Name = 'Test PJPItemScheduler'];
        System.assertEquals(1, scheduledJobs.size(), 'Expected the job to be scheduled.');
        System.assertEquals(cronExpression, scheduledJobs[0].CronExpression, 'Expected the correct cron expression.');
    }
}