force-app/main/default/objects/Beat__c/Beat__c.object-meta.xml
<CustomObject>
    <label>Beat Plan</label>
    <nameField>
        <displayFormat>BEAT-{00}</displayFormat>
        <label>BEATID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Beat Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Calendar_beat__c/Calendar_beat__c.object-meta.xml
<CustomObject>
    <label>PJP</label>
    <nameField>
        <displayFormat>PJP - {0000}</displayFormat>
        <label>PJP Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PJPs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Calendar_beat__c/fields/Last_PJP_Run__c.field-meta.xml
<CustomField>
    <fullName>Last_PJP_Run__c</fullName>
    <label>Last PJP Run</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Calendar_beat__c/fields/Next_PJP_Run__c.field-meta.xml
<CustomField>
    <fullName>Next_PJP_Run__c</fullName>
    <label>Next PJP Run</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Calendar_beat__c/fields/Next_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Start_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Calendar_beat__c/fields/Recurring_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Recurring_Frequency__c</fullName>
    <label>Recurring Frequency</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Calendar_beat__c/fields/Start_Month__c.field-meta.xml
<CustomField>
    <fullName>Start_Month__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Calendar_beat__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PJPs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PJP_Item__c/PJP_Item__c.object-meta.xml
<CustomObject>
    <label>PJP Item</label>
    <nameField>
        <displayFormat>ITEM - {0000}</displayFormat>
        <label>PJP Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PJP Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PJP_Item__c/fields/Assigned_Beat__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Beat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Beat</label>
    <referenceTo>Child_beat__c</referenceTo>
    <relationshipLabel>PJP Items (Worked Beat)</relationshipLabel>
    <relationshipName>PJP_Items1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PJP_Item__c/fields/Beat__c.field-meta.xml
<CustomField>
    <fullName>Beat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approved Beat</label>
    <referenceTo>Child_beat__c</referenceTo>
    <relationshipLabel>PJP Items</relationshipLabel>
    <relationshipName>PJP_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PJP_Item__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PJP_Item__c/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <label>Sequence Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PJP_Item__c/fields/PJP__c.field-meta.xml
<CustomField>
    <fullName>PJP__c</fullName>
    <label>PJP</label>
    <referenceTo>Calendar_beat__c</referenceTo>
    <relationshipLabel>PJP Items</relationshipLabel>
    <relationshipName>PJP_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PJP_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Submitted</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AutoPJPCreationScheduler.cls
global class AutoPJPCreationScheduler  implements Database.Batchable<sObject>,Database.Stateful,Schedulable{
    
    public Database.QueryLocator start(Database.BatchableContext BC){
        String query = 'SELECT Id, Name, OwnerId,User__c,Start_Month__c,Next_Start_Date__c,Recurring_Frequency__c FROM Calendar_beat__c WHERE Active__c = true AND Recurring_Frequency__c != null AND Next_PJP_Run__c = TODAY';
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext BC, List<Calendar_beat__c> pjpRecords){
        
        
        Calendar_beat__c pjp = pjpRecords[0];
        Integer frequency = (Integer) pjp.Recurring_Frequency__c;
        
        Date today = Date.today();
        Date newStartDate = today.addDays(-frequency); // Start from the next day after the last item
        
        pjp.Next_PJP_Run__c = today.addDays(frequency);
        pjp.Last_PJP_Run__c = today;
        
        List<PJP_Item__c> futureItems = [select Id,Date__c from PJP_Item__c where PJP__c = : pjp.Id and Date__c >=:System.TODAY() limit 1];
        system.debug('futureItems:' + futureItems);
        
        if(futureItems.isEmpty()){
            List<PJP_Item__c> items = [select Id,Name,Beat__c,Assigned_Beat__c,Date__c,PJP__c, Order_Number__c,
                                       Status__c from PJP_Item__c
                                       where PJP__c = : pjp.Id and (Date__c <:System.TODAY() and Date__c >= :newStartDate)
                                       order by Date__c asc];     
            
            if (!items.isEmpty()) {
                
                
                // Create a map to store unique items by date
                Map<Date,PJP_Item__c> itemsMap = new Map<Date,PJP_Item__c>();
                for(PJP_Item__c itm : items){
                    if(!itemsMap.containsKey(itm.Date__c)){
                        itemsMap.put(itm.Date__c, itm);
                    }
                }
                Date pjpDate = today;
                List<PJP_Item__c> itemsToCreate = new List<PJP_Item__c>();
                while(newStartDate <= today){
                    if(itemsMap.containsKey(newStartDate)){
                        PJP_Item__c newItem = new PJP_Item__c();
                        newItem.PJP__c = pjp.Id;
                        newItem.Date__c = pjpDate;
                        newItem.Beat__c = itemsMap.get(newStartDate).Beat__c; // Set to null or appropriate value
                        newItem.Assigned_Beat__c = itemsMap.get(newStartDate).Beat__c; // Set to null or appropriate value
                        newItem.Order_Number__c = 1; // Set to default or appropriate value
                        newItem.Status__c = 'Approved'; // Set to default or appropriate value
                        itemsToCreate.add(newItem);
                    }
                    newStartDate = newStartDate.addDays(1);
                    pjpDate = pjpDate.addDays(1);
                }
                
                if(!itemsToCreate.isEmpty()){
                    try{
                        insert itemsToCreate;
                    }
                    catch(Exception e){
                        ExceptionHandler.addLog(e, String.valueOf(itemsToCreate), 'userProfileLWC.createPJP');
                    }
                }
            }
        }   
        
        try{
            update pjp;
        }
        catch(Exception e){
            ExceptionHandler.addLog(e, String.valueOf(pjp), 'userProfileLWC.createPJP');
        }
        
        
        
    }
    
    public void finish(Database.BatchableContext BC){
    }
    
    global void execute(SchedulableContext SC){
        
        Database.executeBatch(new AutoPJPCreationScheduler(), 1);
        /* String cronExpression = '0 00 6 * * ?'; // Cron expression for 6:00 AM every day
        String jobName = 'AutoPJPCreationScheduler';
        
        System.schedule(jobName, cronExpression, new AutoPJPCreationScheduler());*/
    } 
    
}