force-app/main/default/objects/Beat__c/Beat__c.object-meta.xml
<CustomObject>
    <label>Beat Plan</label>
    <nameField>
        <displayFormat>BEAT-{00}</displayFormat>
        <label>BEATID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Beat Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Beat__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Submitted</fullName>
                <default>true</default>
                <label>Not Submitted</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Calendar_beat__c/Calendar_beat__c.object-meta.xml
<CustomObject>
    <label>PJP</label>
    <nameField>
        <displayFormat>PJP - {0000}</displayFormat>
        <label>PJP Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PJPs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Calendar_beat__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Submitted</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Calendar_beat__c/fields/Employee_code__c.field-meta.xml
<CustomField>
    <fullName>Employee_code__c</fullName>
    <formula>User__r.Employee_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Employee code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Child_beat__c/Child_beat__c.object-meta.xml
<CustomObject>
    <label>Beat</label>
    <nameField>
        <label>Beat Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Beats</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Child_beat__c/fields/Beat_Type__c.field-meta.xml
<CustomField>
    <fullName>Beat_Type__c</fullName>
    <label>Beat Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Child_beat__c/fields/Calendar_beat__c.field-meta.xml
<CustomField>
    <fullName>Calendar_beat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PJP</label>
    <referenceTo>Calendar_beat__c</referenceTo>
    <relationshipLabel>Beats</relationshipLabel>
    <relationshipName>Child_beats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Collection_Item__c/Collection_Item__c.object-meta.xml
<CustomObject>
    <label>Collection Item</label>
    <nameField>
        <displayFormat>Collection Item - {00000}</displayFormat>
        <label>Collection Items Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collection Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Collection_Item__c/fields/Amount_Received__c.field-meta.xml
<CustomField>
    <fullName>Amount_Received__c</fullName>
    <label>Amount Received (INR)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Daily_Log__c/Daily_Log__c.object-meta.xml
<CustomObject>
    <label>Daily Attendance</label>
    <nameField>
        <displayFormat>Log Id - {00000}</displayFormat>
        <label>Log Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Attendances</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Log__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Daily_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Daily_Log__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Approval_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Daily_Log__c/fields/Child_beat__c.field-meta.xml
<CustomField>
    <fullName>Child_beat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Child beat</label>
    <referenceTo>Child_beat__c</referenceTo>
    <relationshipName>Daily_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Daily_Log__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <formula>DATEVALUE( Day_started_time__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Daily_Log__c/fields/Employee_Code__c.field-meta.xml
<CustomField>
    <fullName>Employee_Code__c</fullName>
    <formula>Owner:User.Employee_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Employee Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Log__c/fields/New_Calls__c.field-meta.xml
<CustomField>
    <fullName>New_Calls__c</fullName>
    <label>New Calls</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Daily_Log__c/fields/Total_Order_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Order_Amount__c</fullName>
    <label>Total Order Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Daily_Log__c/fields/Total_Productive_Calls__c.field-meta.xml
<CustomField>
    <fullName>Total_Productive_Calls__c</fullName>
    <label>PJP PC</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Daily_Log__c/fields/Total_Visits__c.field-meta.xml
<CustomField>
    <fullName>Total_Visits__c</fullName>
    <label>PJP TC</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order Request</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Order Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Account)</relationshipLabel>
    <relationshipName>Orders2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Customer_type__c.field-meta.xml
<CustomField>
    <fullName>Customer_type__c</fullName>
    <label>Customer type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary Customer</fullName>
            </value>
            <value>
                <fullName>Secondary Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/DISTRICT__c.field-meta.xml
<CustomField>
    <fullName>DISTRICT__c</fullName>
    <formula>TEXT(Account__r.District__c)</formula>
    <label>DISTRICT</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <label>Customer Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary Order</fullName>
            </value>
            <value>
                <fullName>Secondary Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Orderfulfilment_Date__c.field-meta.xml
<CustomField>
    <fullName>Orderfulfilment_Date__c</fullName>
    <label>Order Fulfilment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Secondary_Customer_Category__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Customer_Category__c</fullName>
    <formula>TEXT(Account__r.Secondary_Customer_Category__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Secondary Customer Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>RE - {00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <formula>IF(
  Text(Order__r.Order_Type__c) = &apos;Primary Order&apos;,
  &apos;Primary&apos;,
  IF(
    Text(Order__r.Account__r.Secondary_Customer_Type__c) = &apos;Sub Stockiest&apos;,
    &apos;Sub Stockiest&apos;,
    &apos;Outlet&apos;
  )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Daily_log__c.field-meta.xml
<CustomField>
    <fullName>Daily_log__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Daily log</label>
    <referenceTo>DailyLog__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order_Date__c.field-meta.xml
<CustomField>
    <fullName>Order_Date__c</fullName>
    <formula>Order__r.Order_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PJP_Item__c/PJP_Item__c.object-meta.xml
<CustomObject>
    <label>PJP Item</label>
    <nameField>
        <displayFormat>ITEM - {0000}</displayFormat>
        <label>PJP Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PJP Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PJP_Item__c/fields/Beat__c.field-meta.xml
<CustomField>
    <fullName>Beat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approved Beat</label>
    <referenceTo>Child_beat__c</referenceTo>
    <relationshipLabel>PJP Items</relationshipLabel>
    <relationshipName>PJP_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PJP_Item__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/EODReportPdfControllerTest.cls
@isTest
public class EODReportPdfControllerTest {

    @testSetup
    static void setupData() {
        // Create test User
        Profile p = [SELECT Id FROM Profile WHERE Name = 'TSE' LIMIT 1];
        User u = new User(
            Alias = 'tuser',
            Email='durgaprasad@fingertipplus.com',
            EmailEncodingKey='UTF-8',
            LastName='Test',
            LanguageLocaleKey='en_US',
            LocaleSidKey='en_US',
            ProfileId=p.Id,
            Employee_Code__c = '1191010',
            TimeZoneSidKey='America/Los_Angeles',
            Username='testuser' + System.currentTimeMillis() + '@test.com'
        );
        insert u;

        // Daily Log
        Daily_Log__c dlog = new Daily_Log__c(
            OwnerId = u.Id,
            Is_System_Ended__c = true,
            Total_Visits__c = 5,
            Total_Productive_Calls__c = 3,
            New_Calls__c = 2,
            Total_Order_Amount__c = 1000
        );
        insert dlog;

        
        
        // Account for Order
        Account acc =   new Account(
            Name = 'Primary Cust',
            City__c = 'Delhi',
            State__c = 'Delhi',
            District__c = 'New Delhi',
            Primary_Phone_Number__c = '9999999999',
            Aadhaar_No__c = '123412341234',
            Pincode__c = '110001',
            Customer_Type__c = 'Primary Customer',
            Customer_Status__c = 'Active',
            GeoLocation__Latitude__s =  28.6139,
            GeoLocation__Longitude__s = 77.2090,
            Secondary_Customer_Category__c = 'TN_Elite Club',
            Secondary_Customer_Type__c = 'Retailer',
            Approval_Status__c = 'Credit Dept. Approved',
            Email_ID__c = 'test@gmail.com',
            SAP_Customer_Code__c ='19810121'
            
            
        );
        insert acc;

        // Product
        Product__c prod = new Product__c(Name = 'Test Prod');
        insert prod;

        // Order (Primary)
        Order__c ordPrimary = new Order__c(
            OwnerId = u.Id,
            Order_Type__c = 'Primary Order',
            Account__c = acc.Id,
            Order_Date__c = Date.today()
        );
        insert ordPrimary;

        // Order Item
        Order_Item__c oi1 = new Order_Item__c(
            Order__c = ordPrimary.Id,
            Product__c = prod.Id,
            Total_Amount__c = 500
        );
        insert oi1;

        // Secondary Order
        Order__c ordSecondary = new Order__c(
            OwnerId = u.Id,
            Order_Type__c = 'Secondary Order',
            Account__c = acc.Id,
            Order_Date__c = Date.today()
        );
        insert ordSecondary;

        Order_Item__c oi2 = new Order_Item__c(
            Order__c = ordSecondary.Id,
            Product__c = prod.Id,
            Total_Amount__c = 1000
        );
        insert oi2;

        // Collection Item
        Collection_Item__c coll = new Collection_Item__c(
            OwnerId = u.Id,
            Amount_Received__c = 300,
            Mode_of_Payment__c = 'Cash'
        );
        insert coll;

        // Order fulfilment
        ordPrimary.Orderfulfilment_Date__c = Date.today();
        update ordPrimary;

        Order_Item__c oi3 = new Order_Item__c(
            Order__c = ordPrimary.Id,
            Product__c = prod.Id
        );
        insert oi3;

        // PJP Item
        Calendar_beat__c pjp = new Calendar_beat__c(OwnerId = u.Id);
        insert pjp;
        
        Child_beat__c cb = new Child_beat__c();
        cb.Active__c = true;
        cb.Beat_type__c ='Secondary';
        //cb.Primary_Customer__c = acc.Id;
        //cb.Sub_Stockist__c = acc.id;
        insert cb;

        PJP_Item__c pjpItem = new PJP_Item__c(
            PJP__c = pjp.Id,
            Date__c = Date.today().addDays(1),
            Beat__c = cb.Id
        );
        insert pjpItem;
    }

    @isTest
    static void testControllerWithData() {
        User u = [SELECT Id FROM User WHERE Alias = 'tuser' LIMIT 1];

        Test.startTest();
        ApexPages.currentPage().getParameters().put('id', u.Id);
        ApexPages.StandardController sc = new ApexPages.StandardController(new Daily_Log__c());
        EODReportPdfController ctrl = new EODReportPdfController(sc);
        Test.stopTest();

        // Assertions
     
    }

    @isTest
    static void testControllerWithoutData() {
        User u = [SELECT Id FROM User WHERE Alias = 'tuser' LIMIT 1];
		Daily_Log__c dl = [select id from Daily_Log__c limit 1];
        Test.startTest();
        ApexPages.currentPage().getParameters().put('id', u.Id);
        ApexPages.StandardController sc = new ApexPages.StandardController(new Daily_Log__c());
        EODReportPdfController ctrl = new EODReportPdfController(sc);
        System.enqueueJob(new EODReportQueueableMail(dl.Id));
        EODReportBatch ed = new EODReportBatch();
        database.executeBatch(ed,1);
        
        EODReportBatchScheduler scheduler = new EODReportBatchScheduler();
        String jobId = System.schedule('DailyLogNotificationBatchJob', '0 0 0 * * ?', scheduler);

        Test.stopTest();

    }
}