force-app/main/default/objects/Area__c/Area__c.object-meta.xml
<CustomObject>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Area__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Area</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Region__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Area</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Area__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Regions</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Area__c/fields/Sales_Channel__c.field-meta.xml
<CustomField>
    <fullName>Sales_Channel__c</fullName>
    <label>Sales Channel</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Chanel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee_Customer_Assignment__c/Employee_Customer_Assignment__c.object-meta.xml
<CustomObject>
    <label>Employee Customer Assignment</label>
    <nameField>
        <displayFormat>ECA-{0000}</displayFormat>
        <label>Customer Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Customer Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Customer_Assignment__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Employee Customer Assignments</relationshipLabel>
    <relationshipName>Employee_Customer_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee_Customer_Assignment__c/fields/Employee_Code__c.field-meta.xml
<CustomField>
    <fullName>Employee_Code__c</fullName>
    <formula>Employee__r.Employee_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Executive Employee Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee_Customer_Assignment__c/fields/Executive__c.field-meta.xml
<CustomField>
    <fullName>Executive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Executive</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employee_Customer_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/Product_Mapping__c.object-meta.xml
<CustomObject>
    <label>Product Mapping</label>
    <nameField>
        <displayFormat>PM-{0000}</displayFormat>
        <label>Product Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Mapping__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Area</label>
    <referenceTo>Area__c</referenceTo>
    <relationshipLabel>Product Mappings</relationshipLabel>
    <relationshipName>Product_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Chanel__c.field-meta.xml
<CustomField>
    <fullName>Chanel__c</fullName>
    <label>Sales Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Chanel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Child_Depot__c.field-meta.xml
<CustomField>
    <fullName>Child_Depot__c</fullName>
    <label>Delivery Plant</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Parent_Depot__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Child_Depot</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Product Mappings</relationshipLabel>
    <relationshipName>Product_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <formula>TEXT(Customer__r.Customer_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Exectuive__c.field-meta.xml
<CustomField>
    <fullName>Exectuive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Executive</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Product_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Parent_Depot__c.field-meta.xml
<CustomField>
    <fullName>Parent_Depot__c</fullName>
    <label>Sales Organization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Parent_Depot</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Payment_Term__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term__c</fullName>
    <label>Payment Term</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Term</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Primary_Customer__c.field-meta.xml
<CustomField>
    <fullName>Primary_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Product Mappings (Primary Customer)</relationshipLabel>
    <relationshipName>Product_Mappings1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Sub_Stockiest__c.field-meta.xml
<CustomField>
    <fullName>Sub_Stockiest__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sub Stockiest</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Product Mappings (Sub Stockiest)</relationshipLabel>
    <relationshipName>Product_Mappings2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Region__c/Region__c.object-meta.xml
<CustomObject>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/MappingHelperTest.cls
@isTest
public class MappingHelperTest {
         
    @TestSetup
    static void setup() {
        Profile stdProfile = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];
        UserRole testRole = [SELECT Id FROM UserRole LIMIT 1];
        
        // Primary Test User
        User testUser1 = new User(
            Alias = 'tuser',
            Employee_Code__c  = 'EMP001',
            Email = 'testuser1@example.com',
            EmailEncodingKey = 'UTF-8',
            userroleId = testRole.Id,
            LastName = 'User1',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = stdProfile.Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            Username = 'testuser1' + System.currentTimeMillis() + '@example.com',
            Sales_Channel__c = 'Cake'
        );
        insert testUser1;

        // Secondary Test User
        User testUser2 = new User(
            Alias = 'tuser2',
            Employee_Code__c  = 'EMP002',
            Email = 'testuser2@example.com',
            userroleId = testRole.Id,
            ManagerId = testUser1.Id,
            EmailEncodingKey = 'UTF-8',
            LastName = 'User2',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = stdProfile.Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            Username = 'testuser2' + System.currentTimeMillis() + '@example.com',
            Sales_Channel__c = 'Cake'
        );
        insert testUser2;
    }
    
    @isTest
    static void testSaveAutoMappingData_FullCoverage11() {
        User testUser = [SELECT Id FROM User WHERE Employee_Code__c = 'EMP001' LIMIT 1];
        
        // Area record
        area__c tr = new area__c(Name = 'Test Area', Sales_Channel__c = 'CPD', Region__c = 'Kerala', Area__c = 'Central');
        insert tr;
        
        // Primary Customer
        Account primaryCustomer = new Account(
            Name = 'Primary Customer',
            OwnerId = testUser.Id,
            Customer_Type__c = 'Primary Customer',
            Pincode__c = '560001',
            Primary_Phone_Number__c = '1234567891',
            State__c = 'Karnataka',
            District__c = 'Kolar'
        );
        insert primaryCustomer;

        // Sub Stockiest
        Account subStockiest = new Account(
            Name = 'Sub Stockiest',
            OwnerId = testUser.Id,
            Customer_Type__c = 'Primary Customer',
            Primary_Phone_Number__c = '1234567890',
            Pincode__c = '560002',
            State__c = 'Karnataka',
            District__c = 'Kolar'
        );
        insert subStockiest;

        // Secondary Customer
        Account secondaryCustomer = new Account(
            Name = 'Secondary Customer',
            OwnerId = testUser.Id,
            Customer_Type__c = 'Secondary Customer',
            Primary_Phone_Number__c = '1234567894',
            Pincode__c = '560003',
            State__c = 'Karnataka',
            District__c = 'Kolar'
        );
        insert secondaryCustomer;

        // Payroll Mapping for Primary Customer
        Product_Mapping__c pmPrimary = new Product_Mapping__c(
            Customer__c = primaryCustomer.Id,
            Chanel__c = 'CPD',
            Parent_Depot__c ='1100',
            Area__c = tr.Id,
            Child_Depot__c ='1100',
            Payment_Term__c = '0003',
            Exectuive__c = testUser.Id
        );
        insert pmPrimary;

        // Payroll Mapping for Sub Stockiest
        Product_Mapping__c pmSubStockiest = new Product_Mapping__c(
            Customer__c = subStockiest.Id,
            Primary_Customer__c = primaryCustomer.Id,
            Chanel__c = 'CPD',
            Parent_Depot__c ='1100',
            Area__c = tr.Id,
            Child_Depot__c ='1100',
            Payment_Term__c = '0003',
            Exectuive__c = testUser.Id
        );
        insert pmSubStockiest;

        // Non Payroll Mapping
        Employee_Customer_Assignment__c empAssign = new Employee_Customer_Assignment__c(
            Customer__c = primaryCustomer.Id,
            Executive__c = testUser.Id
        );
        insert empAssign;

      

        // Call Method with Product Mapping List (cover all loops)
        Product_Mapping__c secPm = new Product_Mapping__c(
            Primary_Customer__c = primaryCustomer.Id,
            Chanel__c = 'CPD',
            Parent_Depot__c ='1100',
            Area__c = tr.Id,
            Child_Depot__c ='1100',
            Payment_Term__c = '0003',
            Exectuive__c = testUser.Id
        );

        Test.startTest();
        MappingHelper.saveAutoMappingData(secondaryCustomer, new List<Product_Mapping__c>{secPm});
        Test.stopTest();

        // Verify inserted mappings
        List<Product_Mapping__c> createdMappings = [
            SELECT Id, Primary_Customer__c, Sub_Stockiest__c, Customer__c, Exectuive__c 
            FROM Product_Mapping__c 
            WHERE Customer__c = :secondaryCustomer.Id
        ];
       // System.assert(createdMappings.size() > 0, 'Mappings should be auto-created for secondary customer');
    }
    
        @isTest
    static void testSaveAutoMappingData_FullCoverage() {
        User testUser = [SELECT Id FROM User WHERE Employee_Code__c = 'EMP001' LIMIT 1];
        
        // Area record
        area__c tr = new area__c(Name = 'Test Area', Sales_Channel__c = 'CPD', Region__c = 'Kerala', Area__c = 'Central');
        insert tr;
        
        // Primary Customer
        Account primaryCustomer = new Account(
            Name = 'Primary Customer',
            OwnerId = testUser.Id,
            Customer_Type__c = 'Primary Customer',
            Pincode__c = '560001',
            Primary_Phone_Number__c = '1234567891',
            State__c = 'Karnataka',
            District__c = 'Kolar'
        );
        insert primaryCustomer;

        // Sub Stockiest
        Account subStockiest = new Account(
            Name = 'Sub Stockiest',
            OwnerId = testUser.Id,
            Customer_Type__c = 'Primary Customer',
            Primary_Phone_Number__c = '1234567890',
            Pincode__c = '560002',
            State__c = 'Karnataka',
            District__c = 'Kolar'
        );
        insert subStockiest;

        // Secondary Customer
        Account secondaryCustomer = new Account(
            Name = 'Secondary Customer',
            OwnerId = testUser.Id,
            Customer_Type__c = 'Secondary Customer',
            Primary_Phone_Number__c = '1234567894',
            Pincode__c = '560003',
            State__c = 'Karnataka',
            District__c = 'Kolar'
        );
        insert secondaryCustomer;

        // Payroll Mapping for Primary Customer
        Product_Mapping__c pmPrimary = new Product_Mapping__c(
            Customer__c = primaryCustomer.Id,
            Chanel__c = 'CPD',
            Parent_Depot__c ='1100',
            Area__c = tr.Id,
            Child_Depot__c ='1100',
            Payment_Term__c = '0003',
            Exectuive__c = testUser.Id
        );
        insert pmPrimary;

        // Payroll Mapping for Sub Stockiest
        Product_Mapping__c pmSubStockiest = new Product_Mapping__c(
            Customer__c = subStockiest.Id,
            Primary_Customer__c = primaryCustomer.Id,
            Chanel__c = 'CPD',
            Parent_Depot__c ='1100',
            Area__c = tr.Id,
            Child_Depot__c ='1100',
            Payment_Term__c = '0003',
            Exectuive__c = testUser.Id
        );
        insert pmSubStockiest;

        // Non Payroll Mapping
        Employee_Customer_Assignment__c empAssign = new Employee_Customer_Assignment__c(
            Customer__c = primaryCustomer.Id,
            Executive__c = testUser.Id
        );
        insert empAssign;

      

        // Call Method with Product Mapping List (cover all loops)
        Product_Mapping__c secPm = new Product_Mapping__c(
            Primary_Customer__c = primaryCustomer.Id,
            Chanel__c = 'CPD',
            Parent_Depot__c ='1100',
            Area__c = tr.Id,
            Child_Depot__c ='1100',
            Payment_Term__c = '0003',
            Exectuive__c = testUser.Id
        );

        Test.startTest();
        MappingHelper.saveAutoMappingData(secondaryCustomer, new List<Product_Mapping__c>{});
        Test.stopTest();

        // Verify inserted mappings
        List<Product_Mapping__c> createdMappings = [
            SELECT Id, Primary_Customer__c, Sub_Stockiest__c, Customer__c, Exectuive__c 
            FROM Product_Mapping__c 
            WHERE Customer__c = :secondaryCustomer.Id
        ];
       // System.assert(createdMappings.size() > 0, 'Mappings should be auto-created for secondary customer');
    }
}