force-app/main/default/objects/Area__c/Area__c.object-meta.xml
<CustomObject>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Area__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Area</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Region__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Area</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Division__c/Division__c.object-meta.xml
<CustomObject>
    <label>Division</label>
    <nameField>
        <label>Division Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Divisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Customer_Assignment__c/Employee_Customer_Assignment__c.object-meta.xml
<CustomObject>
    <label>Employee Customer Assignment</label>
    <nameField>
        <displayFormat>ECA-{0000}</displayFormat>
        <label>Customer Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Customer Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Customer_Assignment__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Employee Customer Assignments</relationshipLabel>
    <relationshipName>Employee_Customer_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee_Customer_Assignment__c/fields/Executive__c.field-meta.xml
<CustomField>
    <fullName>Executive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Executive</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employee_Customer_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/Product_Mapping__c.object-meta.xml
<CustomObject>
    <label>Product Mapping</label>
    <nameField>
        <displayFormat>PM-{0000}</displayFormat>
        <label>Product Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Mapping__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Area</label>
    <referenceTo>Area__c</referenceTo>
    <relationshipLabel>Product Mappings</relationshipLabel>
    <relationshipName>Product_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Chanel__c.field-meta.xml
<CustomField>
    <fullName>Chanel__c</fullName>
    <label>Sales Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Chanel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Child_Depot__c.field-meta.xml
<CustomField>
    <fullName>Child_Depot__c</fullName>
    <label>Delivery Plant</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Parent_Depot__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Child_Depot</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Cloned_From_Employee_Replacement__c.field-meta.xml
<CustomField>
    <fullName>Cloned_From_Employee_Replacement__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cloned From Employee Replacement</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Credit_Description__c.field-meta.xml
<CustomField>
    <fullName>Credit_Description__c</fullName>
    <label>Credit Description</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Payment_Term__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Credit_Description</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Product Mappings</relationshipLabel>
    <relationshipName>Product_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <formula>TEXT(Customer__r.Customer_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Distribution_Channel__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Channel__c</fullName>
    <label>Distribution Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Distribution_Channel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Exectuive__c.field-meta.xml
<CustomField>
    <fullName>Exectuive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Executive</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Product_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Inco_Terms__c.field-meta.xml
<CustomField>
    <fullName>Inco_Terms__c</fullName>
    <label>Inco Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Inco_Terms</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Order_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Parent_Depot__c.field-meta.xml
<CustomField>
    <fullName>Parent_Depot__c</fullName>
    <label>Sales Organization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Parent_Depot</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Payment_Term__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term__c</fullName>
    <label>Payment Term</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Term</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/PDP_Day__c.field-meta.xml
<CustomField>
    <fullName>PDP_Day__c</fullName>
    <label>PDP Day</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PDP_Day</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/PDP_Name__c.field-meta.xml
<CustomField>
    <fullName>PDP_Name__c</fullName>
    <label>PDP Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Primary_Customer__c.field-meta.xml
<CustomField>
    <fullName>Primary_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Product Mappings (Primary Customer)</relationshipLabel>
    <relationshipName>Product_Mappings1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Sales_Office__c.field-meta.xml
<CustomField>
    <fullName>Sales_Office__c</fullName>
    <label>Sales Office</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Office</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Secondary_Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Customer_Type__c</fullName>
    <formula>TEXT(Customer__r.Secondary_Customer_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Secondary Customer Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Sub_Stockiest__c.field-meta.xml
<CustomField>
    <fullName>Sub_Stockiest__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sub Stockiest</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Product Mappings (Sub Stockiest)</relationshipLabel>
    <relationshipName>Product_Mappings2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EmployeeProductMappingCloneBatch.cls
public class EmployeeProductMappingCloneBatch 
    implements Database.Batchable<sObject>, Database.Stateful {

    Map<String, String> oldToNewUserMap;

    public EmployeeProductMappingCloneBatch(Map<String, String> oldToNewUserMap) {
        this.oldToNewUserMap = oldToNewUserMap;
    }

    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([
            SELECT Id, Exectuive__c, Primary_Customer__c, Sub_Stockiest__c, Customer__c, Chanel__c,
                   Area__c, PDP_Name__c, PDP_Day__c, Parent_Depot__c, Child_Depot__c, Payment_Term__c, 
                   Credit_Description__c, Inco_Terms__c, Order_Type__c, Distribution_Channel__c, 
                   Sales_Office__c, Division__c, Customer_Type__c, Secondary_Customer_Type__c
            FROM Product_Mapping__c
            WHERE Exectuive__c IN :oldToNewUserMap.keySet()
        ]);
    }

    public void execute(Database.BatchableContext bc, List<Product_Mapping__c> oldMappings) {

        List<Product_Mapping__c> clonedPrimary = new List<Product_Mapping__c>();
        List<Product_Mapping__c> clonedSubstockiest = new List<Product_Mapping__c>();
        List<Product_Mapping__c> clonedSecondary = new List<Product_Mapping__c>();

        // Clone Product Mappings
        for (Product_Mapping__c oldMap : oldMappings) {

            String newExec = oldToNewUserMap.get(oldMap.Exectuive__c);
            if (String.isBlank(newExec)) continue;

            Product_Mapping__c newMap = new Product_Mapping__c();
            
            // Clone field values
            newMap.Exectuive__c = newExec;
            newMap.Primary_Customer__c = oldMap.Primary_Customer__c;
            newMap.Sub_Stockiest__c = oldMap.Sub_Stockiest__c;
            newMap.Customer__c = oldMap.Customer__c;
            newMap.Chanel__c = oldMap.Chanel__c;
            newMap.Area__c = oldMap.Area__c;
            newMap.PDP_Name__c = oldMap.PDP_Name__c;
            newMap.PDP_Day__c = oldMap.PDP_Day__c;
            newMap.Parent_Depot__c = oldMap.Parent_Depot__c;
            newMap.Child_Depot__c = oldMap.Child_Depot__c;
            newMap.Payment_Term__c = oldMap.Payment_Term__c;
            newMap.Credit_Description__c = oldMap.Credit_Description__c;
            newMap.Inco_Terms__c = oldMap.Inco_Terms__c;
            newMap.Order_Type__c = oldMap.Order_Type__c;
            newMap.Distribution_Channel__c = oldMap.Distribution_Channel__c;
            newMap.Sales_Office__c = oldMap.Sales_Office__c;
            newMap.Division__c = oldMap.Division__c;
            newMap.Cloned_From_Employee_Replacement__c = true;
            
            if (oldMap.Customer_Type__c == 'Primary Customer') {
                clonedPrimary.add(newMap);
            } else if (oldMap.Customer_Type__c == 'Secondary Customer' &&
                       oldMap.Secondary_Customer_Type__c == 'Sub Stockiest') {
                clonedSubstockiest.add(newMap);
            } else {
                clonedSecondary.add(newMap);
            }
        }

         
        
        if (!clonedPrimary.isEmpty()) database.insert(clonedPrimary,false);

        //  Clone DSM Customer Assignments in the SAME batch chunk
        List<Employee_Customer_Assignment__c> oldDSM =
            [SELECT Id, Executive__c, Customer__c
             FROM Employee_Customer_Assignment__c
             WHERE Executive__c IN :oldToNewUserMap.keySet()
             LIMIT 2000]; // Safe chunk

        List<Employee_Customer_Assignment__c> newDSM = new List<Employee_Customer_Assignment__c>();

        for (Employee_Customer_Assignment__c oldRow : oldDSM) {
            String newExec = oldToNewUserMap.get(oldRow.Executive__c);
            if (String.isBlank(newExec)) continue;

            Employee_Customer_Assignment__c newRow = new Employee_Customer_Assignment__c();
            newRow.Customer__c = oldRow.Customer__c;
            newRow.Executive__c = newExec;

            newDSM.add(newRow);
        }

        
        if (!newDSM.isEmpty()) database.insert(newDSM,false);
        
        if (!clonedSubstockiest.isEmpty()) database.insert(clonedSubstockiest,false);        
        if (!clonedSecondary.isEmpty()) database.insert(clonedSecondary,false);  

    }

    public void finish(Database.BatchableContext bc) {}
}