force-app/main/default/objects/Area__c/Area__c.object-meta.xml
<CustomObject>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Area__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Area</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Region__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Area</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Area__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Regions</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Area__c/fields/Sales_Channel__c.field-meta.xml
<CustomField>
    <fullName>Sales_Channel__c</fullName>
    <label>Sales Channel</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Chanel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Aadhar_Number__c.field-meta.xml
<CustomField>
    <fullName>Aadhar_Number__c</fullName>
    <label>Aadhar Number</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Employee_Approval_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Approver_ASM__c.field-meta.xml
<CustomField>
    <fullName>Approver_ASM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee Owner Approver 1</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employees6</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Approver_RSM__c.field-meta.xml
<CustomField>
    <fullName>Approver_RSM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee Owner Approver 2</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employees7</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Area</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <label>District</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>State__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>District</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Employee_Code__c.field-meta.xml
<CustomField>
    <fullName>Employee_Code__c</fullName>
    <externalId>true</externalId>
    <label>Employee Code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Employee_Owner_Approver_3_HR__c.field-meta.xml
<CustomField>
    <fullName>Employee_Owner_Approver_3_HR__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee Owner Approver 3 (HR)</label>
    <referenceTo>User</referenceTo>
    <relationshipName>EmployeeswSMc</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Is_User_Deactivated__c.field-meta.xml
<CustomField>
    <fullName>Is_User_Deactivated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is User Deactivated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/IsDataUpload__c.field-meta.xml
<CustomField>
    <fullName>IsDataUpload__c</fullName>
    <defaultValue>true</defaultValue>
    <label>IsDataUpload</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Mail_Id__c.field-meta.xml
<CustomField>
    <fullName>Mail_Id__c</fullName>
    <label>Mail Id</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <label>Permission Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Profile</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Regions</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Reporting_Manager__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reporting Manager</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>User.Id</field>
            <operation>notEqual</operation>
            <valueField>$Source.User__c</valueField>
        </filterItems>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Employees1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Sales_Channel__c.field-meta.xml
<CustomField>
    <fullName>Sales_Channel__c</fullName>
    <label>Sales Channel</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Chanel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Territory</label>
    <referenceTo>Area__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/User_Name__c.field-meta.xml
<CustomField>
    <fullName>User_Name__c</fullName>
    <label>Username</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Working_District__c.field-meta.xml
<CustomField>
    <fullName>Working_District__c</fullName>
    <label>District</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>District</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee_Customer_Assignment__c/Employee_Customer_Assignment__c.object-meta.xml
<CustomObject>
    <label>Employee Customer Assignment</label>
    <nameField>
        <displayFormat>ECA-{0000}</displayFormat>
        <label>Customer Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Customer Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Customer_Assignment__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Employee Customer Assignments</relationshipLabel>
    <relationshipName>Employee_Customer_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee_Customer_Assignment__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Employee Customer Assignments</relationshipLabel>
    <relationshipName>Employee_Customer_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee_Customer_Assignment__c/fields/Employee_Code__c.field-meta.xml
<CustomField>
    <fullName>Employee_Code__c</fullName>
    <formula>Employee__r.Employee_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Executive Employee Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/Product_Mapping__c.object-meta.xml
<CustomObject>
    <label>Product Mapping</label>
    <nameField>
        <displayFormat>PM-{0000}</displayFormat>
        <label>Product Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Mapping__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Area</label>
    <referenceTo>Area__c</referenceTo>
    <relationshipLabel>Product Mappings</relationshipLabel>
    <relationshipName>Product_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Chanel__c.field-meta.xml
<CustomField>
    <fullName>Chanel__c</fullName>
    <label>Sales Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Chanel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Child_Depot__c.field-meta.xml
<CustomField>
    <fullName>Child_Depot__c</fullName>
    <label>Delivery Plant</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Parent_Depot__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Child_Depot</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Product Mappings</relationshipLabel>
    <relationshipName>Product_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <formula>TEXT(Customer__r.Customer_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Product Mappings</relationshipLabel>
    <relationshipName>Product_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Exectuive__c.field-meta.xml
<CustomField>
    <fullName>Exectuive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Executive</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Product_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Parent_Depot__c.field-meta.xml
<CustomField>
    <fullName>Parent_Depot__c</fullName>
    <label>Sales Organization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Parent_Depot</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Payment_Term__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term__c</fullName>
    <label>Payment Term</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Term</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Secondary_Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Customer_Type__c</fullName>
    <formula>TEXT(Customer__r.Secondary_Customer_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Secondary Customer Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Role__c/fields/Role_Id__c.field-meta.xml
<CustomField>
    <fullName>Role_Id__c</fullName>
    <label>Role Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EmployeeTriggerHandlerTest.cls
@isTest
private class EmployeeTriggerHandlerTest {
    
    @TestSetup
    static void setupTestData() {
        // Setup object DML (Profiles, Users, Roles)
        Profile adminProfile = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
        Profile testProfile = [SELECT Id FROM Profile WHERE Name LIKE '%Admin%' LIMIT 1];
        
        User adminUser = new User(
            FirstName = 'Admin',
            LastName = 'User',
            Email = 'admin.user@test.com',
            Username = 'admin.useruser@test.com',
            Alias = 'admin',
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            ProfileId = adminProfile.Id,
            LanguageLocaleKey = 'en_US',
            Employee_Code__c = '994332'
        );
        insert adminUser;
        
        User managerUser = new User(
            FirstName = 'Manager',
            LastName = 'User',
            ManagerId = adminUser.Id,
            Email = 'manager.user@test.com',
            Username = 'manager.useruser@test.com',
            Alias = 'mgr',
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            ProfileId = testProfile.Id,
            LanguageLocaleKey = 'en_US',
            Employee_Code__c = '33456'
        );
        insert managerUser;
        
        UserRole testRole;
        System.runAs(adminUser) {
            testRole = new UserRole(Name = 'Test Role');
            insert testRole;
        }
        
        // Separate the rest into a new transaction
        Test.startTest();
        
        managerUser.UserRoleId = testRole.Id;
        update managerUser;
        
        
        
        // Update again after non-setup insert
        managerUser.Region__c = 'Ker_CPD';
        managerUser.Area__c = 'Central';
        managerUser.Working_District__c = 'Chittoor';
        update managerUser;
        
        Test.stopTest();
    }
    
    
    // Rest of the test methods remain the same...
    @isTest
    static void testBeforeInsert() {
        // Get test data
        
        area__c testTerritory111 = new area__c();
        testTerritory111.Name = 'test11121';
        testTerritory111.Sales_Channel__c = 'CPD';
        testTerritory111.Region__c =	'Kerala';
        testTerritory111.Area__c  = 'Central';
        insert testTerritory111;

        User managerUser = [SELECT Id FROM User WHERE Username = 'manager.useruser@test.com' LIMIT 1];
        Area__c testTerritory = [SELECT Id FROM Area__c LIMIT 1];
        UserRole testRole = [SELECT Id, Name FROM UserRole WHERE Name = 'Test Role' LIMIT 1];
        
        // Create test employee
        Employee__c emp = new Employee__c(
            Name = 'Test Employee',
            OwnerId = managerUser.Id,
            Reporting_Manager__c = managerUser.Id,
            Role__c = testRole.Name,
            Territory__c = testTerritory.Id,
            IsDataUpload__c = true,
            Mail_Id__c = 'test@gmail.com', Aadhar_Number__c = '119977663390', Profile__c = 'ASM', Sales_Channel__c = 'TN', User_Name__c = 'my@tstasm.com'
        );
        
        Test.startTest();
        insert emp;
        try{
            delete emp;
        }
        catch(exception e)
        {}
        
        Test.stopTest();
        
        // Verify results
        Employee__c insertedEmp = [SELECT Id, Role_Id__c, Region__c, Area__c, Working_District__c, 
                                   Approver_ASM__c, Approver_RSM__c, Employee_Owner_Approver_3_HR__c 
                                   FROM Employee__c WHERE Id = :emp.Id];
        
    }
    
    @isTest
    static void testBeforeUpdate() {
        Profile testProfile = [SELECT Id, Name FROM Profile WHERE Name LIKE '%Admin%' LIMIT 1];
        
        User testUser = new User(
            FirstName = 'Test',
            LastName = 'User',
            Email = 'test.user@test.com',
            Username = 'test.useruser2@test.com',
            Alias = 'test',
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            ProfileId = testProfile.Id,
            LanguageLocaleKey = 'en_US',
            Employee_Code__c = '664453'
        );
        insert testUser;
        

        
        area__c testTerritory = new area__c();
        testTerritory.Name = 'test11121';
        testTerritory.Sales_Channel__c = 'CPD';
        testTerritory.Region__c =	'Kerala';
        testTerritory.Area__c  = 'Central';
        insert testTerritory;

        
        
        
        UserRole testRole = [SELECT Id, Name FROM UserRole LIMIT 1];
        
        // Create test employee
        Employee__c emp = new Employee__c(
            Name = 'Test Employee',
            OwnerId = testUser.Id,
            Reporting_Manager__c = testUser.Id,
            Role__c = 'Old Role',
            IsDataUpload__c = true,
            Mail_Id__c = 'test@gmail.com', Aadhar_Number__c = '119977663390', Profile__c = 'ASM', Sales_Channel__c = 'TN', User_Name__c = 'my@tstasm.com'
            
        );
        insert emp;
        
        // Update employee
        emp.Role__c = testRole.Name;
        emp.Territory__c = testTerritory.Id;
        
        Test.startTest();
        update emp;
        Test.stopTest();
        
        // Verify results
        Employee__c updatedEmp = [SELECT Id, Role_Id__c, Region__c, Area__c, Working_District__c 
                                  FROM Employee__c WHERE Id = :emp.Id];
        
        //System.assertEquals(testRole.Id, updatedEmp.Role_Id__c, 'Role Id should be updated');
        //System.assertEquals('Test Region', updatedEmp.Region__c, 'Region should be mapped from territory');
        //System.assertEquals('Test Area', updatedEmp.Area__c, 'Area should be mapped from territory');
        //System.assertEquals('Test District', updatedEmp.Working_District__c, 'District should be mapped from territory');
    }
    
    @isTest
    static void testBeforeUpdat1e() {
        Profile testProfile = [SELECT Id, Name FROM Profile WHERE Name LIKE '%Admin%' LIMIT 1];
        
        User testUser = new User(
            FirstName = 'Test',
            LastName = 'User',
            Email = 'test.user@test.com',
            Username = 'test.useruser2@test.com',
            Alias = 'test',
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            ProfileId = testProfile.Id,
            LanguageLocaleKey = 'en_US',
            Employee_Code__c = '664453'
        );
        insert testUser;
        

        
        area__c testTerritory = new area__c();
        testTerritory.Name = 'test11121';
        testTerritory.Sales_Channel__c = 'CPD';
        testTerritory.Region__c =	'Kerala';
        testTerritory.Area__c  = 'Central';
        insert testTerritory;

        
        
        
        UserRole testRole = [SELECT Id, Name FROM UserRole LIMIT 1];
        
        // Create test employee
        Employee__c emp = new Employee__c(
            Name = 'Test Employee',
            OwnerId = testUser.Id,
            Reporting_Manager__c = testUser.Id,
            Role__c = 'Old Role',
            IsDataUpload__c = true,
            Mail_Id__c = 'test@gmail.com', Aadhar_Number__c = '119977663390', Profile__c = 'ASM', Sales_Channel__c = 'TN', User_Name__c = 'my@tstasm.com'
            
        );
        insert emp;
        
        // Update employee
        emp.Name = 'Suresh';
        emp.Territory__c = testTerritory.Id;
        
        Test.startTest();
        update emp;
        Test.stopTest();
        
        // Verify results
        Employee__c updatedEmp = [SELECT Id, Role_Id__c, Region__c, Area__c, Working_District__c 
                                  FROM Employee__c WHERE Id = :emp.Id];
        
        //System.assertEquals(testRole.Id, updatedEmp.Role_Id__c, 'Role Id should be updated');
        //System.assertEquals('Test Region', updatedEmp.Region__c, 'Region should be mapped from territory');
        //System.assertEquals('Test Area', updatedEmp.Area__c, 'Area should be mapped from territory');
        //System.assertEquals('Test District', updatedEmp.Working_District__c, 'District should be mapped from territory');
    }
    
    
    
    @isTest
    static void testAfterUpdateHRApproval() {
        // Get admin user
        User adminUser = [SELECT Id FROM User WHERE Username = 'admin.useruser@test.com' LIMIT 1];
        
        // Create test employee
        Employee__c emp = new Employee__c(
            Name = 'Test Employee',
            Approval_Status__c = 'Pending',
            Employee_Owner_Approver_3_HR__c = adminUser.Id,
            Reporting_Manager__c = userInfo.getUserId(),
            Mail_Id__c = 'test@gmail.com', Aadhar_Number__c = '119977663390', Profile__c = 'ASM', Sales_Channel__c = 'TN', User_Name__c = 'my@tstasm.com'
            
        );
        insert emp;
        
        // Update approval status
        emp.Approval_Status__c = 'HR Approved';
        
        Test.startTest();
        update emp;
        Test.stopTest();
        
        // Verify notification was sent (would need to query platform events or use a mock)
        // This is just a placeholder assertion
        //System.assertEquals('HR Approved', [SELECT Approval_Status__c FROM Employee__c WHERE Id = :emp.Id].Approval_Status__c);
    }
    
    @isTest
    static void testAfterUpdateActivation() {
        // Get test data
        User managerUser = [SELECT Id FROM User WHERE Username = 'manager.useruser@test.com' LIMIT 1];
        
        // Create test user
        User testUser = new User(
            FirstName = 'Test',
            LastName = 'User',
            Email = 'test.useruser@test.com',
            Username = 'test.user1234@test.com',
            Alias = 'test',
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            ProfileId = [SELECT Id FROM Profile WHERE Name LIKE '%Admin%' LIMIT 1].Id,
            LanguageLocaleKey = 'en_US',
            Employee_Code__c= '001123'
        );
        insert testUser;
        
        // Create test employee
        Employee__c emp = new Employee__c(
            Name = 'Test Employee',
            User__c = testUser.Id,
            Is_Active__c = false,
            Is_User_Deactivated__c = true,
            Employee_Owner_Approver_3_HR__c = managerUser.Id,
            Reporting_Manager__c = UserInfo.getUserId(),
            Mail_Id__c = 'test@gmail.com',
            Aadhar_Number__c = '119977663390',
            Profile__c = 'ASM',
            Sales_Channel__c = 'TN',
            User_Name__c = 'my@tstasm.com'
            
        );
        insert emp;
        
        // Create test account for sharing
        Account testAccount = new Account(Name = 'Test Account',City__c = 'Delhi',
                                          State__c = 'Delhi',
                                          District__c = 'New Delhi',
                                          Primary_Phone_Number__c = '9900099999',Pincode__c = '774456');
        insert testAccount;
        
        // Create product mapping
        Product_Mapping__c pm = new Product_Mapping__c(
            Customer__c = testAccount.Id,
            Exectuive__c = testUser.Id
        );
        insert pm;
        
        // Activate employee
        emp.Is_Active__c = true;
        
        Test.startTest();
        update emp;
        Test.stopTest();
        
        // Verify employee is active
        Employee__c updatedEmp = [SELECT Is_Active__c FROM Employee__c WHERE Id = :emp.Id];
        //System.assertEquals(true, updatedEmp.Is_Active__c, 'Employee should be active');
        
        // Verify product mapping was updated (would need to query in real test)
        // Verify sharing was recreated (would need to query AccountShare in real test)
    }
    

    
    
    @isTest
    static void testBeforeInsert11() {
        
        
        user testUser = [select Id,Name from User where Employee_Code__C = '994332' limit 1];   
        
        user testUser2 = [select Id,Name from User where Employee_Code__C = '33456' limit 1];   
        Employee__c emp = new Employee__c(
            Name = 'Test Employee',
            OwnerId = testUser.Id,
            Reporting_Manager__c = testUser2.Id,
            user__C = testUser.Id,
            IsDataUpload__c = true,
            Mail_Id__c = 'test@gmail.com', Aadhar_Number__c = '119977663390', Profile__c = 'ASM', Sales_Channel__c = 'TN', User_Name__c = 'my@tstasm.com'
        );
        insert emp;
        
        Account acc = new Account(
            Name = 'Primary Customer',
            OwnerId = testUser.Id,
            Customer_Type__c = 'Secondary Customer',
            Pincode__c = '123456',
            Primary_Phone_Number__c = '9876543210',
            State__c = 'Karnataka',
            District__c = 'Kolar'
        );
        insert acc;
        
        Account acc1 = new Account(
            Name = 'Primary Customer',
            OwnerId = testUser.Id,
            Customer_Type__c = 'Primary Customer',
            Pincode__c = '123456',
            Primary_Phone_Number__c = '9876543210',
            State__c = 'Karnataka',
            District__c = 'Kolar'
        );
        insert acc1;
        
        Account acc2 = new Account(
            Name = 'Primary Customer',
            OwnerId = testUser.Id,
            Customer_Type__c = 'Primary Customer',
            Pincode__c = '123456',
            Primary_Phone_Number__c = '2276543210',
            State__c = 'Karnataka',
            District__c = 'Kolar'
        );
        insert acc2;
        
        
        // Create test accounts
        Account newAcc = new Account(Name = 'Secondary Customer',
                                     Customer_Type__c = 'Secondary Customer',
                                     Customer_Status__c = 'Active',
                                     Secondary_Customer_Type__c = 'Sub Stockiest',
                                     SAP_Customer_Code__c = 'SAP0012233',
                                     City__c = 'Delhi',
                                     State__c = 'Delhi',
                                     District__c = 'New Delhi',
                                     Pincode__c = '110001',
                                     Primary_Phone_Number__c = '1234567890');
        insert newAcc;
        
        Profile p = [SELECT Id, Name FROM Profile WHERE Name = 'Standard User' LIMIT 1];
        UserRole ur = [SELECT Id FROM UserRole LIMIT 1];
        
        area__c tr = new area__c();
        tr.Name = 'test';
        tr.Sales_Channel__c = 'CPD';
        tr.Region__c =	'Kerala';
        tr.Area__c  = 'Central';
        insert tr;
        
        Product_Mapping__c pm3 = new   Product_Mapping__c();
        pm3.Customer__c = acc1.Id;
        pm3.Chanel__c = 'CPD';
        pm3.Parent_Depot__c ='1100';
        pm3.Child_Depot__c ='1100';
        pm3.Payment_Term__c = '0003';
        pm3.Area__c = tr.Id;
        pm3.Exectuive__c = testUser.Id;
        insert pm3;
        
        Product_Mapping__c pm4 = new   Product_Mapping__c();
        pm4.Customer__c = acc2.Id;
        pm4.Chanel__c = 'CPD';
        pm4.Parent_Depot__c ='1100';
        pm4.Area__c = tr.Id;
        pm4.Child_Depot__c ='1100';
        pm4.Payment_Term__c = '0003';
        pm4.Exectuive__c = testUser.Id;
        insert pm4;
        
        
        
         
        // Activate employee and assign user
        emp.Is_Active__c = true;
        emp.User__c = testUser.Id;
        emp.Mail_Id__c = 'testing@gmail.com';
        emp.User_Name__c = 'testing76747@gmail.com';
        emp.Primary_Phone_Number__c = '7733440091';
        emp.Aadhar_Number__c = '771100997712';
        emp.Employee_Code__c = '54546637383';
        emp.Designation__c = 'ASM.TSE';
        emp.Payroll__c = 'Yes';
        emp.Payroll_Type__c = 'YRFM';
        emp.Contract_Type__c = 'Distributor';
        emp.Band__c = 'M1';
        update emp;
        
        // Call the method directly for testing
        Map<Id, Id> activatedEmployees = new Map<Id, Id>();
        activatedEmployees.put(emp.Id, testUser.Id);
        EmployeeTriggerHandler.updateExecutiveOnActivation(activatedEmployees);
        
        
        
    }

    @isTest
    static void testReshareCustomerAccess() {
        // Create test user
        User testUser = new User(
            FirstName = 'Test',
            LastName = 'User',
            Email = 'test.user@test.com',
            Username = 'test.useruseruser@test.com',
            Alias = 'test',
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            ProfileId = [SELECT Id FROM Profile WHERE Name LIKE '%Admin%' LIMIT 1].Id,
            LanguageLocaleKey = 'en_US',
            Employee_code__c= '99001'
        );
        insert testUser;
        
        // Create test account
        Account testAccount = new Account(Name = 'Test Account',City__c = 'Delhi',
                                          State__c = 'Delhi',
                                          District__c = 'New Delhi',
                                          Primary_Phone_Number__c = '9901099999',Pincode__c = '774456');
        insert testAccount;
        
        // Create product mapping
        Product_Mapping__c pm = new Product_Mapping__c(
            Customer__c = testAccount.Id,
            Exectuive__c = testUser.Id
        );
        insert pm;
        
        // Create employee customer assignment
        Employee_Customer_Assignment__c eca = new Employee_Customer_Assignment__c(
            Customer__c = testAccount.Id,
            Executive__c = testUser.Id
        );
        insert eca;
        
        // Delete existing shares (simulate deactivation)
        delete [SELECT Id FROM AccountShare WHERE UserOrGroupId = :testUser.Id AND AccountId = :testAccount.Id];
        
        Test.startTest();
        EmployeeTriggerHandler.reshareCustomerAccess(new Set<Id>{testUser.Id});
        Test.stopTest();
        
        // Verify shares were recreated
        List<AccountShare> shares = [SELECT Id FROM AccountShare WHERE UserOrGroupId = :testUser.Id AND AccountId = :testAccount.Id];
        //System.assert(!shares.isEmpty(), 'Account shares should be recreated');
    }
}