force-app/main/default/objects/Area__c/Area__c.object-meta.xml
<CustomObject>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Area__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Area</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Region__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Area</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Area__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Regions</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Area__c/fields/Sales_Channel__c.field-meta.xml
<CustomField>
    <fullName>Sales_Channel__c</fullName>
    <label>Sales Channel</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Chanel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Aadhar_Number__c.field-meta.xml
<CustomField>
    <fullName>Aadhar_Number__c</fullName>
    <label>Aadhar Number</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Area</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <label>District</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>State__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>District</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Employee_Code__c.field-meta.xml
<CustomField>
    <fullName>Employee_Code__c</fullName>
    <externalId>true</externalId>
    <label>Employee Code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Employee__c/fields/IsDataUpload__c.field-meta.xml
<CustomField>
    <fullName>IsDataUpload__c</fullName>
    <defaultValue>true</defaultValue>
    <label>IsDataUpload</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Mail_Id__c.field-meta.xml
<CustomField>
    <fullName>Mail_Id__c</fullName>
    <label>Mail Id</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <label>Permission Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Profile</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Regions</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Reporting_Manager__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reporting Manager</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>User.Id</field>
            <operation>notEqual</operation>
            <valueField>$Source.User__c</valueField>
        </filterItems>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Employees1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Sales_Channel__c.field-meta.xml
<CustomField>
    <fullName>Sales_Channel__c</fullName>
    <label>Sales Channel</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Chanel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/fields/User_Name__c.field-meta.xml
<CustomField>
    <fullName>User_Name__c</fullName>
    <label>Username</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Employee_Customer_Assignment__c/Employee_Customer_Assignment__c.object-meta.xml
<CustomObject>
    <label>Employee Customer Assignment</label>
    <nameField>
        <displayFormat>ECA-{0000}</displayFormat>
        <label>Customer Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Customer Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Customer_Assignment__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Employee Customer Assignments</relationshipLabel>
    <relationshipName>Employee_Customer_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee_Customer_Assignment__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Employee Customer Assignments</relationshipLabel>
    <relationshipName>Employee_Customer_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee_Customer_Assignment__c/fields/Employee_Code__c.field-meta.xml
<CustomField>
    <fullName>Employee_Code__c</fullName>
    <formula>Employee__r.Employee_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Executive Employee Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee_Customer_Assignment__c/fields/Executive__c.field-meta.xml
<CustomField>
    <fullName>Executive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Executive</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employee_Customer_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/Product_Mapping__c.object-meta.xml
<CustomObject>
    <label>Product Mapping</label>
    <nameField>
        <displayFormat>PM-{0000}</displayFormat>
        <label>Product Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Mapping__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Area</label>
    <referenceTo>Area__c</referenceTo>
    <relationshipLabel>Product Mappings</relationshipLabel>
    <relationshipName>Product_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Chanel__c.field-meta.xml
<CustomField>
    <fullName>Chanel__c</fullName>
    <label>Sales Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Chanel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Child_Depot__c.field-meta.xml
<CustomField>
    <fullName>Child_Depot__c</fullName>
    <label>Delivery Plant</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Parent_Depot__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Child_Depot</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Product Mappings</relationshipLabel>
    <relationshipName>Product_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <formula>TEXT(Customer__r.Customer_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Product Mappings</relationshipLabel>
    <relationshipName>Product_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Exectuive__c.field-meta.xml
<CustomField>
    <fullName>Exectuive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Executive</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Product_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Parent_Depot__c.field-meta.xml
<CustomField>
    <fullName>Parent_Depot__c</fullName>
    <label>Sales Organization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Parent_Depot</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Payment_Term__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term__c</fullName>
    <label>Payment Term</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Term</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Primary_Customer__c.field-meta.xml
<CustomField>
    <fullName>Primary_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Product Mappings (Primary Customer)</relationshipLabel>
    <relationshipName>Product_Mappings1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Region__c/Region__c.object-meta.xml
<CustomObject>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/EmployeeCustomerAssignmentTriggerTest.cls
@isTest
public class EmployeeCustomerAssignmentTriggerTest {
    
    @TestSetup
    static void setup() {
        Profile adminProfile = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
        UserRole testRole = [SELECT Id FROM UserRole LIMIT 1];
        // Create test users
        User testUser1 = new User(
            Alias = 'tuser',
            Employee_Code__c  = '123212231',
            Email = 'testuser@example.com',
            EmailEncodingKey = 'UTF-8',
            userroleId = testRole.Id,
            LastName = 'Test',
            isActive=true,
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'TSE' LIMIT 1].Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            Username = 'testuser@example.com' + System.currentTimeMillis(),
            Sales_Channel__c = 'Cake'
        );
        insert testUser1;
        User testUser2 = new User(
            Alias = 'tuser12',
            Employee_Code__c  = '1232122343',
            Email = 'testuser@example.com',
            userroleId = testRole.Id,
            ManagerId = testUser1.Id,
            isActive=true,
            EmailEncodingKey = 'UTF-8',
            LastName = 'Test',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'TSE' LIMIT 1].Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            Username = 'testuser@example.com' + System.currentTimeMillis(),
            Sales_Channel__c = 'Cake'
        );
        insert testUser2 ;
        
        
        
    }
    
    @isTest
    static void testAfterInsert() {
        // Create test accounts
        Account acc1 = new Account(Name = 'Primary Customer 1',
                                   Customer_Type__c = 'Primary Customer',
                                   Customer_Status__c = 'Active',
                                   SAP_Customer_Code__c = 'SAP0012233',
                                   
                                   City__c = 'Delhi',
                                   State__c = 'Delhi',
                                   District__c = 'New Delhi',
                                   Pincode__c = '110001',
                                   Primary_Phone_Number__c = '1234567890');
        insert acc1;
        // Prepare test data
        User user = [SELECT Id FROM User WHERE LastName = 'Test' and isActive= true LIMIT 1];
        Employee_Customer_Assignment__c eca = new Employee_Customer_Assignment__c(
            Customer__c = acc1.Id,
            Executive__c = user.Id
        );
        
        Test.startTest();
        insert eca;
        Test.stopTest();
        
        
    }
    
    
    @isTest
    static void testAfterInsertBulk() {
        // Prepare bulk test data
        
        
        Account acc1 = new Account(Name = 'Primary Customer 1',
                                   Customer_Type__c = 'Primary Customer',
                                   Customer_Status__c = 'Active',
                                   SAP_Customer_Code__c = 'SAP0012ssa233',
                                   
                                   City__c = 'Delhi',
                                   State__c = 'Delhi',
                                   District__c = 'New Delhi',
                                   Pincode__c = '110001',
                                   Primary_Phone_Number__c = '1234567890');
        insert acc1;
                
        // Create test accounts
        Account newAcc = new Account(Name = 'Psecc',
                                     Customer_Type__c = 'Secondary Customer',
                                     Customer_Status__c = 'Active',
                                     SAP_Customer_Code__c = 'SAP001222211233',
                                     City__c = 'Delhi',
                                     State__c = 'Delhi',
                                     District__c = 'New Delhi',
                                     Pincode__c = '110001',
                                     Primary_Phone_Number__c = '1234567890');
        insert newAcc;
        
        user exe = [select Id,Name from User where Employee_Code__C = '1232122343' and isActive = true limit 1];   
        
        
        User user = [SELECT Id FROM User WHERE LastName = 'Test' and isActive = true LIMIT 1];
        List<Employee_Customer_Assignment__c> ecas = new List<Employee_Customer_Assignment__c>();
        for (Integer i = 0; i < 50; i++) {
            ecas.add(new Employee_Customer_Assignment__c(
                Customer__c = acc1.Id,
                Executive__c = user.Id
            ));
        }
        
        area__c tr = new area__c();
        tr.Name = '2211sjsjs';
        tr.Sales_Channel__c = 'CPD';
        tr.Region__c =	'Kerala';
        tr.Area__c  = 'Central';
        insert tr;
        
        Test.startTest(); 
        
        
        Product_Mapping__c pm4 = new   Product_Mapping__c();
        pm4.Customer__c = acc1.Id;
        pm4.Chanel__c = 'CPD';
        pm4.Parent_Depot__c ='1100';
        pm4.Area__c = tr.Id;
        pm4.Child_Depot__c ='1100';
        pm4.Payment_Term__c = '0003';
        pm4.Exectuive__c = exe.Id;
        insert pm4;
        
        Product_Mapping__c pm5 = new Product_Mapping__c(
            Customer__c = newAcc.Id,
            Payment_Term__c = '0003',
            Chanel__c = 'CPD',
            Exectuive__c = exe.Id,
            Area__c = tr.Id,
            Primary_Customer__c = acc1.Id
        );
        insert pm5;
        
        
        Employee_Customer_Assignment__c emp = new Employee_Customer_Assignment__c(
            Customer__c = acc1.Id,
            Executive__c = user.Id
        );
        insert emp;
        
 
        insert ecas;
        Test.stopTest();
        
        
    }
    
    @isTest
    static void testAfterUpdateChangeCustomer() {
        Profile adminProfile = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
        UserRole testRole = [SELECT Id FROM UserRole LIMIT 1];
        
        user managerUser = [select Id,Name from User where Employee_Code__C = '123212231' limit 1];   
        
        user exe = [select Id,Name from User where Employee_Code__C = '1232122343' limit 1];   
        
        
        // Create employee record
        Employee__c emp1 = new Employee__c(
            Name = 'Test Employee',
            OwnerId = managerUser.Id,
            Reporting_Manager__c = managerUser.Id,
            IsDataUpload__c = true,
            Mail_Id__c = 'test@gmail.com',
            Aadhar_Number__c = '119977663390',
            Profile__c = 'ASM',
            Sales_Channel__c = 'TN',
            User_Name__c = 'my@tstasm.com'
        );
        insert emp1;
        
        // Create test accounts
        Account newAcc = new Account(Name = 'Primary Customer 1',
                                     Customer_Type__c = 'Secondary Customer',
                                     Customer_Status__c = 'Active',
                                     SAP_Customer_Code__c = 'SAP0012233',
                                     City__c = 'Delhi',
                                     State__c = 'Delhi',
                                     District__c = 'New Delhi',
                                     Pincode__c = '110001',
                                     Primary_Phone_Number__c = '1234567890');
        insert newAcc;
        
        // Create test accounts
        Account newAcc1 = new Account(Name = 'Primary Customer 1',
                                      Customer_Type__c = 'Primary Customer',
                                      Customer_Status__c = 'Active',
                                      SAP_Customer_Code__c = 'SAP001221233',
                                      
                                      City__c = 'Delhi',
                                      State__c = 'Delhi',
                                      District__c = 'New Delhi',
                                      Pincode__c = '110001',
                                      Primary_Phone_Number__c = '2344567890');
        insert newAcc1;
        
        // Create test accounts
        Account newAcc3 = new Account(Name = 'Primary Customer 1',
                                      Customer_Type__c = 'Primary Customer',
                                      Customer_Status__c = 'Active',
                                      SAP_Customer_Code__c = 'SAe1111121P0012233',
                                      
                                      City__c = 'Delhi',
                                      State__c = 'Delhi',
                                      District__c = 'New Delhi',
                                      Pincode__c = '110001',
                                      Primary_Phone_Number__c = '1234567890');
        insert newAcc3;
        
        
        Test.startTest();
        area__c tr = new area__c();
        tr.Name = 'test11121';
        tr.Sales_Channel__c = 'CPD';
        tr.Region__c =	'Kerala';
        tr.Area__c  = 'Central';
        insert tr;
        
        Product_Mapping__c pm1 = new Product_Mapping__c(
            Customer__c = newAcc1.Id,
            Area__c = tr.Id,
            Chanel__c = 'CPD',
            Payment_Term__c = '0003',
            Exectuive__c = exe.Id
        );
        insert pm1;
        Product_Mapping__c pm11 = new Product_Mapping__c(
            Customer__c = newAcc1.Id,
            Area__c = tr.Id,
            Chanel__c = 'CPD',
            Payment_Term__c = '0003',
            Exectuive__c = managerUser.Id
        );
        insert pm11;
        
        
        Product_Mapping__c pm7 = new Product_Mapping__c(
            Customer__c = newAcc3.Id,
            Payment_Term__c = '0003',
            Chanel__c = 'CPD',
            Area__c = tr.Id,
            Exectuive__c = managerUser.Id
        );
        insert pm7;
        
        Product_Mapping__c pm = new Product_Mapping__c(
            Customer__c = newAcc.Id,
            Payment_Term__c = '0003',
            Chanel__c = 'CPD',
            Exectuive__c = exe.Id,
            Area__c = tr.Id,
            Primary_Customer__c = newAcc1.Id
        );
        insert pm;
        

        
        
        Employee_Customer_Assignment__c emp = new Employee_Customer_Assignment__c(
            Customer__c = newAcc3.Id,
            Employee__c = emp1.Id,
            Executive__c = exe.Id
        );
        insert emp;
        
        emp = [SELECT Id, Customer__c, Employee__c, Executive__c FROM Employee_Customer_Assignment__c WHERE Id = :emp.Id];
        emp.Customer__c = newAcc1.Id;
        emp.Executive__c = exe.Id;
        update emp;
        
        
        Test.stopTest();
        
    }
    
    
    @isTest
    static void testAfterDelete() {
        user testUser2 = [select Id,Name from User where Employee_Code__C = '123212231' limit 1];   
        
        user testUser1 = [select Id,Name from User where Employee_Code__C = '1232122343' limit 1];   
        
        
        // Create test accounts
        Account newAcc1 = new Account(Name = 'Primary Customer 1',
                                      Customer_Type__c = 'Primary Customer',
                                      Customer_Status__c = 'Active',
                                      SAP_Customer_Code__c = 'SAP0012222221233',
                                      
                                      City__c = 'Delhi',
                                      State__c = 'Delhi',
                                      District__c = 'New Delhi',
                                      Pincode__c = '110001',
                                      Primary_Phone_Number__c = '9344567890');
        insert newAcc1;
        
        // Create test accounts
        Account newAcc3 = new Account(Name = 'Primary Customer 1',
                                      Customer_Type__c = 'Primary Customer',
                                      Customer_Status__c = 'Active',
                                      SAP_Customer_Code__c = 'S111Ae1111121P0012233',
                                      
                                      City__c = 'Delhi',
                                      State__c = 'Delhi',
                                      District__c = 'New Delhi',
                                      Pincode__c = '110001',
                                      Primary_Phone_Number__c = '7234567890');
        insert newAcc3;
        
        
        // Create Employee_Customer_Assignment__c records
        Employee_Customer_Assignment__c eca1 = new Employee_Customer_Assignment__c(
            Customer__c = newAcc1.Id,
            Executive__c = testUser1.Id
        );
        Employee_Customer_Assignment__c eca2 = new Employee_Customer_Assignment__c(
            Customer__c = newAcc3.Id,
            Executive__c = testUser2.Id
        );
        insert new List<Employee_Customer_Assignment__c>{ eca1, eca2 };
            // Prepare test data
            Employee_Customer_Assignment__c eca = [SELECT Id, Customer__c, Executive__c 
                                                   FROM Employee_Customer_Assignment__c 
                                                   WHERE Customer__r.Name = 'Primary Customer 1' LIMIT 1];
        
        
        Test.startTest();
        delete eca;
        Test.stopTest();
        
        
    }
    

}