force-app/main/default/objects/Area__c/Area__c.object-meta.xml
<CustomObject>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Area__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Area</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Region__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Area</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Area__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Regions</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Area__c/fields/Sales_Channel__c.field-meta.xml
<CustomField>
    <fullName>Sales_Channel__c</fullName>
    <label>Sales Channel</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Chanel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Aadhar_Number__c.field-meta.xml
<CustomField>
    <fullName>Aadhar_Number__c</fullName>
    <label>Aadhar Number</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Area</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <label>District</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>State__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>District</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Employee_Code__c.field-meta.xml
<CustomField>
    <fullName>Employee_Code__c</fullName>
    <externalId>true</externalId>
    <label>Employee Code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Mail_Id__c.field-meta.xml
<CustomField>
    <fullName>Mail_Id__c</fullName>
    <label>Mail Id</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Payroll__c.field-meta.xml
<CustomField>
    <fullName>Payroll__c</fullName>
    <label>Payroll</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payroll</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <label>Permission Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Profile</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Regions</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Reporting_Manager__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reporting Manager</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>User.Id</field>
            <operation>notEqual</operation>
            <valueField>$Source.User__c</valueField>
        </filterItems>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Employees1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Sales_Channel__c.field-meta.xml
<CustomField>
    <fullName>Sales_Channel__c</fullName>
    <label>Sales Channel</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Chanel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/fields/User_Name__c.field-meta.xml
<CustomField>
    <fullName>User_Name__c</fullName>
    <label>Username</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Employee_Customer_Assignment__c/Employee_Customer_Assignment__c.object-meta.xml
<CustomObject>
    <label>Employee Customer Assignment</label>
    <nameField>
        <displayFormat>ECA-{0000}</displayFormat>
        <label>Customer Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Customer Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Customer_Assignment__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Employee Customer Assignments</relationshipLabel>
    <relationshipName>Employee_Customer_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee_Customer_Assignment__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Employee Customer Assignments</relationshipLabel>
    <relationshipName>Employee_Customer_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee_Customer_Assignment__c/fields/Employee_Code__c.field-meta.xml
<CustomField>
    <fullName>Employee_Code__c</fullName>
    <formula>Employee__r.Employee_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Executive Employee Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee_Customer_Assignment__c/fields/Executive__c.field-meta.xml
<CustomField>
    <fullName>Executive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Executive</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employee_Customer_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/Product_Mapping__c.object-meta.xml
<CustomObject>
    <label>Product Mapping</label>
    <nameField>
        <displayFormat>PM-{0000}</displayFormat>
        <label>Product Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Mapping__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Area</label>
    <referenceTo>Area__c</referenceTo>
    <relationshipLabel>Product Mappings</relationshipLabel>
    <relationshipName>Product_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Chanel__c.field-meta.xml
<CustomField>
    <fullName>Chanel__c</fullName>
    <label>Sales Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Chanel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Product Mappings</relationshipLabel>
    <relationshipName>Product_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <formula>TEXT(Customer__r.Customer_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Product Mappings</relationshipLabel>
    <relationshipName>Product_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Exectuive__c.field-meta.xml
<CustomField>
    <fullName>Exectuive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Executive</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Product_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Payment_Term__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term__c</fullName>
    <label>Payment Term</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Term</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Primary_Customer__c.field-meta.xml
<CustomField>
    <fullName>Primary_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Product Mappings (Primary Customer)</relationshipLabel>
    <relationshipName>Product_Mappings1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Secondary_Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Customer_Type__c</fullName>
    <formula>TEXT(Customer__r.Secondary_Customer_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Secondary Customer Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Region__c/Region__c.object-meta.xml
<CustomObject>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/EmployeeCustomerAssignmentControllerTest.cls
@isTest
public class EmployeeCustomerAssignmentControllerTest {

    @TestSetup
    static void setup() {
        // Create test user
        User testUser = new User(
            Alias = 'tuser',
            Employee_Code__c  = '123212231',
            Email = 'testuser@example.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'Test',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1].Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            Username = 'testuser@example.com' + System.currentTimeMillis(),
           Sales_Channel__c = 'Cake'
        );
        insert testUser;

        // Create deactivated user
        User deactivatedUser = new User(
            Alias = 'duser',
             Employee_Code__c  = '123212233',
            Email = 'deactuser@example.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'Deact',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1].Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            Username = 'deactuser@example.com' + System.currentTimeMillis(),
          	IsActive = false,
             Sales_Channel__c = 'Cake'
        );
        insert deactivatedUser;

        
        area__c area = new area__c();
        area.Name = 'test11121';
        area.Sales_Channel__c = 'CPD';
        area.Region__c =	'Kerala';
        area.Area__c  = 'Central';
        insert area;

        // Create Employee__c
        Employee__c emp = new Employee__c(
            Name = 'Test Employee',
            User__c = testUser.Id,
            Is_Active__c = true,
            Payroll__c = 'Yes',
            Reporting_Manager__c = testUser.Id,
            Sales_Channel__c = 'Cake',
            Mail_Id__c = 'test.employee@example.com',          // Required
            Aadhar_Number__c = '123412341234',                 // Required
            Profile__c = 'DSM',                                // Required (string or lookup, adjust if it's a reference)
            User_Name__c = 'test.employee@example.com'                     // Required
        );
        insert emp;

        // Create Accounts (Primary and Secondary Customers)
        List<Account> accounts = new List<Account>();
        accounts.add(new Account(
            Name = 'Primary Customer 1',
            Customer_Type__c = 'Primary Customer',
            Customer_Status__c = 'Active',
            SAP_Customer_Code__c = 'SAP001',
            Area__c = area.Id,
            City__c = 'Delhi',
            State__c = 'Delhi',
            District__c = 'New Delhi',
            Pincode__c = '110001',
            Primary_Phone_Number__c = '1234567890'
        ));
        accounts.add(new Account(
            Name = 'Primary Customer 2',
            Customer_Type__c = 'Primary Customer',
            Customer_Status__c = 'Active',
            SAP_Customer_Code__c = 'SAP001121',
            Area__c = area.Id,
            City__c = 'Delhi',
            State__c = 'Delhi',
            District__c = 'New Delhi',
            Pincode__c = '110001',
            Primary_Phone_Number__c = '2134567890'
        ));
        accounts.add(new Account(
            Name = 'Secondary Customer 1',
            Customer_Type__c = 'Secondary Customer',
            Customer_Status__c = 'Active',
            SAP_Customer_Code__c = 'SAP002',
            City__c = 'Delhi',
            State__c = 'Delhi',
            District__c = 'New Delhi',
            Pincode__c = '110001',
            Secondary_Customer_Type__c = 'Sub Stockiest',
            Primary_Phone_Number__c = '9876543210'
        ));
        insert accounts;

        // Create Employee_Customer_Assignment__c
        Employee_Customer_Assignment__c eca = new Employee_Customer_Assignment__c(
            Executive__c = testUser.Id,
            Employee__c = emp.Id,
            Customer__c = accounts[0].Id
        );
        insert eca;
        
        // Create primary Product_Mapping__c
        Product_Mapping__c pm = new Product_Mapping__c(
            Exectuive__c = testUser.Id,
            Employee__c = emp.Id,
            Customer__c = accounts[0].Id,
            Primary_Customer__c = accounts[0].Id,
            Area__c = area.Id,
            Payment_Term__c = '0003',
            Chanel__c = 'CPD'
            // Remove Customer__r
        );
        insert pm;
        
        // Create secondary Product_Mapping__c
        Product_Mapping__c pmSecondary = new Product_Mapping__c(
            Exectuive__c = testUser.Id,
            Employee__c = emp.Id,
            Customer__c = accounts[1].Id,
            Primary_Customer__c = accounts[0].Id,
            Area__c = area.Id,
             Chanel__c = 'CPD' 
            // Remove Customer__r
        );
        insert pmSecondary;
        
        SecondaryCustomerMappingBatch batch = new SecondaryCustomerMappingBatch();
        Database.executeBatch(batch, 100);
    }

    @isTest
    static void testGetAllDataUserSSADSM() {
        User testUser = [SELECT Id FROM User WHERE LastName = 'Test' LIMIT 1];

        Test.startTest();
        try{
            EmployeeCustomerAssignmentController.getAllData(testUser.Id, 'User');
            
        } catch(Exception e) {
            
            system.debug('hi');
        }
        Test.stopTest();

        
    }

    @isTest
    static void testGetAllDataEmployeeNonSSADSM() {
        Employee__c emp = [SELECT Id, User__c FROM Employee__c WHERE Name = 'Test Employee' LIMIT 1];
        
        EmployeeSubordinateController.getSubordinates(emp.Id);
        User deactivatedUser = [SELECT Id FROM User WHERE LastName = 'Deact' LIMIT 1];
        update new Employee__c(Id = emp.Id,User__c = deactivatedUser.Id);

        Test.startTest();
        EmployeeCustomerAssignmentController.getAllData(emp.Id, 'Employee');

        Test.stopTest();

        
    }

    @isTest
    static void testGetAllDataEmptyRecordId() {
        Test.startTest();
        EmployeeCustomerAssignmentController.getAllData('', 'User');
        Test.stopTest();

       
    }

    @isTest
    static void testGetCustomersGroupedByArea() {
        Test.startTest();
        
        EmployeeCustomerAssignmentController.getCustomersGroupedByArea();
        Test.stopTest();

       
    }

    @isTest
    static void testInsertProductMapping() {
        
        area__c area = new area__c();
        area.Name = 'tesaatdd11121';
        area.Sales_Channel__c = 'CPD';
        area.Region__c =	'Kerala';
        area.Area__c  = 'Central';
        insert area;
        
        Account acc = [SELECT Id FROM Account WHERE Customer_Type__c = 'Primary Customer' LIMIT 1];
        Employee__c emp = [SELECT Id FROM Employee__c LIMIT 1];
        Product_Mapping__c pm = new Product_Mapping__c(
            Customer__c = acc.Id,
            Exectuive__c = UserInfo.getUserId(),
            Employee__c = emp.Id,
            Chanel__c = 'CPD',
            Area__c = area.Id
            
        );

        Test.startTest();
        EmployeeCustomerAssignmentController.insertProductMaping(pm);
        Test.stopTest();

        
    }

    @isTest
    static void testInsertExecutiveCustomerMapping() {
        Account acc = [SELECT Id FROM Account WHERE Customer_Type__c = 'Primary Customer' and Name='Primary Customer 2' LIMIT 1];
        Employee__c emp = [SELECT Id FROM Employee__c LIMIT 1];
        Employee_Customer_Assignment__c eca = new Employee_Customer_Assignment__c(
            Customer__c = acc.Id,
            Executive__c = UserInfo.getUserId(),
            Employee__c = emp.Id
        );

        Test.startTest();
         
        EmployeeCustomerAssignmentController.insertExecutiveCustomerMapping(eca);
        Test.stopTest();

        
    }

    @isTest
    static void testGetSecondaryCustomerAssignmentUserSSADSM() {
        User testUser = [SELECT Id FROM User WHERE LastName = 'Test' LIMIT 1];

        Test.startTest();
        try{
            EmployeeCustomerAssignmentController.getSecondaryCustomerAssignment(testUser.Id, 'User');
            
            
        } catch(Exception e) {
            system.debug('hi');
            
        }
        Test.stopTest();

        
    }

    @isTest
    static void testGetSecondaryCustomerAssignmentEmployeeNonSSADSM() {
        Employee__c emp = [SELECT Id, User__c FROM Employee__c WHERE Name = 'Test Employee' LIMIT 1];
        User deactivatedUser = [SELECT Id FROM User WHERE LastName = 'Deact' LIMIT 1];
        update new Employee__c(Id = emp.Id,User__c = deactivatedUser.Id);

        Test.startTest();
        EmployeeCustomerAssignmentController.getSecondaryCustomerAssignment(emp.Id, 'Employee');
        Test.stopTest();
    }

    @isTest
    static void testSaveProductMappings() {
             area__c area = new area__c();
        area.Name = 'test111www21';
        area.Sales_Channel__c = 'CPD';
        area.Region__c =	'Kerala';
        area.Area__c  = 'Central';
        insert area;

        Account acc = [SELECT Id FROM Account WHERE Customer_Type__c = 'Primary Customer' LIMIT 1];
        Employee__c emp = [SELECT Id FROM Employee__c LIMIT 1];
        Product_Mapping__c pm = new Product_Mapping__c(
            Customer__c = acc.Id,
            Exectuive__c = UserInfo.getUserId(),
            Employee__c = emp.Id,
            Chanel__c = 'CPD',
            Area__c = area.Id
           
        );
        insert pm;

        List<Product_Mapping__c> mappings = new List<Product_Mapping__c>{ pm };
        List<Id> toDelete = new List<Id>{ pm.Id };

        Test.startTest();
        try{
            EmployeeCustomerAssignmentController.saveProductMappings(mappings, toDelete);
            
        } catch(Exception e) {
            system.debug('hi');
        }
        Test.stopTest();

       
    }

    @isTest
    static void testSaveProductMappingsEmptyList() {
        Test.startTest();
        EmployeeCustomerAssignmentController.saveProductMappings(null, new List<Id>());
        Test.stopTest();

       
    }
}