force-app/main/default/objects/Area__c/Area__c.object-meta.xml
<CustomObject>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Area__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Area</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Region__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Area</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Area__c/fields/Territory_Code_Text__c.field-meta.xml
<CustomField>
    <fullName>Territory_Code_Text__c</fullName>
    <externalId>true</externalId>
    <label>Territory Code Text</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Child_beat__c/Child_beat__c.object-meta.xml
<CustomObject>
    <label>Beat</label>
    <nameField>
        <label>Beat Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Beats</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Child_beat__c/fields/Beat_Id_Text__c.field-meta.xml
<CustomField>
    <fullName>Beat_Id_Text__c</fullName>
    <externalId>true</externalId>
    <label>Beat ID</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Child_beat__c/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <label>Order Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Child_beat__c/fields/Primary_Customer__c.field-meta.xml
<CustomField>
    <fullName>Primary_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Beats</relationshipLabel>
    <relationshipName>Beats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Child_beat__c/fields/Sub_Stockist__c.field-meta.xml
<CustomField>
    <fullName>Sub_Stockist__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sub Stockist</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Beats (Sub Stockist)</relationshipLabel>
    <relationshipName>Beats1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Division__c/Division__c.object-meta.xml
<CustomObject>
    <label>Division</label>
    <nameField>
        <label>Division Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Divisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Customer_Assignment__c/Employee_Customer_Assignment__c.object-meta.xml
<CustomObject>
    <label>Employee Customer Assignment</label>
    <nameField>
        <displayFormat>ECA-{0000}</displayFormat>
        <label>Customer Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Customer Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Customer_Assignment__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Employee Customer Assignments</relationshipLabel>
    <relationshipName>Employee_Customer_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee_Customer_Assignment__c/fields/Executive__c.field-meta.xml
<CustomField>
    <fullName>Executive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Executive</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employee_Customer_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Junction_Beat__c/Junction_Beat__c.object-meta.xml
<CustomObject>
    <label>Beat Item</label>
    <nameField>
        <displayFormat>ITEM - {0000}</displayFormat>
        <label>Beat Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Beat Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Junction_Beat__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Junction_Beats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Junction_Beat__c/fields/Child_beat__c.field-meta.xml
<CustomField>
    <fullName>Child_beat__c</fullName>
    <label>Beat</label>
    <referenceTo>Child_beat__c</referenceTo>
    <relationshipLabel>Beat Items</relationshipLabel>
    <relationshipName>Junction_Beats</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Junction_Beat__c/fields/Mapping_Id__c.field-meta.xml
<CustomField>
    <fullName>Mapping_Id__c</fullName>
    <externalId>true</externalId>
    <label>Beat Item ID</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PJP_Item__c/PJP_Item__c.object-meta.xml
<CustomObject>
    <label>PJP Item</label>
    <nameField>
        <displayFormat>ITEM - {0000}</displayFormat>
        <label>PJP Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PJP Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PJP_Item__c/fields/Assigned_Beat__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Beat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Beat</label>
    <referenceTo>Child_beat__c</referenceTo>
    <relationshipLabel>PJP Items (Worked Beat)</relationshipLabel>
    <relationshipName>PJP_Items1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PJP_Item__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PJP_Item__c/fields/Mapping_Id__c.field-meta.xml
<CustomField>
    <fullName>Mapping_Id__c</fullName>
    <externalId>true</externalId>
    <label>PJP Item ID</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PJP_Item__c/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <label>Sequence Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PJP_Item__c/fields/PJP__c.field-meta.xml
<CustomField>
    <fullName>PJP__c</fullName>
    <label>PJP</label>
    <referenceTo>Calendar_beat__c</referenceTo>
    <relationshipLabel>PJP Items</relationshipLabel>
    <relationshipName>PJP_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/Product_Mapping__c.object-meta.xml
<CustomObject>
    <label>Product Mapping</label>
    <nameField>
        <displayFormat>PM-{0000}</displayFormat>
        <label>Product Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Mapping__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Area</label>
    <referenceTo>Area__c</referenceTo>
    <relationshipLabel>Product Mappings</relationshipLabel>
    <relationshipName>Product_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Chanel__c.field-meta.xml
<CustomField>
    <fullName>Chanel__c</fullName>
    <label>Sales Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Chanel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Child_Depot__c.field-meta.xml
<CustomField>
    <fullName>Child_Depot__c</fullName>
    <label>Delivery Plant</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Parent_Depot__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Child_Depot</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Product Mappings</relationshipLabel>
    <relationshipName>Product_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Distribution_Channel__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Channel__c</fullName>
    <label>Distribution Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Distribution_Channel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Exectuive__c.field-meta.xml
<CustomField>
    <fullName>Exectuive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Executive</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Product_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Inco_Terms__c.field-meta.xml
<CustomField>
    <fullName>Inco_Terms__c</fullName>
    <label>Inco Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Inco_Terms</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Mapping_Id__c.field-meta.xml
<CustomField>
    <fullName>Mapping_Id__c</fullName>
    <externalId>true</externalId>
    <label>Mapping Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Order_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Parent_Depot__c.field-meta.xml
<CustomField>
    <fullName>Parent_Depot__c</fullName>
    <label>Sales Organization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Parent_Depot</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Payment_Term__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term__c</fullName>
    <label>Payment Term</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Term</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/PDP_Day__c.field-meta.xml
<CustomField>
    <fullName>PDP_Day__c</fullName>
    <label>PDP Day</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PDP_Day</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Primary_Customer__c.field-meta.xml
<CustomField>
    <fullName>Primary_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Product Mappings (Primary Customer)</relationshipLabel>
    <relationshipName>Product_Mappings1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Sales_Office__c.field-meta.xml
<CustomField>
    <fullName>Sales_Office__c</fullName>
    <label>Sales Office</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Office</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Sub_Stockiest__c.field-meta.xml
<CustomField>
    <fullName>Sub_Stockiest__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sub Stockiest</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Product Mappings (Sub Stockiest)</relationshipLabel>
    <relationshipName>Product_Mappings2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CSVFieldMapping.cls
/*
 *********************************************************
Apex Class Name    : CSVFieldMapping
    Created Date       : Apr 12, 2024
    @description       : This class is used to map the field names (API Names) to the CSV Headers
@author            : Mayuri Patel
Modification Log:
    Ver   Date         Author                  Modification
    1.0   12-04-2024   Mayuri Patel            Initial Version
     *********************************************************
 */
public class CSVFieldMapping {
    
    public Map<String,String> fieldMap = new Map<String,String>();
    public Map<String,DataType> typeMap = new Map<String,DataType>();
    public Map<String,String> refFieldMap = new Map<String,String>();
    String externalId = '';
    
    //   public enum DataType {Text, Reference, Picklist, DateType, Checkbox, DateTimeType, DecimalType, IntegerType}
    
    public CSVFieldMapping(){}
    
    public CSVFieldMapping(String objectName){
        
        if(objectName == 'Junction_Beat__c'){
            
            fieldMap.put('Mapping ID','Mapping_Id__c');
            typeMap.put('Mapping_Id__c',DataType.ExternalId);
            externalId = 'Mapping_Id__c';
            
            fieldMap.put('Beat ID','Child_beat__c');
            typeMap.put('Child_beat__c',DataType.Reference);
            refFieldMap.put('Child_beat__c','Beat_ID_Text__c');
            
            fieldMap.put('Customer Code','Account__c');
            typeMap.put('Account__c',DataType.Reference);
            refFieldMap.put('Account__c','Customer_Code_Text__c');
            
            fieldMap.put('Sequence Number','Order_Number__c');
            typeMap.put('Order_Number__c',DataType.DecimalType);
            
        }
        else if(objectName == 'Child_beat__c'){
            
            fieldMap.put('Beat ID','Beat_ID_Text__c');
            typeMap.put('Beat_ID_Text__c',DataType.ExternalId);
            externalId = 'Beat_ID_Text__c';
            
            fieldMap.put('Beat Name','Name');
            typeMap.put('Name',DataType.Text);
            
            fieldMap.put('Primary Customer Code','Primary_Customer__c');
            typeMap.put('Primary_Customer__c',DataType.Reference);
            refFieldMap.put('Primary_Customer__c','SAP_Customer_Code__c');
            
            fieldMap.put('Substockiest Customer Code','Sub_Stockist__c');
            typeMap.put('Sub_Stockist__c',DataType.Reference);
            refFieldMap.put('Sub_Stockist__c','Outlet_Id__c');
            
        }
        else if(objectName == 'PJP_Item__c'){
            
            fieldMap.put('Mapping ID','Mapping_Id__c');
            typeMap.put('Mapping_Id__c',DataType.ExternalId);
            externalId = 'Mapping_Id__c';
            
            fieldMap.put('PJP ID','PJP__c');
            typeMap.put('PJP__c',DataType.Reference);
            refFieldMap.put('PJP__c','PJP_Id_Text__c');
            
            fieldMap.put('Beat ID','Assigned_Beat__c');
            typeMap.put('Assigned_Beat__c',DataType.Reference);
            refFieldMap.put('Assigned_Beat__c','Beat_ID_Text__c');
            
            fieldMap.put('Sequence Number','Order_Number__c');
            typeMap.put('Order_Number__c',DataType.DecimalType);
            
            fieldMap.put('Date','Date__c');
            typeMap.put('Date__c',DataType.DateType);
            
        }
        else if(objectName == 'Employee_Customer_Assignment__c'){
            
            
            fieldMap.put('User Id','Executive__c');
            typeMap.put('Executive__c',DataType.Reference);
            refFieldMap.put('Executive__c','User_Id_Text__c');
            
            fieldMap.put('Customer Code','Customer__c');
            typeMap.put('Customer__c',DataType.Reference);
            refFieldMap.put('Customer__c','Customer_Code_Text__c');
            
            
            fieldMap.put('Mapping ID','Mapping_Id__c');
            typeMap.put('Mapping_Id__c',DataType.ExternalId);
            externalId = 'Mapping_Id__c';
            
            
        }
        else if(objectName == 'Product_Mapping__c'){
            
            
            fieldMap.put('User Id','Exectuive__c');
            typeMap.put('Exectuive__c',DataType.Reference);
            refFieldMap.put('Exectuive__c','User_Id_Text__c');
            
            fieldMap.put('Customer Code','Customer__c');
            typeMap.put('Customer__c',DataType.Reference);
            refFieldMap.put('Customer__c','Customer_Code_Text__c');
            
            fieldMap.put('Primary Customer Code','Primary_Customer__c');
            typeMap.put('Primary_Customer__c',DataType.Reference);
            refFieldMap.put('Primary_Customer__c','Customer_Code_Text__c');
            
            fieldMap.put('Substockiest Customer Code','Sub_Stockiest__c');
            typeMap.put('Sub_Stockiest__c',DataType.Reference);
            refFieldMap.put('Sub_Stockiest__c','Customer_Code_Text__c');
            
            
            fieldMap.put('Sales Channel','Chanel__c');
            typeMap.put('Chanel__c',DataType.Picklist);
            
            fieldMap.put('Territory','Area__c');
            typeMap.put('Area__c',DataType.Reference);
            refFieldMap.put('Area__c','Territory_Code_Text__c');
            
            fieldMap.put('PDP Day','PDP_Day__c');
            typeMap.put('PDP_Day__c',DataType.Picklist);
            
            fieldMap.put('Sales Organization','Parent_Depot__c');
            typeMap.put('Parent_Depot__c',DataType.Picklist);
            
            fieldMap.put('Delivery Plant','Child_Depot__c');
            typeMap.put('Child_Depot__c',DataType.Picklist);
            
            fieldMap.put('Sales Office','Sales_Office__c');
            typeMap.put('Sales_Office__c',DataType.Picklist);
            
            fieldMap.put('Order Type','Order_Type__c');
            typeMap.put('Order_Type__c',DataType.Picklist);
            
            fieldMap.put('Distribution Channel','Distribution_Channel__c');
            typeMap.put('Distribution_Channel__c',DataType.Picklist);
            
            fieldMap.put('Division','Division__c');
            typeMap.put('Division__c',DataType.Picklist);
            
            fieldMap.put('Payment Term','Payment_Term__c');
            typeMap.put('Payment_Term__c',DataType.Picklist);
            
            fieldMap.put('Inco Terms','Inco_Terms__c');
            typeMap.put('Inco_Terms__c',DataType.Picklist);
            
            
            fieldMap.put('Mapping ID','Mapping_Id__c');
            typeMap.put('Mapping_Id__c',DataType.ExternalId);
            externalId = 'Mapping_Id__c';
            
            
        }
        
    }
    
    public String getAPIName(String headerName){
        return fieldMap.containsKey(headerName) ? fieldMap.get(headerName) : null;
    }
    
    public DataType getFieldType(String apiName){
        // system.debug(apiName);
        // system.debug(typeMap);
        return typeMap.containsKey(apiName) ? typeMap.get(apiName) : DataType.Text;
    }
    public String getExternalFieldName(String apiName){
        return refFieldMap.containsKey(apiName) ? refFieldMap.get(apiName) : null;
    }
    
    public String getExternalIdName(){
        return externalId;
    }
}