force-app/main/default/objects/Area__c/Area__c.object-meta.xml
<CustomObject>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Area__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Area</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Region__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Area</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Area__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Regions</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Area__c/fields/RSM__c.field-meta.xml
<CustomField>
    <fullName>RSM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RSM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Territories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Area__c/fields/Sales_Channel__c.field-meta.xml
<CustomField>
    <fullName>Sales_Channel__c</fullName>
    <label>Sales Channel</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Chanel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Child_beat__c/Child_beat__c.object-meta.xml
<CustomObject>
    <label>Beat</label>
    <nameField>
        <label>Beat Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Beats</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Child_beat__c/fields/Sales_Channel__c.field-meta.xml
<CustomField>
    <fullName>Sales_Channel__c</fullName>
    <formula>IF(INCLUDES(Owner:User.Sales_Channel__c, &quot;TN&quot;), &quot;TN; &quot;, &quot;&quot;) &amp;
IF(INCLUDES(Owner:User.Sales_Channel__c, &quot;AP&quot;), &quot;AP; &quot;, &quot;&quot;) &amp;
IF(INCLUDES(Owner:User.Sales_Channel__c, &quot;TS&quot;), &quot;TS; &quot;, &quot;&quot;) &amp;
IF(INCLUDES(Owner:User.Sales_Channel__c, &quot;Cake&quot;), &quot;Cake; &quot;, &quot;&quot;) &amp;
IF(INCLUDES(Owner:User.Sales_Channel__c, &quot;Institutional&quot;), &quot;Institutional; &quot;, &quot;&quot;) &amp;
IF(INCLUDES(Owner:User.Sales_Channel__c, &quot;District Bulk&quot;), &quot;District Bulk; &quot;, &quot;&quot;) &amp;
IF(INCLUDES(Owner:User.Sales_Channel__c, &quot;Bread&quot;), &quot;Bread; &quot;, &quot;&quot;) &amp;
IF(INCLUDES(Owner:User.Sales_Channel__c, &quot;KA&quot;), &quot;KA; &quot;, &quot;&quot;) &amp;
IF(INCLUDES(Owner:User.Sales_Channel__c, &quot;Bulk Depot&quot;), &quot;Bulk Depot; &quot;, &quot;&quot;) &amp;
IF(INCLUDES(Owner:User.Sales_Channel__c, &quot;CPD&quot;), &quot;CPD; &quot;, &quot;&quot;) &amp;
IF(INCLUDES(Owner:User.Sales_Channel__c, &quot;Madurai&quot;), &quot;Madurai; &quot;, &quot;&quot;) &amp;
IF(INCLUDES(Owner:User.Sales_Channel__c, &quot;West&quot;), &quot;West; &quot;, &quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Channel</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Aadhar_Number__c.field-meta.xml
<CustomField>
    <fullName>Aadhar_Number__c</fullName>
    <label>Aadhar Number</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <formula>Is_Active__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Area</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/fields/ASM_TSM__c.field-meta.xml
<CustomField>
    <fullName>ASM_TSM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee Approver L1</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>ASM</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>TSM</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Employees3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Basic_Pay__c.field-meta.xml
<CustomField>
    <fullName>Basic_Pay__c</fullName>
    <label>Monthly Basic Pay (INR)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/DA__c.field-meta.xml
<CustomField>
    <fullName>DA__c</fullName>
    <label>DA (INR)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Designation__c.field-meta.xml
<CustomField>
    <fullName>Designation__c</fullName>
    <label>Designation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Area Sales Manager</fullName>
            </value>
            <value>
                <fullName>Chief Executive Officer - Sales</fullName>
            </value>
            <value>
                <fullName>Consultant/Mentor</fullName>
            </value>
            <value>
                <fullName>Delivery Boy</fullName>
            </value>
            <value>
                <fullName>Depot In Charge</fullName>
            </value>
            <value>
                <fullName>Deputy Area Sales Manager</fullName>
            </value>
            <value>
                <fullName>Deputy Regional Sales Manager</fullName>
            </value>
            <value>
                <fullName>Deputy Territory Sales Manager</fullName>
            </value>
            <value>
                <fullName>Distributor Salesman</fullName>
            </value>
            <value>
                <fullName>Executive</fullName>
            </value>
            <value>
                <fullName>General  Manager</fullName>
            </value>
            <value>
                <fullName>Interim Sales Representative</fullName>
            </value>
            <value>
                <fullName>Jr.Territory Sales Executive</fullName>
            </value>
            <value>
                <fullName>Junior Territory Sales Executive</fullName>
            </value>
            <value>
                <fullName>Key Accounts Executive</fullName>
            </value>
            <value>
                <fullName>Key Accounts Manager</fullName>
            </value>
            <value>
                <fullName>Management Trainee</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Merchandiser</fullName>
            </value>
            <value>
                <fullName>Regional Sales Manager</fullName>
            </value>
            <value>
                <fullName>Sales Representative</fullName>
            </value>
            <value>
                <fullName>Secondary Sales Associates</fullName>
            </value>
            <value>
                <fullName>Senior Area Sales Manager</fullName>
            </value>
            <value>
                <fullName>Senior Executive</fullName>
            </value>
            <value>
                <fullName>Senior Key Accounts Officer</fullName>
            </value>
            <value>
                <fullName>Senior Regional Sales Manager</fullName>
            </value>
            <value>
                <fullName>Senior Sales &amp; Distribution Manager</fullName>
            </value>
            <value>
                <fullName>Senior Territory Sales Executive</fullName>
            </value>
            <value>
                <fullName>Senior Territory Sales Manager</fullName>
            </value>
            <value>
                <fullName>Territory Sales Executive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Employee_Approver_3_HR__c.field-meta.xml
<CustomField>
    <fullName>Employee_Approver_3_HR__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee Approver L3 (HR)</label>
    <referenceTo>User</referenceTo>
    <relationshipName>EmployeeswS13</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Employee_Code__c.field-meta.xml
<CustomField>
    <fullName>Employee_Code__c</fullName>
    <externalId>true</externalId>
    <label>Employee Code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Gross_Salary__c.field-meta.xml
<CustomField>
    <fullName>Gross_Salary__c</fullName>
    <label>Monthly Gross Salary (INR)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Mail_Id__c.field-meta.xml
<CustomField>
    <fullName>Mail_Id__c</fullName>
    <label>Mail Id</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Primary_Customer_Approver_1__c.field-meta.xml
<CustomField>
    <fullName>Primary_Customer_Approver_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Customer Approver L1</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employees8</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <label>Permission Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Profile</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Regions</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/fields/RSM__c.field-meta.xml
<CustomField>
    <fullName>RSM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee Approver L2</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>RSM</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Employees2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Sales_Channel__c.field-meta.xml
<CustomField>
    <fullName>Sales_Channel__c</fullName>
    <label>Sales Channel</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Chanel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Secondary_Customer_Approver_1__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Customer_Approver_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Secondary Customer Approver L1</label>
    <referenceTo>User</referenceTo>
    <relationshipName>EmployeeswS1X</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Secondary_Customer_Approver_2__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Customer_Approver_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Secondary Customer Approver L2</label>
    <referenceTo>User</referenceTo>
    <relationshipName>EmployeeswS1h</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/TA_limit__c.field-meta.xml
<CustomField>
    <fullName>TA_limit__c</fullName>
    <label>TA limit (INR)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/User_Name__c.field-meta.xml
<CustomField>
    <fullName>User_Name__c</fullName>
    <label>Username</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Role__c/fields/Role_Id__c.field-meta.xml
<CustomField>
    <fullName>Role_Id__c</fullName>
    <label>Role Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ReporteeViewControllerTest.cls
@isTest
public class ReporteeViewControllerTest {

    @TestSetup
    static void setup() {
        Profile tseProfile = [SELECT Id FROM Profile WHERE Name = 'TSE' LIMIT 1];
        UserRole testRole = [SELECT Id FROM UserRole LIMIT 1];

        User manager = new User(
            Alias = 'mgr1',
            Employee_Code__c = 'MGR001TEST',
            Email = 'manager.reportee.test@example.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'Manager',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = tseProfile.Id,
            TimeZoneSidKey = 'Asia/Kolkata',
            Username = 'manager.reportee.test@example.com' + System.currentTimeMillis(),
            Sales_Channel__c = 'Cake',
            UserRoleId = testRole.Id
        );
        insert manager;

        User sub = new User(
            Alias = 'sub1',
            Employee_Code__c = 'SUB001TEST',
            Email = 'sub.reportee.test@example.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'Subordinate',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = tseProfile.Id,
            TimeZoneSidKey = 'Asia/Kolkata',
            Username = 'sub.reportee.test@example.com' + System.currentTimeMillis(),
            Sales_Channel__c = 'Cake',
            ManagerId = manager.Id,
            UserRoleId = testRole.Id
        );
        insert sub;

        // Use System.runAs() to avoid MIXED_DML_OPERATION error
        System.runAs(sub) {
            Employee__c subEmp = new Employee__c(
                Name = 'Sub Reportee',
                Mail_Id__c = 'sub.reportee.test@example.com',
                User_Name__c = 'sub.reportee.test@example.com.testuser',
                Primary_Phone_Number__c = '9876543210',
                Employee_Code__c = 'SUB001TEST',
                Designation__c = 'TSE',
                Profile__c = 'TSE',
                Role_Id__c = testRole.Id,
                Is_Active__c = true,
                Basic_Pay__c = 25000,
                Aadhar_Number__c = '123456789012',
                Gross_Salary__c = 35000,
                DA__c = 5000,
                TA_limit__c = 2000,
                Area__c = 'Central',
                Region__c = 'West',
                ASM_TSM__c = manager.Id,
                RSM__c = manager.Id,
                Employee_Approver_3_HR__c = manager.Id,
                Secondary_Customer_Approver_1__c = manager.Id,
                Secondary_Customer_Approver_2__c = manager.Id,
                Primary_Customer_Approver_1__c = manager.Id,
                Primary_Customer_Approver_2__c = manager.Id,
                Primary_Customer_Approver_3_CD__c = manager.Id,
                PJP_Approver_1__c = manager.Id,
                PJP_Approver_2__c = manager.Id,
                Expense_Approver_1__c = manager.Id,
                Expense_Approver_2_Finance_Department__c = manager.Id,
                Sales_Channel__c = 'Cake',
                State__c = 'Uttar Pradesh',
                District__c = 'Lucknow',
                Pincode__c = '226001',
                User__c = sub.Id,
                Cloning_is_Completed__c = false,
                Role__c = 'TSE'
            );
            insert subEmp;
        }
    }

    @isTest
    static void testGetSubordinates() {
        User manager = [SELECT Id FROM User WHERE Employee_Code__c = 'MGR001TEST' LIMIT 1];
        System.runAs(manager) {
            List<ReporteeViewController.SubordinateWrapper> subs = ReporteeViewController.getSubordinates();
            System.assertNotEquals(null, subs, 'Should return non-null list');
        }
    }

    @isTest
    static void testGetSubordinatesAsSubordinate() {
        User sub = [SELECT Id FROM User WHERE Employee_Code__c = 'SUB001TEST' LIMIT 1];
        System.runAs(sub) {
            List<ReporteeViewController.SubordinateWrapper> subs = ReporteeViewController.getSubordinates();
            System.assertNotEquals(null, subs, 'Should return non-null list even with no direct reports');
        }
    }

    @isTest
    static void testGetSubordinateBeats() {
        User sub = [SELECT Id FROM User WHERE Employee_Code__c = 'SUB001TEST' LIMIT 1];

        Child_beat__c beat = new Child_beat__c(
            Name = 'Test Beat Reportee',
            Active__c = true,
            OwnerId = sub.Id,
            Beat_Type__c = 'Secondary'
        );
        insert beat;

        List<ReporteeViewController.BeatWrapper> beats = ReporteeViewController.getSubordinateBeats(sub.Id);
        System.assertNotEquals(null, beats, 'Should return non-null list');
        System.assert(beats.size() >= 1, 'Should return at least one beat for the subordinate');
    }

    @isTest
    static void testGetSubordinateBeatsNullId() {
        List<ReporteeViewController.BeatWrapper> beats = ReporteeViewController.getSubordinateBeats(null);
        System.assertNotEquals(null, beats, 'Should return non-null list for null userId');
        System.assertEquals(0, beats.size(), 'Should return empty list for null userId');
    }

    @isTest
    static void testGetSubordinateBeatOutlets() {
        User sub = [SELECT Id FROM User WHERE Employee_Code__c = 'SUB001TEST' LIMIT 1];

        Child_beat__c beat = new Child_beat__c(
            Name = 'Test Beat Outlets',
            Active__c = true,
            Beat_Type__c ='Secondary',
            OwnerId = sub.Id
        );
        insert beat;

        List<Junction_Beat__c> outlets = ReporteeViewController.getSubordinateBeatOutlets(beat.Id);
        System.assertNotEquals(null, outlets, 'Should return non-null list');
    }

    @isTest
    static void testGetSubordinateBeatOutletsWithData() {
        User sub = [SELECT Id FROM User WHERE Employee_Code__c = 'SUB001TEST' LIMIT 1];

        Child_beat__c beat = new Child_beat__c(
            Name = 'Test Beat With Outlets',
            Active__c = true,
            Beat_Type__c ='Secondary',
            OwnerId = sub.Id
        );
        insert beat;

        Junction_Beat__c junction = new Junction_Beat__c(
            Child_Beat__c = beat.Id
        );
        insert junction;

        List<Junction_Beat__c> outlets = ReporteeViewController.getSubordinateBeatOutlets(beat.Id);
        System.assertNotEquals(null, outlets, 'Should return non-null list');
        System.assert(outlets.size() >= 1, 'Should return at least one outlet for the beat');
    }

    @isTest
    static void testGetSubordinateBeatOutletsNullId() {
        List<Junction_Beat__c> outlets = ReporteeViewController.getSubordinateBeatOutlets(null);
        System.assertNotEquals(null, outlets, 'Should return non-null list for null beatId');
        System.assertEquals(0, outlets.size(), 'Should return empty list for null beatId');
    }

    @isTest
    static void testGetSubordinatesReturnsListType() {
        User manager = [SELECT Id FROM User WHERE Employee_Code__c = 'MGR001TEST' LIMIT 1];
        System.runAs(manager) {
            List<ReporteeViewController.SubordinateWrapper> subs = ReporteeViewController.getSubordinates();
            System.assertNotEquals(null, subs, 'Result should not be null');
            System.assert(subs.size() >= 0, 'List size should be zero or more');
        }
    }
}