force-app/main/default/objects/Area__c/Area__c.object-meta.xml
<CustomObject>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Area__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Area</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Region__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Area</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Area__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Regions</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Area__c/fields/Sales_Channel__c.field-meta.xml
<CustomField>
    <fullName>Sales_Channel__c</fullName>
    <label>Sales Channel</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Chanel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Sales Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Chanel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/Product_Mapping__c.object-meta.xml
<CustomObject>
    <label>Product Mapping</label>
    <nameField>
        <displayFormat>PM-{0000}</displayFormat>
        <label>Product Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Mapping__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Area</label>
    <referenceTo>Area__c</referenceTo>
    <relationshipLabel>Product Mappings</relationshipLabel>
    <relationshipName>Product_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Chanel__c.field-meta.xml
<CustomField>
    <fullName>Chanel__c</fullName>
    <label>Sales Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Chanel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Product Mappings</relationshipLabel>
    <relationshipName>Product_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <formula>TEXT(Customer__r.Customer_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Exectuive__c.field-meta.xml
<CustomField>
    <fullName>Exectuive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Executive</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Product_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Region__c/Region__c.object-meta.xml
<CustomObject>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Channel_To_SKU__c/Sales_Channel_To_SKU__c.object-meta.xml
<CustomObject>
    <label>Sales Channel To SKU</label>
    <nameField>
        <displayFormat>SCU-{0000}</displayFormat>
        <label>Sales Channel To SKU Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Channel To SKU</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Channel_To_SKU__c/fields/SKU__c.field-meta.xml
<CustomField>
    <fullName>SKU__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SKU</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Sales Channel To SKU</relationshipLabel>
    <relationshipName>Sales_Channel_To_SKU</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LookupControllerTest.cls
@isTest
public class LookupControllerTest {

    @isTest
    static void testSearchRecordsWithFilter() {
        // Create sample Account with specific Type for filtering
        
        Account primaryAcc = new Account(
            Name = 'Test Account 1',
            Customer_Type__c = 'Primary Customer',
            Pincode__c = '123456',
            Primary_Phone_Number__c = '0876543210',
            State__c = 'Karnataka',
            District__c = 'Kolar'
        );
        insert primaryAcc;
        
        Account acc2 = new Account(
            Name = 'Test Account 1',
            Customer_Type__c = 'Primary Customer',
            Pincode__c = '123456',
            Primary_Phone_Number__c = '9076543210',
            State__c = 'Karnataka',
            District__c = 'Kolar'
        );
        insert acc2;
        
        Area__c ar = new Area__c();
            ar.Sales_Channel__c = 'West';
            ar.Region__c = 'West';
			ar.Area__c = 'Mumbai';
insert ar;     
        
        Product_Mapping__c pm = new Product_Mapping__c();
        pm.Customer__c = acc2.Id;
        pm.Exectuive__c = UserInfo.getUserId();
        pm.Chanel__c = 'Cake';
        pm.Area__c = ar.Id;
        insert pm;
        
        Product__c pro = new product__c();
        pro.Name = '727272';
        insert pro;
        
        Sales_Channel_To_SKU__c sc = new Sales_Channel_To_SKU__c();
        sc.Sales_Channel__c = 'Cake';
        sc.SKU__c = pro.id;
        insert sc;


        Test.startTest();
        List<SObject> result = LookupController.searchRecords(
            'Test',              // searchKey
            'Account',           // objectApiName
            'Channel__c',              // filterField
            'Cake'           // filterValue
        );
        List<SObject> result1 = LookupController.searchRecords(
            'Test',              // searchKey
            'Account',           // objectApiName
            'Type',              // filterField
            'Cake'           // filterValue
        );
        
        List<SObject> result2 = LookupController.searchRecords(
            'Test',              // searchKey
            'Account',           // objectApiName
            'Order_Owner__c',              // filterField
            acc2.Id           // filterValue
        );
        Test.stopTest();
        

    }

}