force-app/main/default/objects/Daily_Log__c/Daily_Log__c.object-meta.xml
<CustomObject>
    <label>Daily Attendance</label>
    <nameField>
        <displayFormat>Log Id - {00000}</displayFormat>
        <label>Log Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Attendances</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Log__c/fields/Day_ended_time__c.field-meta.xml
<CustomField>
    <fullName>Day_ended_time__c</fullName>
    <label>Day ended time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit - {00000000}</displayFormat>
        <label>Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Actual_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Actual_Start_Time__c</fullName>
    <label>Actual Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/ClockIn_Latitude__c.field-meta.xml
<CustomField>
    <fullName>ClockIn_Latitude__c</fullName>
    <label>ClockIn Latitude</label>
    <precision>8</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Clockin_Longitude__c.field-meta.xml
<CustomField>
    <fullName>Clockin_Longitude__c</fullName>
    <label>Clockin Longitude</label>
    <precision>8</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/dailylogTriggerHandlerTest.cls
@isTest
public class dailylogTriggerHandlerTest {
    
    @isTest
    static void testTriggerLogic() {
        Daily_Log__c daily = new Daily_Log__c();
        insert daily;
        
        Visit__c vs = new Visit__c(Daily_Log__c = daily.Id);
        insert vs;
        
        vs.ClockIn_Latitude__c = 37.7749;
        vs.Clockin_Longitude__c = 78.4194;
        vs.Actual_Start_Time__c = DateTime.now();
        update vs;
        
        vs.Distance__c = 12;
        update vs;
        
        daily.Day_ended_time__c = DateTime.now();
        daily.Clock_Out_Location__Longitude__s = 37.7749;
        daily.Clock_Out_Location__Latitude__s = 78.4194;
        update daily;
    }
    
    @isTest
    static void testEODReportBatch() {
        // Create minimum data so batch runs once
        Daily_Log__c daily = new Daily_Log__c();
        insert daily;
        
        Test.startTest();
        Database.executeBatch(new EODReport(), 1); // force single execution
        Test.stopTest();
    }
}