force-app/main/default/objects/Daily_Log__c/Daily_Log__c.object-meta.xml
<CustomObject>
    <label>Daily Attendance</label>
    <nameField>
        <displayFormat>Log Id - {00000}</displayFormat>
        <label>Log Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Attendances</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Log__c/fields/Day_ended_time__c.field-meta.xml
<CustomField>
    <fullName>Day_ended_time__c</fullName>
    <label>Day ended time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Daily_Log__c/fields/Employee_Code__c.field-meta.xml
<CustomField>
    <fullName>Employee_Code__c</fullName>
    <formula>Owner:User.Employee_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Employee Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit - {00000000}</displayFormat>
        <label>Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Actual_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Actual_Start_Time__c</fullName>
    <label>Actual Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/ClockIn_Latitude__c.field-meta.xml
<CustomField>
    <fullName>ClockIn_Latitude__c</fullName>
    <label>ClockIn Latitude</label>
    <precision>8</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Clockin_Longitude__c.field-meta.xml
<CustomField>
    <fullName>Clockin_Longitude__c</fullName>
    <label>Clockin Longitude</label>
    <precision>8</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/EODReportTest.cls
@isTest
public class EODReportTest {
    
    @isTest
    static void testBatchRunsForManager() {
        // Create a role (required for UserRoleId != null filter)
        UserRole role = new UserRole(Name = 'Test Manager Role');
        insert role;
        
        // Create manager user
        User manager = new User(
            FirstName = 'Test',
            LastName = 'Manager',
            Email = 'manager@test.com',
            Username = 'manager' + DateTime.now().getTime() + '@test.com',
            Alias = 'tmgr',
            Employee_Code__c  = 'sjk22ddhjkj18118',
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1].Id,
            TimeZoneSidKey = 'GMT',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            UserRoleId = role.Id
        );
        insert manager;
        
        // Create subordinate
        User subordinate = new User(
            FirstName = 'Test',
            LastName = 'Subordinate',
            Email = 'sub@test.com',
             Employee_Code__c  = 'sjkhjkj1822118',
            Username = 'sub' + DateTime.now().getTime() + '@test.com',
            Alias = 'tsub',
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1].Id,
            TimeZoneSidKey = 'GMT',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            ManagerId = manager.Id
        );
        insert subordinate;
        Daily_Log__c daily = new Daily_Log__c();
        insert daily;
        
        Visit__c vs = new Visit__c(Daily_Log__c = daily.Id);
        insert vs;
        
        vs.ClockIn_Latitude__c = 37.7749;
        vs.Clockin_Longitude__c = 78.4194;
        vs.Actual_Start_Time__c = DateTime.now();
        update vs;
        
        vs.Distance__c = 12;
        update vs;
        
        daily.Day_ended_time__c = DateTime.now();
        daily.Clock_Out_Location__Longitude__s = 37.7749;
        daily.Clock_Out_Location__Latitude__s = 78.4194;
        update daily;
        
        // Run batch
        Test.startTest();
        Database.executeBatch(new EODReport(), 1);  // force single execution
        Test.stopTest();
        

    }
}