force-app/main/default/objects/Daily_Log__c/Daily_Log__c.object-meta.xml
<CustomObject>
    <label>Daily Attendance</label>
    <nameField>
        <displayFormat>Log Id - {00000}</displayFormat>
        <label>Log Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Attendances</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Log__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <formula>DATEVALUE( Day_started_time__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Daily_Log__c/fields/Return_Calls__c.field-meta.xml
<CustomField>
    <fullName>Return_Calls__c</fullName>
    <label>Return Calls</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/Product_Mapping__c.object-meta.xml
<CustomObject>
    <label>Product Mapping</label>
    <nameField>
        <displayFormat>PM-{0000}</displayFormat>
        <label>Product Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Mapping__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Product Mappings</relationshipLabel>
    <relationshipName>Product_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Customer_Executive_Pair__c.field-meta.xml
<CustomField>
    <fullName>Customer_Executive_Pair__c</fullName>
    <formula>CASESAFEID(Customer__c ) +&apos;-&apos;+ CASESAFEID(Exectuive__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer_Executive_Pair</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <formula>TEXT(Customer__r.Customer_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Primary_Customer__c.field-meta.xml
<CustomField>
    <fullName>Primary_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Product Mappings (Primary Customer)</relationshipLabel>
    <relationshipName>Product_Mappings1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Sub_Stockiest__c.field-meta.xml
<CustomField>
    <fullName>Sub_Stockiest__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sub Stockiest</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Product Mappings (Sub Stockiest)</relationshipLabel>
    <relationshipName>Product_Mappings2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Return__c/Return__c.object-meta.xml
<CustomObject>
    <label>Return</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Return Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Returns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Return__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Returns</relationshipLabel>
    <relationshipName>Returns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Return__c/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Returns (Distributor)</relationshipLabel>
    <relationshipName>Returns1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Return__c/fields/Sub_Stockiest__c.field-meta.xml
<CustomField>
    <fullName>Sub_Stockiest__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sub Stockiest</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Returns (Sub Stockiest)</relationshipLabel>
    <relationshipName>Returns2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Return__c/fields/UniqueFileId__c.field-meta.xml
<CustomField>
    <fullName>UniqueFileId__c</fullName>
    <label>UniqueFileId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ReturnTriggerHandler.cls
public class ReturnTriggerHandler {
    public static void beforInsert(List<Return__c> newReturns) {
        set<String> customerCodes = new set<String>();
        set<String> customerWithExecutiveIds = new set<String>();
        // Collect all unique file IDs from new accounts
        for (Return__c dl : newReturns) {
            if(dl.Customer__c !=null && dl.Customer_Type__c == 'Secondary Customer')
            {
                string key = dl.Customer__c +'-'+dl.OwnerId;
                customerWithExecutiveIds.add(key);
                customerCodes.add(dl.Customer__c);
            }
        }
        
        
        list<Product_Mapping__c> secondaryMappings = [select Id,Primary_Customer__c,Customer__c,Customer_Executive_Pair__c,Sub_Stockiest__c
                                                      from Product_Mapping__c where 
                                                      Customer_Executive_Pair__c In:customerWithExecutiveIds and Primary_Customer__c != null];
        list<Product_Mapping__c> allsecondaryMappings = [select Id,Primary_Customer__c,Customer__c,Customer_Executive_Pair__c,Sub_Stockiest__c
                                                         from Product_Mapping__c where Customer__c In:customerCodes and Primary_Customer__c != null];
        
        if(!secondaryMappings.isEmpty() || !allsecondaryMappings.isEmpty())
        {
            map<String,String> keyWithPrimaryCustomer = new map<String,String>();
            map<String,String> keyWithSubStockiest = new map<String,String>();
            for(Product_Mapping__c pm :secondaryMappings)
            {
                keyWithPrimaryCustomer.put(pm.Customer_Executive_Pair__c,pm.Primary_Customer__c);
                if(pm.Sub_Stockiest__c != null)
                {
                    keyWithSubStockiest.put(pm.Customer_Executive_Pair__c,pm.Sub_Stockiest__c);
                }
            }
            
            map<String,String> secondaryCustomerWithPrimaryCustomer = new map<String,String>();
            map<String,String> secondaryCustomerWithSubStockiest = new map<String,String>();
            for(Product_Mapping__c pm :allsecondaryMappings)
            {
                secondaryCustomerWithPrimaryCustomer.put(pm.Customer__c,pm.Primary_Customer__c);
                if(pm.Sub_Stockiest__c != null)
                {
                    secondaryCustomerWithSubStockiest.put(pm.Customer__c,pm.Sub_Stockiest__c);
                }
            }
            
            for(Return__c rtn : newReturns) {
                if(rtn.Customer__c !=null && rtn.Customer_Type__c == 'Secondary Customer')
                {
                    string key = rtn.Customer__c +'-'+rtn.OwnerId;
                    if(keyWithPrimaryCustomer.containsKey(key))
                    {
                        string DistributorId =  keyWithPrimaryCustomer.get(key);
                        rtn.Distributor__c = DistributorId;
                    }
                    else if(secondaryCustomerWithPrimaryCustomer.containsKey(rtn.Customer__c))
                    {
                        string DistributorId =  secondaryCustomerWithPrimaryCustomer.get(rtn.Customer__c);
                        rtn.Distributor__c = DistributorId;
                    }
                    
                    
                    if(keyWithSubStockiest.containsKey(key))
                    {
                        string subStockiestId =  keyWithSubStockiest.get(key);
                        rtn.Sub_Stockiest__c = subStockiestId;
                    }
                    else if(secondaryCustomerWithPrimaryCustomer.containsKey(rtn.Customer__c))
                    {
                        string subStockiestId =  secondaryCustomerWithSubStockiest.get(rtn.Customer__c);
                        rtn.Sub_Stockiest__c = subStockiestId;
                    }
                }
                
            }
            
        }
        
    }
    public static void afterInsert(List<Return__c> newReturns) {
        Set<String> uniqueFileIds = new Set<String>();
        Map<String, Id> idMap = new Map<String, Id>();
        Set<Id> userIds = new Set<Id>();
        set<String> customerCodes = new set<String>();
        set<String> customerWithExecutiveIds = new set<String>();
        // Collect all unique file IDs from new accounts
        for (Return__c dl : newReturns) {
            userIds.add(dl.OwnerId);
            if (dl.UniqueFileId__c != null) {
                uniqueFileIds.add(dl.UniqueFileId__c);
                idMap.put(dl.UniqueFileId__c, dl.Id);
            }
        }
        
        CustomSharingService.linkFilesToRecords(uniqueFileIds, idMap);
        if(!userIds.isEmpty())
        {
            updateReturnCount(userIds);
        }
        
    }
    public static void afterDelete(List<Return__c> oldReturns)
    {
        Set<Id> userIds = new Set<Id>();
        for(Return__c col: oldReturns)
        {
            userIds.add(col.OwnerId);
        }
        if(!userIds.isEmpty())
        {
            updateReturnCount(userIds);
        }
    }
    public static void updateReturnCount(Set<Id> userIds)
    {
        // Maps with userId → count of returns created today
        Map<Id, Integer> returnCountMap = new Map<Id, Integer>();
        
        for (AggregateResult ar : [ SELECT OwnerId ownerId, COUNT(Id) returnCount
                                   FROM Return__c WHERE OwnerId IN :userIds AND Return_Date__c = TODAY GROUP BY OwnerId
                                  ]) {
                                      Id ownerId = (Id) ar.get('ownerId');
                                      Integer returnCount = (Integer) ar.get('returnCount');
                                      returnCountMap.put( ownerId, (returnCountMap.containsKey(ownerId) ? returnCountMap.get(ownerId) : 0) + returnCount);
                                  }
        
        // Query daily logs for those users
        List<Daily_Log__c> dailyLogs = [SELECT Id, OwnerId, Date__c FROM Daily_Log__c WHERE OwnerId IN :userIds AND Date__c = TODAY ];
        
        List<Daily_Log__c> logsToUpdate = new List<Daily_Log__c>();
        for (Daily_Log__c dl : dailyLogs) {
            dl.Return_Calls__c = returnCountMap.get(dl.OwnerId) != null ? returnCountMap.get(dl.OwnerId) : 0;
            logsToUpdate.add(dl);
        }
        
        if (!logsToUpdate.isEmpty()) { update logsToUpdate;} 
    }
}