force-app/main/default/objects/Daily_Log__c/Daily_Log__c.object-meta.xml
<CustomObject>
    <label>Daily Attendance</label>
    <nameField>
        <displayFormat>Log Id - {00000}</displayFormat>
        <label>Log Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Attendances</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Log__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Daily_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Daily_Log__c/fields/Day_started_time__c.field-meta.xml
<CustomField>
    <fullName>Day_started_time__c</fullName>
    <label>Day started time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Daily_Log__c/fields/Employee_Code__c.field-meta.xml
<CustomField>
    <fullName>Employee_Code__c</fullName>
    <formula>Owner:User.Employee_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Employee Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order Request</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Order Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Account)</relationshipLabel>
    <relationshipName>Orders2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Customer_type__c.field-meta.xml
<CustomField>
    <fullName>Customer_type__c</fullName>
    <label>Customer type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary Customer</fullName>
            </value>
            <value>
                <fullName>Secondary Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Distance__c.field-meta.xml
<CustomField>
    <fullName>Distance__c</fullName>
    <formula>IF(
    AND(
        NOT(ISBLANK(Clock_In_Location__Latitude__s)),
        NOT(ISBLANK(Clock_In_Location__Longitude__s)),
        Clock_In_Location__Latitude__s &lt;&gt; 0,
        Clock_In_Location__Longitude__s &lt;&gt; 0,
        NOT(ISBLANK(Customer_Location__Latitude__s)),
        NOT(ISBLANK(Customer_Location__Longitude__s)),
        Customer_Location__Latitude__s &lt;&gt; 0,
        Customer_Location__Longitude__s &lt;&gt; 0
    ),
    DISTANCE(
        GEOLOCATION(Customer_Location__Latitude__s, Customer_Location__Longitude__s),
        GEOLOCATION(Clock_In_Location__Latitude__s, Clock_In_Location__Longitude__s),
        &apos;km&apos;
    ),
    0
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Distance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/DISTRICT__c.field-meta.xml
<CustomField>
    <fullName>DISTRICT__c</fullName>
    <formula>TEXT(Account__r.District__c)</formula>
    <label>DISTRICT</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Executive__c.field-meta.xml
<CustomField>
    <fullName>Executive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Executive</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Order_Fulfillment_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Fulfillment_Status__c</fullName>
    <label>Order Fulfillment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>order_status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <label>Customer Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary Order</fullName>
            </value>
            <value>
                <fullName>Secondary Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Order_Status1</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Visit__c.field-meta.xml
<CustomField>
    <fullName>Visit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Visit</label>
    <referenceTo>Visit__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>RE - {00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <formula>IF(
  Text(Order__r.Order_Type__c) = &apos;Primary Order&apos;,
  &apos;Primary&apos;,
  IF(
    Text(Order__r.Account__r.Secondary_Customer_Type__c) = &apos;Sub Stockiest&apos;,
    &apos;Sub Stockiest&apos;,
    &apos;Outlet&apos;
  )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Daily_log__c.field-meta.xml
<CustomField>
    <fullName>Daily_log__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Daily log</label>
    <referenceTo>DailyLog__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order_Date__c.field-meta.xml
<CustomField>
    <fullName>Order_Date__c</fullName>
    <formula>Order__r.Order_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>order_status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Tax_Amount__c.field-meta.xml
<CustomField>
    <fullName>Tax_Amount__c</fullName>
    <label>Tax Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Unit_price__c.field-meta.xml
<CustomField>
    <fullName>Unit_price__c</fullName>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Visit__c.field-meta.xml
<CustomField>
    <fullName>Visit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Visit</label>
    <referenceTo>Visit__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/SKU_Code__c.field-meta.xml
<CustomField>
    <fullName>SKU_Code__c</fullName>
    <externalId>true</externalId>
    <label>SKU Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit - {00000000}</displayFormat>
        <label>Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Actual_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Actual_Start_Time__c</fullName>
    <label>Actual Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/ClockIn_Latitude__c.field-meta.xml
<CustomField>
    <fullName>ClockIn_Latitude__c</fullName>
    <label>ClockIn Latitude</label>
    <precision>8</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Clockin_Longitude__c.field-meta.xml
<CustomField>
    <fullName>Clockin_Longitude__c</fullName>
    <label>Clockin Longitude</label>
    <precision>8</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <formula>IF(TEXT(Account1__r.Customer_Type__c ) ==&apos;Primary Customer&apos;,  TEXT(Account1__r.Primary_Customer_Type__c), TEXT(Account1__r.Secondary_Customer_Type__c) )</formula>
    <label>Customer Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <isActive>false</isActive>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>PostPone</fullName>
                <isActive>false</isActive>
                <label>PostPone</label>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
                <isActive>false</isActive>
                <label>Rescheduled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OrderTriggerHandlerTest.cls
@isTest
public class OrderTriggerHandlerTest {
    
    @isTest
    public static void testClassMethod(){
        Test.startTest();
        Profile p = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];
        User u = new User(
            FirstName = 'Test',
            LastName = 'User11',
            Email = 'visituser111@test.com',
            Username = 'visituser' + System.currentTimeMillis() + '@test.com',
            Alias = 'vusr',
            Employee_Code__c  = 'sjkhjkj18118',
            ProfileId = p.Id,
            TimeZoneSidKey = 'Asia/Kolkata',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US'
        );
        insert u;
        
        Product__c prod = new Product__c(Name='Test Product',SKU_Code__c ='1010sksksk');
        insert prod;
        
        Account acc = new Account(
            Name = 'Primary Customer',
            Customer_Type__c = 'Primary Customer',
            Pincode__c = '123456',
            Primary_Phone_Number__c = '9876543210',
            State__c = 'Karnataka',
            District__c = 'Kolar'
        );
        insert acc;
        
        // Primary Order
        Order__c order = new Order__c(
            Order_Type__c = 'Primary Order',
            Account__c = acc.Id,
            OwnerId = u.Id,
            Order_Fulfillment_Status__c = 'Not Fulfilled',
            Order_Date__c = Date.today()
        );
        insert order;

        List<Order_Item__c> items = new List<Order_Item__c>();
        for (Integer i = 0; i < 2; i++) {
            items.add(new Order_Item__c(
                Order__c = order.Id,
                Product__c = prod.Id,
                Quantity__c = 10,
                Delivered_Quantity__c = 0,
                Unit_Price__c = 100,
                Total_Amount__c = 1000,
                Tax_Amount__c = 100,
                Status__c = 'Not Fulfilled'
            ));
        }
        insert items;
        
        // Secondary Order
        Order__c order1 = new Order__c(
            Order_Type__c = 'Secondary Order',
            Account__c = acc.Id,
            Status__c = 'New',
            OwnerId = u.Id,
            Order_Fulfillment_Status__c = 'Not Fulfilled',
            Order_Date__c = Date.today(),
            Executive__c = userInfo.getUserId()
        );
        insert order1;
        
        List<Order_Item__c> items1 = new List<Order_Item__c>();
        for (Integer i = 0; i < 2; i++) {
            items1.add(new Order_Item__c(
                Order__c = order1.Id,
                Product__c = prod.Id,
                Quantity__c = 10,
                Delivered_Quantity__c = 0,
                Unit_Price__c = 100,
                Total_Amount__c = 1000,
                Tax_Amount__c = 100,
                Status__c = 'Not Fulfilled'
            ));
        }
        insert items1;
        
     
        
        // Call the handler
        OrderItemTriggerHandler.updateOrderAmount(items1);
        
        Test.stopTest();
        
  
    }
     @isTest
    public static void testClassMethod1(){
        Test.startTest();
        
        Profile p = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];
        User u = new User(
            FirstName = 'Test',
            LastName = 'User11',
            Email = 'visituserSS111@test.com',
            Username = 'visituser' + System.currentTimeMillis() + '@test.com',
            Alias = 'vusr',
            Employee_Code__c  = 'sjkhjkj18118',
            ProfileId = p.Id,
            TimeZoneSidKey = 'Asia/Kolkata',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US'
        );
        insert u;
        
        Product__c prod = new Product__c(Name='Test Product',SKU_Code__c ='10DD10sksksk');
        insert prod;
        
        Account acc = new Account(
            Name = 'Primary Customer',
            Customer_Type__c = 'Primary Customer',
            Pincode__c = '123456',
            Primary_Phone_Number__c = '9876543210',
            State__c = 'Karnataka',
            District__c = 'Kolar'
        );
        insert acc;
        
        // Primary Order
        Order__c order = new Order__c(
            Order_Type__c = 'Primary Order',
            Account__c = acc.Id,
            OwnerId = u.Id,
            Order_Fulfillment_Status__c = 'Not Fulfilled',
            Order_Date__c = Date.today(),
            Executive__c = userInfo.getUserId()
        );
        insert order;

        List<Order_Item__c> items = new List<Order_Item__c>();
        for (Integer i = 0; i < 2; i++) {
            items.add(new Order_Item__c(
                Order__c = order.Id,
                Product__c = prod.Id,
                Quantity__c = 10,
                Delivered_Quantity__c = 0,
                Unit_Price__c = 100,
                Total_Amount__c = 1000,
                Tax_Amount__c = 100,
                Status__c = 'Not Fulfilled'
            ));
        }
        insert items;
        delete items[0];
        items[1].Quantity__c = 12;
        update   items[1];
        // Create a Daily Log record
        Daily_Log__c log = new Daily_Log__c();
        log.Day_started_time__c = Date.today().addDays(-1);
        log.Clock_Out_Location__Longitude__s =37.7749;
        log.Clock_Out_Location__Latitude__s = 78.4194;
        insert log;
        
            
        // Create Visit record with key fields
        Visit__c visit = new Visit__c(
            //OwnerId = u.Id,
            UniqueFileId__c = 'fileKey123',
            ClockIn_Latitude__c = 12.9716,
            Clockin_Longitude__c = 77.5946,
            Actual_Start_Time__c = System.now(),
            Distance__c = 10,
            Daily_log__c = log.Id
        );
        
       
        insert visit;  
        // Secondary Order
        Order__c order1 = new Order__c(
            Order_Type__c = 'Secondary Order',
            Account__c = acc.Id,
            visit__C = visit.id,
            OwnerId = u.Id,
            Order_Fulfillment_Status__c = 'Not Fulfilled',
            Order_Date__c = Date.today()
        );
        insert order1;
        
            // Secondary Order
        Order__c order2 = new Order__c(
            Order_Type__c = 'Secondary Order',
            Account__c = acc.Id,
            visit__C = visit.id,
            OwnerId = u.Id,
            Order_Fulfillment_Status__c = 'Not Fulfilled',
            Order_Date__c = Date.today()
        );
        insert order2;
        
        delete order1;
        DailyLogOrderAmountBatch bt = new DailyLogOrderAmountBatch();
        database.executeBatch(bt,200);
        
        
        Test.stopTest();
        
  
    }
    
}