force-app/main/default/objects/Secondary_Credit_Note__c/Secondary_Credit_Note__c.object-meta.xml
<CustomObject>
    <label>Secondary Credit Note</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Secondary Credit Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Secondary Credit Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Secondary_Credit_Note__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Secondary Credit Notes</relationshipLabel>
    <relationshipName>Secondary_Credit_Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Secondary_Credit_Note__c/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Secondary Credit Notes (Distributor)</relationshipLabel>
    <relationshipName>Secondary_Credit_Notes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SecondaryCreditNoteSharingBatch.cls
public class SecondaryCreditNoteSharingBatch implements Database.Batchable<SObject> {

    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([
            SELECT Id, Distributor__c, Customer__c
            FROM Secondary_Credit_Note__c
            WHERE Distributor__c != null AND Customer__c != null
        ]);
    }

    public void execute(Database.BatchableContext bc, List<Secondary_Credit_Note__c> scope) {
        SecondaryCreditNoteSharingHandler.shareCustomerAccountsWithDistributorUsers(scope);
    }

    public void finish(Database.BatchableContext bc) {
        System.debug('SecondaryCreditNoteSharingBatch completed.');
    }
}