force-app/main/default/objects/Secondary_Invoice__c/Secondary_Invoice__c.object-meta.xml
<CustomObject>
    <label>Secondary Invoice</label>
    <nameField>
        <displayFormat>{YYYY} / {MM} / {0000}</displayFormat>
        <label>Secondary Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Secondary Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Secondary_Invoice__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Secondary Invoices (Customer)</relationshipLabel>
    <relationshipName>Secondary_Invoices1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Secondary_Invoice__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.Customer_Type__c</field>
            <operation>equals</operation>
            <value>Dealer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Secondary Invoices</relationshipLabel>
    <relationshipName>Secondary_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SecondaryInvoiceSharingBatch.cls
public class SecondaryInvoiceSharingBatch implements Database.Batchable<SObject> {

    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([
            SELECT Id, Store__c, Customer__c
            FROM Secondary_Invoice__c
            WHERE Store__c != null AND Customer__c != null
        ]);
    }

    public void execute(Database.BatchableContext bc, List<Secondary_Invoice__c> scope) {
        SecondaryInvoiceSharingHandler.shareCustomerAccountsWithDistributorUsers(scope);
    }

    public void finish(Database.BatchableContext bc) {
        System.debug('SecondaryInvoiceSharingBatch completed.');
    }
}