force-app/main/default/objects/Incentive_Slab__c/Incentive_Slab__c.object-meta.xml
<CustomObject>
    <label>Incentive Slab</label>
    <nameField>
        <displayFormat>IS-{000}</displayFormat>
        <label>Incentive Slab Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Incentive Slabs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Incentive_Slab__c/fields/Achievement_From__c.field-meta.xml
<CustomField>
    <fullName>Achievement_From__c</fullName>
    <label>Achievement From</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Incentive_Slab__c/fields/Achievement_To__c.field-meta.xml
<CustomField>
    <fullName>Achievement_To__c</fullName>
    <label>Achievement To</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Incentive_Slab__c/fields/Incentive_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Incentive_Percentage__c</fullName>
    <label>Incentive Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Incentive_Slab__c/fields/Target_Plan__c.field-meta.xml
<CustomField>
    <fullName>Target_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Target Plan</label>
    <referenceTo>Target_Plan__c</referenceTo>
    <relationshipLabel>Incentive Slabs</relationshipLabel>
    <relationshipName>Incentive_Slabs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Product_Category1__c.field-meta.xml
<CustomField>
    <fullName>Product_Category1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Category</label>
    <referenceTo>Product_Category__c</referenceTo>
    <relationshipName>Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product_category__c.field-meta.xml
<CustomField>
    <fullName>Product_category__c</fullName>
    <label>Product category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Selling_Category__c.field-meta.xml
<CustomField>
    <fullName>Selling_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Selling Category</label>
    <referenceTo>Selling_Category__c</referenceTo>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Category__c/Product_Category__c.object-meta.xml
<CustomObject>
    <label>Product Category</label>
    <nameField>
        <label>Product Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Category__c/fields/Selling_Category__c.field-meta.xml
<CustomField>
    <fullName>Selling_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Selling Category</label>
    <referenceTo>Selling_Category__c</referenceTo>
    <relationshipLabel>Product Categories</relationshipLabel>
    <relationshipName>Product_Categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Target__c/Target__c.object-meta.xml
<CustomObject>
    <label>NotUsed_Target</label>
    <nameField>
        <displayFormat>TR{00}</displayFormat>
        <label>Target</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NotUsed_Target</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Target__c/fields/Period__c.field-meta.xml
<CustomField>
    <fullName>Period__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Period</label>
    <referenceTo>Period__c</referenceTo>
    <relationshipName>Target</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Target_Item__c/Target_Item__c.object-meta.xml
<CustomObject>
    <label>NotUsed_Target Item</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Target Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NotUsed_Target Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Target_Item__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <referenceTo>Target_Item__c</referenceTo>
    <relationshipName>Target_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Target_Item__c/fields/Target__c.field-meta.xml
<CustomField>
    <fullName>Target__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Target</label>
    <referenceTo>Target__c</referenceTo>
    <relationshipName>Target_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Target_Item__c/fields/Target_Logic__c.field-meta.xml
<CustomField>
    <fullName>Target_Logic__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Target Logic</label>
    <referenceTo>Target_Logic__c</referenceTo>
    <relationshipName>Target_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Target_Logic__c/Target_Logic__c.object-meta.xml
<CustomObject>
    <label>NotUsed_Target Logic</label>
    <nameField>
        <label>Target Logic Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NotUsed_Target Logics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Target_Logic__c/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Target_Logic__c/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <label>Field</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Object__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Grand_Total__c</fullName>
                <label>Grand Total</label>
            </value>
            <value>
                <fullName>Total_Quantity__c</fullName>
                <label>Total Quantity</label>
            </value>
            <value>
                <fullName>Total_Amount__c</fullName>
                <label>Total Amount</label>
            </value>
            <value>
                <fullName>Quantity__c</fullName>
                <label>Quantity</label>
            </value>
            <value>
                <fullName>Id</fullName>
            </value>
            <value>
                <fullName>Account1__c</fullName>
                <label>Account</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Target_Logic__c/fields/Formula__c.field-meta.xml
<CustomField>
    <fullName>Formula__c</fullName>
    <label>Formula</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Target_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SUM</fullName>
            </value>
            <value>
                <fullName>COUNT</fullName>
            </value>
            <value>
                <fullName>COUNT_DISTINCT</fullName>
                <label>Unique Count</label>
            </value>
            <value>
                <fullName>AVG</fullName>
                <isActive>false</isActive>
                <label>AVG</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Target_Logic__c/fields/max_incentive__c.field-meta.xml
<CustomField>
    <fullName>max_incentive__c</fullName>
    <label>Max Incentive</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Target_Logic__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Formula__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invoice__c</fullName>
                <label>Invoice</label>
            </value>
            <value>
                <fullName>Invoice_item__c</fullName>
                <label>Invoice Item</label>
            </value>
            <value>
                <fullName>Visit__c</fullName>
                <label>Visit</label>
            </value>
            <value>
                <fullName>Account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Target_Logic__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipName>Target_Logics</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Target_Logic__c/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Category</label>
    <referenceTo>Product_Category__c</referenceTo>
    <relationshipName>Target_Logics</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Target_Logic__c/fields/Selling_Category__c.field-meta.xml
<CustomField>
    <fullName>Selling_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Selling Category</label>
    <referenceTo>Selling_Category__c</referenceTo>
    <relationshipName>Target_Logics</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Target_Logic__c/fields/Target_Plan__c.field-meta.xml
<CustomField>
    <fullName>Target_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Target Plan</label>
    <referenceTo>Target_Plan__c</referenceTo>
    <relationshipName>Target_Logics</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Target_Logic__c/fields/Target_Type__c.field-meta.xml
<CustomField>
    <fullName>Target_Type__c</fullName>
    <label>Target Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Target_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Target_Logic__c/fields/Weightage__c.field-meta.xml
<CustomField>
    <fullName>Weightage__c</fullName>
    <label>Weightage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Target_Plan__c/Target_Plan__c.object-meta.xml
<CustomObject>
    <label>NotUsed_Target Plan</label>
    <nameField>
        <displayFormat>TP-{000}</displayFormat>
        <label>Target Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NotUsed_Target Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Target_Plan__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Division</label>
    <referenceTo>Division__c</referenceTo>
    <relationshipName>Target_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Target_Plan__c/fields/Incentive_Type__c.field-meta.xml
<CustomField>
    <fullName>Incentive_Type__c</fullName>
    <label>Incentive Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Variable Pay</fullName>
            </value>
            <value>
                <fullName>Basic Pay</fullName>
            </value>
            <value>
                <fullName>Actual Amount</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Target_Plan__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Region</label>
    <referenceTo>Region__c</referenceTo>
    <relationshipName>Target_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TargetPlanController.cls
public class TargetPlanController {
    public class Databox{ 
        @AuraEnabled
        public list<Product_Category__c> productCategoryList = new list<Product_Category__c>();
        @AuraEnabled
        public list<Selling_Category__c> sellingCategoryList = new list<Selling_Category__c>();
        @AuraEnabled
        public list<Product__c> productList = new list<Product__c>();
        @AuraEnabled
        public list<Region__c> regionList = new list<Region__c>();
        @AuraEnabled
        public list<Division__c> divisionList = new list<Division__c>();
        @AuraEnabled
        public List<Map<String, String>> incentiveType = new List<Map<String, String>> ();
        @AuraEnabled
        public List<Map<String, String>> targetType = new List<Map<String, String>> ();
        @AuraEnabled
        public List<Map<String, String>> accountType = new List<Map<String, String>> ();

        @AuraEnabled
        public Map<String, Map<String, String>> targetTypeObjectMap = new  Map<String, Map<String, String>>();
        @AuraEnabled
        public Map<String, Map<String, String>> formulaObjectMap = new  Map<String, Map<String, String>>();
        @AuraEnabled
        public Map<String, Map<String, String>> objectFieldMap = new  Map<String, Map<String, String>>();
        
        @AuraEnabled
        public Target_Plan__c targetPlan = new Target_Plan__c();
        @AuraEnabled
        public list<Target_Logic__c> targetLogicList = new list<Target_Logic__c>();
        @AuraEnabled
        public list<Incentive_Slab__c> incentiveSlabList = new list<Incentive_Slab__c>();
        @AuraEnabled
        public String recordAction = '';
        @AuraEnabled
        public String recordId = '';
        @AuraEnabled
        public String recordName = '';
    }

    @AuraEnabled
    public static Databox getAllData(string recordId) {
        Map<String, Object> picklistData = new Map<String, Object>();
		Databox dx = new Databox();
        dx.productCategoryList = [select Id,Name from Product_Category__c where Active__c = true];
        dx.productList = [select Id,Name,Product_Category1__c from Product__c where Is_Active__c = true];
        dx.regionList = [select Id,Name from Region__c where Active__c = true];
        dx.sellingCategoryList = [select Id,Name from Selling_Category__c];
        dx.divisionList = [select Id,Name from Division__c where Active__c = true];
        dx.incentiveType = extractPicklistValues('Target_Plan__c','Incentive_Type__c');
        dx.targetType = extractPicklistValues('Target_Logic__c','Target_Type__c');
        dx.accountType = extractPicklistValues('Target_Logic__c','Account_Type__c');
       
        // Fetch dependent picklist values (Formula → Object, Object → Field)
        dx.targetTypeObjectMap =  getDependentMap(new Target_Logic__c(), 'Target_Type__c', 'Formula__c');
        dx.formulaObjectMap = getDependentMap(new Target_Logic__c(), 'Formula__c', 'Object__c');
        dx.objectFieldMap = getDependentMap(new Target_Logic__c(), 'Object__c', 'Field__c');
        
        if(recordId != null && recordId != '')
        {
        	dx.targetPlan = [select Id,Name,Region__c,Division__c,Active__c,Incentive_Type__c from Target_Plan__c where Id =:recordId];
            dx.targetLogicList = [select Id,Name,Target_Type__c,Formula__c,Object__c,Field__c,Weightage__c,max_incentive__c,
                                  Account_Type__c,Product_Category__c,Product_Category__r.Name,Product__c,Product__r.Name,
                                  Target_Plan__c,Selling_Category__c,Selling_Category__r.Name
                                  from Target_Logic__c where Target_Plan__c =:recordId];
            dx.incentiveSlabList = [select Id,Name,Achievement_From__c,Achievement_To__c,Incentive_Percentage__c,
                                    Incentive_Amount__c,Target_Plan__c from Incentive_Slab__c where Target_Plan__c =:recordId];
        }
        
        return dx;      
    }
    
    @AuraEnabled
    public static Map<String, Map<String, String>> getDependentMap(SObject objDetail, String contrFieldApiName, String depFieldApiName) {
        System.debug('Fetching dependent picklist values...');
        
        Map<String, Map<String, String>> objResults = new Map<String, Map<String, String>>();
        
        Schema.sObjectType objType = objDetail.getSObjectType();
        if (objType == null) return objResults;
        
        Map<String, Schema.SObjectField> objFieldMap = objType.getDescribe().fields.getMap();
        if (!objFieldMap.containsKey(contrFieldApiName) || !objFieldMap.containsKey(depFieldApiName)) return objResults;
        
        Schema.SObjectField ctrlField = objFieldMap.get(contrFieldApiName);
        Schema.SObjectField depField = objFieldMap.get(depFieldApiName);
        
        List<Schema.PicklistEntry> ctrlEntries = ctrlField.getDescribe().getPicklistValues();
        List<PicklistEntryWrapper> depEntries = wrapPicklistEntries(depField.getDescribe().getPicklistValues());
        
        List<String> ctrlValues = new List<String>();
        for (Schema.PicklistEntry ple : ctrlEntries) {
            String label = ple.getLabel();
            String value = ple.getValue();
            objResults.put(value, new Map<String, String>());
            ctrlValues.add(value);
        }
        
        Integer index = 0;
        for (PicklistEntryWrapper depEntry : depEntries) {
            String depLabel = depEntry.label;
            String depValue = depEntry.value;
            String validForBits = base64ToBits(depEntry.validFor);
            
            for (Integer i = 0; i < validForBits.length(); i++) {
                if (validForBits.mid(i, 1) == '1') {
                    objResults.get(ctrlValues.get(i)).put(depLabel, depValue);
                }
            }
        }
 
        
        return objResults;
    }
    

    private static List<Map<String, String>> extractPicklistValues(String objectName, String fieldName) {
        // Get the global describe map
        Map<String, Schema.SObjectType> schemaMap = Schema.getGlobalDescribe();
        
        // Check if the object exists
        if (!schemaMap.containsKey(objectName)) {
            return new List<Map<String, String>>();
        }
        
        Schema.DescribeSObjectResult objDescribe = schemaMap.get(objectName).getDescribe();
        Map<String, Schema.SObjectField> fieldMap = objDescribe.fields.getMap();
        
        // Check if the field exists in the object
        if (!fieldMap.containsKey(fieldName)) {
            return new List<Map<String, String>>();
        }
        
        Schema.DescribeFieldResult fieldResult = fieldMap.get(fieldName).getDescribe();
        List<Map<String, String>> picklistValues = new List<Map<String, String>>();
        
        if (fieldResult != null && fieldResult.getType() == Schema.DisplayType.Picklist) {
            for (Schema.PicklistEntry entry : fieldResult.getPicklistValues()) {
                picklistValues.add(new Map<String, String>{
                    'label' => entry.getLabel(),
                        'value' => entry.getValue()
                        });
            }
        }
        return picklistValues;
    }
    

    public static String base64ToBits(String validFor) {
        if (String.isEmpty(validFor)) return '';
        String validForBits = '';

        for (Integer i = 0; i < validFor.length(); i++) {
            Integer val = base64Chars.indexOf(validFor.mid(i, 1));
            validForBits += decimalToBinary(val).leftPad(6, '0');
        }
        return validForBits;
    }

    private static final String base64Chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';

    public static String decimalToBinary(Integer val) {
        String bits = '';
        while (val > 0) {
            bits = String.valueOf(Math.mod(val, 2)) + bits;
            val = val / 2;
        }
        return bits;
    }

    private static List<PicklistEntryWrapper> wrapPicklistEntries(List<Schema.PicklistEntry> PLEs) {
        return (List<PicklistEntryWrapper>) JSON.deserialize(JSON.serialize(PLEs), List<PicklistEntryWrapper>.class);
    }

    public class PicklistEntryWrapper {
        public String label {get;set;}
        public String value {get;set;}
        public String validFor {get;set;}
    }
    
    @AuraEnabled
    public static Databox saveData(Target_Plan__c targetPlan, List<Target_Logic__c> targetLogicList, List<Incentive_Slab__c> slabs, List<string> deleteLogicsList, List<string> deleteSlabsList) {
        try {
            Databox dx = new Databox();
            
            // 1. Same Region, Division, Incentive Type – Allow only one target plan
            List<Target_Plan__c> existingTargetPlan = [
                SELECT Id, Name 
                FROM Target_Plan__c 
                WHERE Region__c = :targetPlan.Region__c 
                AND Division__c = :targetPlan.Division__c
                AND Incentive_Type__c = :targetPlan.Incentive_Type__c
                AND Id != :targetPlan.Id
                LIMIT 1
            ];
            
            if (!existingTargetPlan.isEmpty()) {
                dx.recordId = null;
                dx.recordName = existingTargetPlan[0].Name;
                dx.recordAction = 'Duplicate';
                return dx;
            }
            
            // 2. One active target plan for one Region-Division combination
            if (targetPlan.Active__c) {
                List<Target_Plan__c> activeTargetPlans = [
                    SELECT Id, Name 
                    FROM Target_Plan__c 
                    WHERE Region__c = :targetPlan.Region__c 
                    AND Division__c = :targetPlan.Division__c
                    AND Active__c = true
                    AND Id != :targetPlan.Id
                    LIMIT 1
                ];
                if (!activeTargetPlans.isEmpty()) {
                    dx.recordId = null;
                    dx.recordName = activeTargetPlans[0].Name;
                    dx.recordAction = 'Cannot Activate';
                    return dx;
                }
            }
            
            // 3. Prevent deactivation if connected Target Items exist
            if (targetPlan.Active__c == false && targetPlan.Id != null) {
                 Period__c per = [select id, Start_Date__c, End_Date__c  from Period__c where Start_Date__c <= TODAY and End_Date__c>= TODAY];
                List<Target_Logic__c> existingTargetLogics = [
                    SELECT Id, (SELECT Id FROM Target_Items__r where Target__r.Period__c =:per.Id) 
                    FROM Target_Logic__c 
                    WHERE Target_Plan__c = :targetPlan.Id
                ];
                
                for (Target_Logic__c logic : existingTargetLogics) {
                    if (logic.Target_Items__r != null && !logic.Target_Items__r.isEmpty()) {
                        dx.recordId = null;
                        dx.recordName = targetPlan.Name;
                        dx.recordAction = 'Cannot Deactivate';
                        return dx;
                    }
                }
            }
            
            // Delete Target Logics and Slabs
            if (!deleteLogicsList.isEmpty()) {
                List<Target_Logic__c> delLogicsList = [
                    SELECT Id, Name 
                    FROM Target_Logic__c 
                    WHERE Id IN :deleteLogicsList
                ];
                delete delLogicsList;
            }
            
            if (!deleteSlabsList.isEmpty()) {
                List<Incentive_Slab__c> delSlabsList = [
                    SELECT Id, Name 
                    FROM Incentive_Slab__c 
                    WHERE Id IN :deleteSlabsList
                ];
                delete delSlabsList;
            }
            
            // Insert or Update Target Plan
            upsert targetPlan;
            
            // Associate Target Plan ID with Target Logics
            for (Target_Logic__c logic : targetLogicList) {
                logic.Target_Plan__c = targetPlan.Id;
            }
            
            // Associate Target Plan ID with Incentive Slabs
            for (Incentive_Slab__c slab : slabs) {
                slab.Target_Plan__c = targetPlan.Id;
            }
            
            // Insert or Update Logics and Slabs
            if (!targetLogicList.isEmpty()) {
                upsert targetLogicList;
            }
            if (!slabs.isEmpty()) {
                upsert slabs;
            }
            
            dx.recordAction = 'Record Created Successfully';
            dx.recordId = targetPlan.Id;
            dx.recordName = targetPlan.Name;
            return dx;
            
        } catch (Exception e) {
            throw new AuraHandledException('Error while saving data: ' + e.getMessage());
        }
    }

    
}