force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order Request</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Order Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Account)</relationshipLabel>
    <relationshipName>Orders2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Company_Address__c.field-meta.xml
<CustomField>
    <fullName>Company_Address__c</fullName>
    <formula>CASE(
    TEXT(Sales_Organization__c),
    &apos;1300&apos;,&apos;SIDCO Industrial Estate, P.O. Peringandoor, Athani, Thrissur - 680 581, Kerala, India.&apos;,
    &apos;1500&apos;, &apos;Plot No. 21, SIPCOT Industrial Complex, Phase II, Hosur, Tamil Nadu.&apos;,
    &apos;1100&apos;, &apos;Athani, Velappaya P. O Kerala Head Office &amp; Factory, No. 22- A, Development Plot, Peringandoor P. O, Thrissur-680581, Kerala, India&apos;,
    &apos;SIDCO Industrial Estate, P.O. Peringandoor, Athani, Thrissur - 680 581, Kerala, India.&apos;  /* Default */
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Company Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <formula>CASE(
    TEXT(Sales_Organization__c),
				&apos;1300&apos;, &apos;Elite Foods Pvt Ltd.&apos; ,
    &apos;1500&apos;, &apos;Elite Natural Pvt Ltd.&apos;,
    &apos;1100&apos;, &apos;Yamuna Roller Flour Mills Pvt Ltd&apos;,
    &apos;Elite Foods Pvt Ltd.&apos;  /* Default */
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Company Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Delivery_To__c.field-meta.xml
<CustomField>
    <fullName>Delivery_To__c</fullName>
    <label>Delivery To</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>RE - {00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order_Date__c.field-meta.xml
<CustomField>
    <fullName>Order_Date__c</fullName>
    <formula>Order__r.Order_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Tax__c.field-meta.xml
<CustomField>
    <fullName>Tax__c</fullName>
    <label>Tax(%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Tax_Amount__c.field-meta.xml
<CustomField>
    <fullName>Tax_Amount__c</fullName>
    <label>Tax Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Unit_price__c.field-meta.xml
<CustomField>
    <fullName>Unit_price__c</fullName>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/OrderPdfController.cls
public class OrderPdfController {
    public Id recid { get; set; }
    public List<OrderWapper> oItemList { get; set; }
    public String customerName { get; set; }
    public String orderNo { get; set; }
    public String orderDate { get; set; }
    public String deliveredTo { get; set; }
    public String expectedDelivaryDate { get; set; }
    public Decimal totalQuantity { get; set; }
    public Decimal totalAmount { get; set; }
    public String ownerName { get; set; }
    public string finalAmtinWords {get;set;}
    public string companyName {get;set;}
    public string companyAddress {get;set;}
    
    
    public OrderPdfController(ApexPages.StandardController controller) { 
        recid = ApexPages.currentPage().getParameters().get('id');
        NumberTOWordConvertion nwcObj = new NumberTOWordConvertion();
        // Fetch related order Items
        List<Order_Item__c> orderItemList = [
            SELECT Id,Name,	Product__r.Name,Quantity__c,Unit_price__c,Tax_Percent__c,Tax__c,Total_Amount__c,Order__r.Order_Date__c,
            Order__r.Account__r.Name,Order__r.Owner_Name__c,Order__r.Name,Order__r.Expected_Delivery_Date__c,	Order__r.Delivery_To__c,Tax_Amount__c,
            Order__r.Company_Address__c,Order__r.Company_Name__c FROM Order_Item__c WHERE Order__c = :recid
        ];
        
        oItemList = new List<OrderWapper>();
        totalQuantity = 0.0;
        totalAmount = 0.0;
        
        if (!orderItemList.isEmpty()) {
            // Populate header-level fields from the first record
            customerName = orderItemList[0].Order__r.Account__r.Name;
            orderNo = orderItemList[0].Order__r.Name;
            companyName = orderItemList[0].order__r.Company_Name__c;
            companyAddress = orderItemList[0].Order__r.Company_Address__c;
            ApexPages.currentPage().getHeaders()
                .put('Content-Disposition', 'attachment; filename="' + orderNo + '.pdf"');
            deliveredTo = orderItemList[0].Order__r.Delivery_To__c;
            if (orderItemList[0].Order__r.Order_Date__c != null) {
                Date myDate = orderItemList[0].Order__r.Order_Date__c;
                DateTime myDT = DateTime.newInstance(myDate.year(), myDate.month(), myDate.day());
                orderDate = myDT.format('MMMM dd, yyyy');
            } else {
                orderDate = '';
            }
            
            if (orderItemList[0].Order__r.Expected_Delivery_Date__c != null) {
                Date myDate = orderItemList[0].Order__r.Expected_Delivery_Date__c;
                DateTime myDT = DateTime.newInstance(myDate.year(), myDate.month(), myDate.day());
                expectedDelivaryDate = myDT.format('MMMM dd, yyyy');
            } else {
                expectedDelivaryDate = '';
            }
            
            
            
            
            ownerName =  orderItemList[0].Order__r.Owner_Name__c;
            integer i = 1;
            for (Order_Item__c orderItem : orderItemList) {
                OrderWapper oItem = new OrderWapper();
                oItem.index = i++;
                oItem.skuName = orderItem.Product__r.Name;
                oItem.quantity = orderItem.Quantity__c;
                oItem.unitPrice = orderItem.Unit_price__c;
                oItem.taxpercent = orderItem.Tax__c;
                oItem.taxAmount = orderItem.Tax_Amount__c;
                
                oItem.totalAmount = orderItem.Total_Amount__c;
                if(orderItem.Quantity__c != null)
                {
                    totalQuantity += orderItem.Quantity__c;
                }
                if(orderItem.Total_Amount__c != null )
                {
                    totalAmount += orderItem.Total_Amount__c;
                }
                oItemList.add(oItem);
            }
            finalAmtinWords = nwcObj.getNumberTOWordConvertion(totalAmount);
        }
    }
    
    public class OrderWapper {
        public Decimal index { get; set; }
        public String skuName { get; set; }
        public Decimal quantity { get; set; }
        public Decimal unitPrice { get; set; }
        public Decimal taxpercent { get; set; }
        public Decimal taxAmount { get; set; }
        public Decimal totalAmount { get; set; }
        
    }
}