force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order Request</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Order Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Account)</relationshipLabel>
    <relationshipName>Orders2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>RE - {00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Delivered_Net_Weight__c.field-meta.xml
<CustomField>
    <fullName>Delivered_Net_Weight__c</fullName>
    <formula>Delivered_Quantity__c * Product__r.Net_Weight__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Delivered Net Weight</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Fulfilled_Quantity_in_Cases__c.field-meta.xml
<CustomField>
    <fullName>Fulfilled_Quantity_in_Cases__c</fullName>
    <formula>Delivered_Quantity__c / Product__r.Uom_Conversion__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fulfilled_Quantity_in_Cases</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/NET_WEIGHT__c.field-meta.xml
<CustomField>
    <fullName>NET_WEIGHT__c</fullName>
    <formula>Quantity__c *  Product__r.Net_Weight__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>NET WEIGHT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Non_Taxable_Order_Value__c.field-meta.xml
<CustomField>
    <fullName>Non_Taxable_Order_Value__c</fullName>
    <formula>Total_Amount__c -  Tax_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Non Taxable Order Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order_Date__c.field-meta.xml
<CustomField>
    <fullName>Order_Date__c</fullName>
    <formula>Order__r.Order_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order_Qty_in_Case__c.field-meta.xml
<CustomField>
    <fullName>Order_Qty_in_Case__c</fullName>
    <formula>Quantity__c / Product__r.Uom_Conversion__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order Qty in Case</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Tax__c.field-meta.xml
<CustomField>
    <fullName>Tax__c</fullName>
    <label>Tax(%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Tax_Amount__c.field-meta.xml
<CustomField>
    <fullName>Tax_Amount__c</fullName>
    <label>Tax Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Unit_price__c.field-meta.xml
<CustomField>
    <fullName>Unit_price__c</fullName>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/TransactionController.cls
public class TransactionController {
    public class OrderItemWrapper {
        @AuraEnabled public Id Id {get; set;}
        @AuraEnabled public String Name {get; set;}
        @AuraEnabled public String recordUrl {get; set;}
        @AuraEnabled public String ProductName {get; set;}
        @AuraEnabled public String productUrl {get; set;}
        @AuraEnabled public Decimal eachQuantity {get; set;}
        @AuraEnabled public Decimal CaseQuantity {get; set;}
        @AuraEnabled public Decimal UnitPrice {get; set;}
        @AuraEnabled public Decimal AmountWithOutTax {get; set;}
        @AuraEnabled public Decimal taxPercent {get; set;}
        @AuraEnabled public Decimal taxAmount {get; set;}
        @AuraEnabled public Decimal totalAmount {get; set;}
        @AuraEnabled public Decimal NetWeight {get; set;}
        @AuraEnabled public Decimal DeliveredQty {get; set;}
        @AuraEnabled public Decimal DeliveredQtyInCases {get; set;}
        @AuraEnabled public Decimal DeliveredNetWeight {get; set;} 
        @AuraEnabled public String OrderName {get; set;}
        @AuraEnabled public Date OrderDate {get; set;}
    }
    
    @AuraEnabled
    public static List<OrderItemWrapper> getOrderItems(Id accountId) {
        List<Order_Item__c> items = [
            SELECT Id, Name, Product__c, Product__r.Name, Quantity__c, Unit_price__c,
                   Tax_Amount__c, Tax__c, Non_Taxable_Order_Value__c, Total_Amount__c, Order_Qty_in_Case__c,
                   NET_WEIGHT__c, Delivered_Quantity__c, Fulfilled_Quantity_in_Cases__c, Delivered_Net_Weight__c,
                   Order__c, Order__r.Name, Order__r.Order_Date__c
            FROM Order_Item__c
            WHERE Order__r.Account__c = :accountId
            ORDER BY Order__r.Order_Date__c DESC limit 50000
        ];
        
        List<OrderItemWrapper> results = new List<OrderItemWrapper>();
        for (Order_Item__c oi : items) {
            OrderItemWrapper w = new OrderItemWrapper();
            w.Id = oi.Id;
            w.Name = oi.Name;
            w.recordUrl = '/' + oi.Id;             
            w.ProductName = oi.Product__r.Name;
            w.productUrl = '/' + oi.Product__c;    
            w.eachQuantity = oi.Quantity__c;
            w.UnitPrice = oi.Unit_price__c;
            w.AmountWithOutTax = oi.Non_Taxable_Order_Value__c;
            w.taxPercent = oi.Tax__c;
            w.taxAmount = oi.Tax_Amount__c;
            w.totalAmount = oi.Total_Amount__c;
            w.CaseQuantity = oi.Order_Qty_in_Case__c;
            w.NetWeight = oi.NET_WEIGHT__c;
            w.DeliveredQty = oi.Delivered_Quantity__c;
            w.DeliveredQtyInCases = oi.Fulfilled_Quantity_in_Cases__c;
            w.DeliveredNetWeight = oi.Delivered_Net_Weight__c;
            
            w.OrderName = oi.Order__r.Name;
            w.OrderDate = oi.Order__r.Order_Date__c;
            
            results.add(w);
        }
        return results;
    }
}