force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order Request</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Order Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <label>Customer Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary Order</fullName>
            </value>
            <value>
                <fullName>Secondary Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Push_to_Logistics__c.field-meta.xml
<CustomField>
    <fullName>Push_to_Logistics__c</fullName>
    <label>Push to Logistics</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Order_Status1</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/PushToLogisticsBatch.cls
public class PushToLogisticsBatch
    implements Database.Batchable<SObject>, Database.Stateful, Database.AllowsCallouts {

    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            'SELECT Id, Name, Status__c, Push_to_Logistics__c ' +
            'FROM Order__c ' +
            'WHERE Order_Type__c = \'Primary Order\' ' +
            'AND Push_to_Logistics__c = null'
        );
    }

    public void execute(Database.BatchableContext bc, List<Order__c> scope) {

        for (Order__c ord : scope) {
            // Enqueue ONE order per Queueable
          //  System.enqueueJob(new PushOrderToSAQueueable(ord.Id));
	PostHandler.orderPost(ord);
        }
    }

    public void finish(Database.BatchableContext bc) {
        System.debug('PushToLogistics batch completed');
    }
}