force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order Request</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Order Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Account)</relationshipLabel>
    <relationshipName>Orders2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Customer_type__c.field-meta.xml
<CustomField>
    <fullName>Customer_type__c</fullName>
    <label>Customer type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary Customer</fullName>
            </value>
            <value>
                <fullName>Secondary Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/DISTRICT__c.field-meta.xml
<CustomField>
    <fullName>DISTRICT__c</fullName>
    <formula>TEXT(Account__r.District__c)</formula>
    <label>DISTRICT</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Store)</relationshipLabel>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>RE - {00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <formula>IF(
  Text(Order__r.Order_Type__c) = &apos;Primary Order&apos;,
  &apos;Primary&apos;,
  IF(
    Text(Order__r.Account__r.Secondary_Customer_Type__c) = &apos;Sub Stockiest&apos;,
    &apos;Sub Stockiest&apos;,
    &apos;Outlet&apos;
  )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order_Date__c.field-meta.xml
<CustomField>
    <fullName>Order_Date__c</fullName>
    <formula>Order__r.Order_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/ProductCode__c.field-meta.xml
<CustomField>
    <fullName>ProductCode__c</fullName>
    <label>ProductCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/SKU_Code__c.field-meta.xml
<CustomField>
    <fullName>SKU_Code__c</fullName>
    <externalId>true</externalId>
    <label>SKU Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/postHandler_TestClass.cls
@isTest
private class postHandler_TestClass 
{
    private class FakeHttpResponseGenerator implements HttpCalloutMock {
        private String responseBody;
        private Integer statusCode;
        private String endPoint;
        
        public FakeHttpResponseGenerator(String responseBody, Integer statusCode, string endPoint) {
            this.responseBody = responseBody;
            this.statusCode = statusCode;
            this.endPoint = endPoint;
        }
        
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setBody(responseBody);
            req.setEndpoint(endPoint);
            res.setStatusCode(statusCode);
            return res;
        }
    }
    
    static testMethod void testmeth(){
        Profile testProfile = [SELECT Id FROM Profile WHERE Name = 'HR' LIMIT 1];
        
        User newUser = new User();
        newUser.FirstName = 'Test';
        newUser.LastName = 'User005';
        newUser.Email = 'testuswqer@example.com';
        newUser.Username = 'tesqwtww203424@example.com';
        newUser.Alias = 'tuser';
        newUser.CommunityNickname = 'testuser';
        newUser.TimeZoneSidKey = 'America/Los_Angeles';
        newUser.LocaleSidKey = 'en_US';
        newUser.EmailEncodingKey = 'UTF-8';
        newUser.ProfileId = testProfile.Id;
        newUser.LanguageLocaleKey = 'en_US';
        newUser.Employee_Code__c ='1aa21';
        insert newUser;
        
        
        Account acc= new Account();
        acc.Name='Test Account';
        acc.Customer_Type__c = 'Primary Customer';
        acc.Primary_Phone_Number__c ='3121212112';
        acc.State__c='Kerala';
        acc.District__c='Kozhikode';
        insert acc;
        
        Product__c prd=new Product__c();
        prd.Name='sample Product';
        prd.ProductCode__c='test1';
        prd.SKU_Code__c='2ds';
        insert prd;
        
        Order__c ord=new Order__c();
        ord.Order_Date__c= system.today();
      //  ord.Store__c = acc.id;
        ord.account__c = acc.id;
        ord.ownerId=newUser.id;
        insert ord;
        
        Order_Item__c orditem = new Order_Item__c();
        orditem.Product__c=prd.id;
        orditem.Order__c=ord.id;
        orditem.Total_Amount__c=12;
        insert orditem;
        
        Order__c ords=new Order__c();
        ords.Order_Date__c= system.today();
        ords.Store__c = acc.id;
        ords.ownerId=newUser.id;
        insert ords;
        system.debug('ords '+ords);
        list<string>abc= new list<string>();
        String expectedAccessToken1 = '{"access_token":"sampleAccessToken"}';
        
        // String expectedAccessToken2 = '{"access_token":"null"}';
        
        Test.setMock(HttpCalloutMock.class, new FakeHttpResponseGenerator(expectedAccessToken1, 200,'Test'));
        
        Test.startTest();
       // SAPIntegrationController.getAccounts(acc.id);
        postHandler.sendOrder(ord.Id);
     //   postHandler.checkOrderSAP_Status(ord.Id);
        Test.StopTest();
    }
       static testMethod void testmeth01(){
        Profile testProfile = [SELECT Id FROM Profile WHERE Name = 'HR' LIMIT 1];
        
        User newUser = new User();
        newUser.FirstName = 'Test';
        newUser.LastName = 'User005';
        newUser.Email = 'testuswqer@example.com';
        newUser.Username = 'tesdqwtww203424@example.com';
        newUser.Alias = 'tuser';
        newUser.CommunityNickname = 'testuser';
        newUser.TimeZoneSidKey = 'America/Los_Angeles';
        newUser.LocaleSidKey = 'en_US';
        newUser.EmailEncodingKey = 'UTF-8';
        newUser.ProfileId = testProfile.Id;
        newUser.LanguageLocaleKey = 'en_US';
        newUser.Employee_Code__c ='1aad21';
        insert newUser;
        
        
        Account acc= new Account();
        acc.Name='Test Account';
        acc.Primary_Phone_Number__c ='3121212112';
        acc.State__c='Kerala';
        acc.District__c='Kozhikode';
        insert acc;
        
       
        list<string>abc= new list<string>();
        String expectedAccessToken1 = '{"access_token":"sampleAccessToken"}';
        
        // String expectedAccessToken2 = '{"access_token":"null"}';
        
        Test.setMock(HttpCalloutMock.class, new FakeHttpResponseGenerator(expectedAccessToken1, 200,'Test'));
        
        Test.startTest();
       // SAPIntegrationController.getAccounts(acc.id);	
        postHandler.accPost(acc,true);
     //   postHandler.checkOrderSAP_Status(ord.Id);
        Test.StopTest();
    }
   /* static testMethod void testmeth1(){
        Profile testProfile = [SELECT Id FROM Profile WHERE Name = 'HR' LIMIT 1];
        
        User newUser = new User();
        newUser.FirstName = 'Test';
        newUser.LastName = 'User005';
        newUser.Email = 'testuser@example.com';
        newUser.Username = 'testww203424@example.com';
        newUser.Alias = 'tuser';
        newUser.CommunityNickname = 'testuser';
        newUser.TimeZoneSidKey = 'America/Los_Angeles';
        newUser.LocaleSidKey = 'en_US';
        newUser.EmailEncodingKey = 'UTF-8';
        newUser.ProfileId = testProfile.Id;
        newUser.LanguageLocaleKey = 'en_US';
        insert newUser;
        
        
        Account acc= new Account();
        acc.Name='Test Account';
        //  acc.Mobile__c='9876578756';
   //     acc.Email__c='sample@asd.com';
        insert acc;
        
        Product__c prd=new Product__c();
        prd.Name='sample Product';
        prd.ProductCode__c='test1';
        insert prd;
        
        Order__c ord=new Order__c();
        ord.Order_Date__c= system.today();
        ord.Store__c = acc.id;
        ord.ownerId=newUser.id;
        insert ord;
        
        Order_Item__c orditem = new Order_Item__c();
        orditem.Product__c=prd.id;
        orditem.Order__c=ord.id;
        insert orditem;
        
        Order__c ords=new Order__c();
        ords.Order_Date__c= system.today();
        ords.Store__c = acc.id;
        ords.ownerId=newUser.id;
        insert ords;
        system.debug('ords '+ords);
        list<string>abc= new list<string>();
        String expectedAccessToken1 = '{"access_token":"sampleAccessToken"}';
        
        Test.setMock(HttpCalloutMock.class, new FakeHttpResponseGenerator(expectedAccessToken1, 0,'trst'));
        Test.startTest();
        postHandler.sendOrder(ord.Id);
        Test.StopTest();
    }
    
    static testMethod void testmeth2(){
        Profile testProfile = [SELECT Id FROM Profile WHERE Name = 'HR' LIMIT 1];
        
        User newUser = new User();
        newUser.FirstName = 'Test';
        newUser.LastName = 'User005';
        newUser.Email = 'testuser@example.com';
        newUser.Username = 'testww203424@example.com';
        newUser.Alias = 'tuser';
        newUser.CommunityNickname = 'testuser';
        newUser.TimeZoneSidKey = 'America/Los_Angeles';
        newUser.LocaleSidKey = 'en_US';
        newUser.EmailEncodingKey = 'UTF-8';
        newUser.ProfileId = testProfile.Id;
        newUser.LanguageLocaleKey = 'en_US';
        insert newUser;
        
        
        Account acc= new Account();
        acc.Name='Test Account';
   //     acc.Email__c='sample@asd.com';
        insert acc;
        
        Product__c prd=new Product__c();
        prd.Name='sample Product';
        prd.ProductCode__c='test1';
        insert prd;
        
        Order__c ord=new Order__c();
        ord.Order_Date__c= system.today();
        ord.Store__c = acc.id;
        ord.ownerId=newUser.id;
        insert ord;
        
        Order_Item__c orditem = new Order_Item__c();
        orditem.Product__c=prd.id;
        orditem.Order__c=ord.id;
        insert orditem;
        
        Order__c ords=new Order__c();
        
        ords.Store__c = acc.id;
        ords.ownerId=newUser.id;
        insert ords;
        system.debug('ords '+ords);
        list<string>abc= new list<string>();
        String expectedAccessToken1 = '{"access_token":"sampleAccessToken"}';
        String username = 'your_username';
        String password = 'your_password';
        Test.setMock(HttpCalloutMock.class, new FakeHttpResponseGenerator(expectedAccessToken1, 2000,'test'));
       
      postHandler.sendOrder(ord.Id);
  
       //  SAPIntegrationController.testMeth();
      
    }    */
}