force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order Request</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Order Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Order_Status1</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/RejectOrder.cls
public class RejectOrder {
    @AuraEnabled
    public static string rejectOrder(string recordId)
    {
        try {
            List<Order__c> ordList = [select Id,Name,Status__c from Order__c where Id =:recordId ];
            if (ordList.isEmpty()) {  return 'Error: ORDER_NOT_FOUND'; }
            Order__c ord = ordList[0];
            // Check if the replacement has already been done
            if (ord.Status__c == 'Rejected' ) {
                return 'Error: REJECTION_COMPLETED';
            }
            
            ord.Status__c = 'Rejected';
            update Ord;
            return 'Success:Order has been rejected successfully.';
        }
        catch (Exception ex) {
            System.debug('Exception in rejcting order: ' + ex.getMessage());
            return 'Error: ' + ex.getMessage();
        }
        
    }
}